// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorageClient creates a new instance of MockStorageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockStorageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockStorageClient is an autogenerated mock type for the StorageClient type
type MockStorageClient struct {
	mock.Mock
}

type MockStorageClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageClient) EXPECT() *MockStorageClient_Expecter {
	return &MockStorageClient_Expecter{mock: &_m.Mock}
}

// PresignUpload provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) PresignUpload(ctx context.Context, contentType string, filename string) (string, map[string]string, error) {
	ret := _mock.Called(ctx, contentType, filename)

	if len(ret) == 0 {
		panic("no return value specified for PresignUpload")
	}

	var r0 string
	var r1 map[string]string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, map[string]string, error)); ok {
		return returnFunc(ctx, contentType, filename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, contentType, filename)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) map[string]string); ok {
		r1 = returnFunc(ctx, contentType, filename)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, contentType, filename)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStorageClient_PresignUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignUpload'
type MockStorageClient_PresignUpload_Call struct {
	*mock.Call
}

// PresignUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - contentType string
//   - filename string
func (_e *MockStorageClient_Expecter) PresignUpload(ctx any, contentType any, filename any) *MockStorageClient_PresignUpload_Call {
	return &MockStorageClient_PresignUpload_Call{Call: _e.mock.On("PresignUpload", ctx, contentType, filename)}
}

func (_c *MockStorageClient_PresignUpload_Call) Run(run func(ctx context.Context, contentType string, filename string)) *MockStorageClient_PresignUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageClient_PresignUpload_Call) Return(url string, fields map[string]string, err error) *MockStorageClient_PresignUpload_Call {
	_c.Call.Return(url, fields, err)
	return _c
}

func (_c *MockStorageClient_PresignUpload_Call) RunAndReturn(run func(ctx context.Context, contentType string, filename string) (string, map[string]string, error)) *MockStorageClient_PresignUpload_Call {
	_c.Call.Return(run)
	return _c
}
