---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb
  namespace: backend
spec:
  encryptedData:
    MONGODB_URI: AgAtfp8C7j3fYQXR+wDY541/k/o1BZH7v1y23b4ZbKMPMuKDsS4JFJFYjfZYc9LbOZiVCoVIGpcVSsFqkK61xpuf5LPC0xrkbVtqCHcffGS+ZjpOPV/I8pMqn79m8gAPJFN4re228lY7IT1oF1TZKBo/ijmK7cHJL1YCxfrRtnZV6nX5XlvduzkXVnFSPVkxWner5lhdb3TbMjNwD4OJ2TLtXjakzSKGac+4dWULFU2aNlAqREgpWc3pMZTdjl86ib4A+gy6S4NcXn4kN17l6Xlibpcz6dKWLZcfEN6GeDIf82wyDVN+A3UJIzGgc95J7etVNjxa+eKwLanY40lp/Mwg6H9/QR/arpR9qtuwwrYlZ0Bxc6oyp6JRlz0QHgUeKQ1ErCjxoGPVy6N3Ff5peu8L2U6eNJMhcSr4ASYSFaYIse9JisxJUHNd/vYV9BgBZVHLwO2JenbH+GIutPP5ft2P6/jHFpd9cuSupWIdJS54/a+cpMP13UFp1fJo04Uesoa4YI2D4QWodD79V3EK+XBETVjDjpWp8YasWBB26a70n37TfCRarncHsu9XtyTxeeTYkbyvrEvZnbAD9vcMCdIHfoUAJhXQUfYEUpg1O9y4VnfB09q2lTrLPHy4mnIG5iO6pS1O4jrmSclVs7px8Ko4Wu3tiYEp2toKOXdGttVlIsgLjddOU8T/Jy2ORt275YlFwHJx3nMFb8xLyYoduVB9kXw0WOwTG3vORLCNPRSQVIEkzwT64KXTCyVEvm6WcpHG6DnWVA7X6vzRnRYXI1VsrHkln1KJL81OQF1n649bcWosxJFCLay9qtbOyjFSBO6CGtpOsQE1lbBgirBAnrMTusqqXXy2Ljgwevw+LZpCDA3OKvR6Tqxo923Ezw2/BYfARocGGUaQoB35M/SFXA==
  template:
    metadata:
      name: mongodb
      namespace: backend
