---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb
  namespace: backend
spec:
  encryptedData:
    MONGODB_URI: AgDBrfatyj+PLArhenkxcQLrt/O0YonoNpWHpwz2OhcwqflsysygYZQKpaycFl9ADpskHmSeD44pLc4Nh/uu5zy9K7WifTOHOfR0Tg2Rko0sq8v72My1l0Pus5HC9pIdgQ7JHHtFbNqbJxqx2Ibpb+QcN9qvC7JiHIEDke9p1tXCBDCqg58QH7hukBuVEbDXdOUQ3+zKnB1mt4+pVQZmBOWYEUdxdC9A9F0tgBb8Y4Yk4a3Zcb3tksWj4qx6+dnqukcpyEcbcHiEyy5TK6QFkMxndkbWTCsejpVRtcYXgbCMizLThq6qiO6QUseo4m7v4wXlN8b/ICIGsO3bF4HygsVotqscymfR2tm+nqELr/wfe/rP3zCBxh823Q1IBZQWbdO/+/4CZ8t/CqA8/M49X09OE+5ubqf48OQXpa8yc9ANVBnUlhD01J2xXLv7FLiSkwPdH/XzpFMSTOF1w6jVD28E+TUmA6jgl8BBMzA9G2OXIKhGTWlG+5k/wiY5kJvP3cm+jeFGn3eMuiS33q34YBjXDzJN1J5CSb9BjYMsEqqiCwpTOnASE4pft/h/NR36MTdLHp6furBynEsWDIq5dsbAPJNHF1SVdXvsZE0V7MGYEF2l8ortSK5rdl8kOp837kHUCDVHbkTF7h0hmzhreIR4iMgUoY2+IlLsKfGoT/ud4xvnjgEsxfHbOFoIyAShv8zIeiHHX1eNOtg/tXHKlUAMJpYAOYGt60V7Pie+WUhjtil29wbjpe/JuQqnNlhMRQPATroQlvYYpq6DkEKujqF6WEL3p3MNTHIqlfo3IP9JxF2h1H9jK9mPcwmIdAScqZ04AieoLJyLGTIIGfpVuy4UAqFoiI/Qb+KKdiepk+OnD+TmHsWKpDjmfCwBBlK5eT9F4zWN0c9GLEGWFPz2vg==
  template:
    metadata:
      name: mongodb
      namespace: backend
