---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: astradb
  namespace: backend
spec:
  encryptedData:
    ASTRADB_TOKEN: AgAlbVMBIQqr89Uas07GzbWwmkI6EjvUNCz7oaoNCoA29SeRbY8Ft3yXXGNjIhBoWIylpefs2KpBV7nZxmcn1SgDZYBobWaToZd8RryrjP6Ufpkkc6iLZYCXOmKJpy3OUzGlroAuAsXUvVUvlCMy1fF6u6tGSS6fe2BzZ+5p3WKfs828MagMv+omQsugcy37XgunXiVu4xDKl2ivLT4lyP7EcAqLkf+zfVMegIwkuLS8yVVIimhrlvcyBtV4DEWiijy5PfExrgpOq2SkfUKMMS0ABL0AG5MfO0ONE1xCJbSz4ZXeX0ILGzA/MeoiZY7zSvHQYYxRJvGniwHWMZ6asndgMNSDisb6IwISyfBc5zV6ZFguPme4DKceNG/6kGRc0i4PZ5YSWulz9YMnvZo+bDuk+i9VyuAiAWd9mQfsLQHnCELvJBtH/6xzCOzGe2K104APFRGcKr3Z0joir3DIBCfZVN6sqVkGsqjtau81kmOC1bn0BWLPEzW5f2Q/BjmJWSqCNCble/i44eUMFIErxkcc3l20bOuYyuIxuy+wPjt0O1vdvLRGIAI1UvKKa6dQQ04KqK5BuvlLTbiUfnuSsxZsI0KcuaeJ3orncuN5iHJBO+QKlmO20/8uBuvMcRC/gywi/mR4gHifWJIaF+LOaA7gAg4fJGXAL91df+seHSOIhrQB4jZO3SdP+Q/vqNF+PtzKEl0CxjIyUG/G2CxhgmmfcGYjhk9fuhFcJcoCPwQFs9NrZOKKf5v0Gmd0NrVFDF2wS1FgKyf2kq++dBVK5i5ALXhio0f/WoErEstZBuoX2p1n5EeCI9++lvzGXYpMqv73
  template:
    metadata:
      name: astradb
      namespace: backend
