---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp
  namespace: backend
spec:
  encryptedData:
    FROM_EMAIL_PASSWORD: AgA9Lfd3qt3h/gJdrC3bAiIPyHmxZ8xxmJAgu6KohxvlYLi++WYdMoeg6uZb8h9VOaJNQzNxCC/ReMBMIeWkCik2EdY3hlA69bHu3bgD4vnl9aL3i/5K6sg8LuwvapJ7QmJkKYyYB1VXfbT7oDT9lXgWWJFNLnN4CR/PrW9D5NO9nya8su+yHONXFNNdnUZgQB/M/ukapjNWKyEAFGIz2IR+WIL75G4U55TKvOTT5AQrg2IZ7eBQzfF5K1eqqqcMELhtLApogj9TBTbpTkpopRQKUmhaSXNJVfZrH25IfVtraWYP7MldDgYuRx36VYI8SnRcMTf8G8woSHayZE854/GKUcTKgLjmQ6n97zbzlfLBp9ykihK84YWKJwOqZLTiFApOhSRLKH29777FdJjzcrY1Dd8DEem0FPbvoATvqNYc7Z/vfaYpvrw0HsFWJxs8vh9XB6lN3O92kPPDOJRWHI6pHMUu95Hq/kxbg8fIaOOlUKI+Imijq1hVEilODgBhgKFeD5caEFH6gFd5lwAJu7cgfUpY7Au/22ggZXtJGfFHpEYxKmqoIRCiWnELwbk8i7+ATUuz8o06SIRN+KqPCzAcGBGEDn4wfwn7fauUhc5NSzhNwRlAoeEUrNtfiBPuNTrwSTsEzdl38cRNMCqOnKMokR1HCQ21Arwn/ZT5CSHKEx7ZOHYT4SPyEs7bla3IkysLayOqKu146mpl8diMl4Cc
  template:
    metadata:
      name: smtp
      namespace: backend
