// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFCMClient creates a new instance of MockFCMClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFCMClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFCMClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFCMClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFCMClient is an autogenerated mock type for the FCMClient type
type MockFCMClient struct {
	mock.Mock
}

type MockFCMClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFCMClient) EXPECT() *MockFCMClient_Expecter {
	return &MockFCMClient_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockFCMClient
func (_mock *MockFCMClient) Send(ctx context.Context, tokens []string, title string, body string, imageURL string) ([]string, error) {
	ret := _mock.Called(ctx, tokens, title, body, imageURL)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, string, string) ([]string, error)); ok {
		return returnFunc(ctx, tokens, title, body, imageURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, string, string) []string); ok {
		r0 = returnFunc(ctx, tokens, title, body, imageURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, string, string, string) error); ok {
		r1 = returnFunc(ctx, tokens, title, body, imageURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFCMClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockFCMClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - tokens []string
//   - title string
//   - body string
//   - imageURL string
func (_e *MockFCMClient_Expecter) Send(ctx any, tokens any, title any, body any, imageURL any) *MockFCMClient_Send_Call {
	return &MockFCMClient_Send_Call{Call: _e.mock.On("Send", ctx, tokens, title, body, imageURL)}
}

func (_c *MockFCMClient_Send_Call) Run(run func(ctx context.Context, tokens []string, title string, body string, imageURL string)) *MockFCMClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockFCMClient_Send_Call) Return(invalidTokens []string, err error) *MockFCMClient_Send_Call {
	_c.Call.Return(invalidTokens, err)
	return _c
}

func (_c *MockFCMClient_Send_Call) RunAndReturn(run func(ctx context.Context, tokens []string, title string, body string, imageURL string) ([]string, error)) *MockFCMClient_Send_Call {
	_c.Call.Return(run)
	return _c
}
