// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"context"

	"github.com/apache/cassandra-gocql-driver/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// DidNotification provides a mock function for the type MockRepository
func (_mock *MockRepository) DidNotification(ctx context.Context, messageId string, notificationId string) (bool, error) {
	ret := _mock.Called(ctx, messageId, notificationId)

	if len(ret) == 0 {
		panic("no return value specified for DidNotification")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, messageId, notificationId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, messageId, notificationId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, messageId, notificationId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_DidNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DidNotification'
type MockRepository_DidNotification_Call struct {
	*mock.Call
}

// DidNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - messageId string
//   - notificationId string
func (_e *MockRepository_Expecter) DidNotification(ctx any, messageId any, notificationId any) *MockRepository_DidNotification_Call {
	return &MockRepository_DidNotification_Call{Call: _e.mock.On("DidNotification", ctx, messageId, notificationId)}
}

func (_c *MockRepository_DidNotification_Call) Run(run func(ctx context.Context, messageId string, notificationId string)) *MockRepository_DidNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_DidNotification_Call) Return(b bool, err error) *MockRepository_DidNotification_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_DidNotification_Call) RunAndReturn(run func(ctx context.Context, messageId string, notificationId string) (bool, error)) *MockRepository_DidNotification_Call {
	_c.Call.Return(run)
	return _c
}

// MarkNotification provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkNotification(ctx context.Context, messageId string, notificationId string) error {
	ret := _mock.Called(ctx, messageId, notificationId)

	if len(ret) == 0 {
		panic("no return value specified for MarkNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, messageId, notificationId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkNotification'
type MockRepository_MarkNotification_Call struct {
	*mock.Call
}

// MarkNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - messageId string
//   - notificationId string
func (_e *MockRepository_Expecter) MarkNotification(ctx any, messageId any, notificationId any) *MockRepository_MarkNotification_Call {
	return &MockRepository_MarkNotification_Call{Call: _e.mock.On("MarkNotification", ctx, messageId, notificationId)}
}

func (_c *MockRepository_MarkNotification_Call) Run(run func(ctx context.Context, messageId string, notificationId string)) *MockRepository_MarkNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_MarkNotification_Call) Return(err error) *MockRepository_MarkNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkNotification_Call) RunAndReturn(run func(ctx context.Context, messageId string, notificationId string) error) *MockRepository_MarkNotification_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveNotificationInfoByIdAndToken provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveNotificationInfoByIdAndToken(ctx context.Context, id gocql.UUID, token string) error {
	ret := _mock.Called(ctx, id, token)

	if len(ret) == 0 {
		panic("no return value specified for RemoveNotificationInfoByIdAndToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RemoveNotificationInfoByIdAndToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveNotificationInfoByIdAndToken'
type MockRepository_RemoveNotificationInfoByIdAndToken_Call struct {
	*mock.Call
}

// RemoveNotificationInfoByIdAndToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id gocql.UUID
//   - token string
func (_e *MockRepository_Expecter) RemoveNotificationInfoByIdAndToken(ctx any, id any, token any) *MockRepository_RemoveNotificationInfoByIdAndToken_Call {
	return &MockRepository_RemoveNotificationInfoByIdAndToken_Call{Call: _e.mock.On("RemoveNotificationInfoByIdAndToken", ctx, id, token)}
}

func (_c *MockRepository_RemoveNotificationInfoByIdAndToken_Call) Run(run func(ctx context.Context, id gocql.UUID, token string)) *MockRepository_RemoveNotificationInfoByIdAndToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_RemoveNotificationInfoByIdAndToken_Call) Return(err error) *MockRepository_RemoveNotificationInfoByIdAndToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RemoveNotificationInfoByIdAndToken_Call) RunAndReturn(run func(ctx context.Context, id gocql.UUID, token string) error) *MockRepository_RemoveNotificationInfoByIdAndToken_Call {
	_c.Call.Return(run)
	return _c
}
