plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.6.1'
}

group = 'exponentialbackoffretryjob'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

ext {
    flinkVersion = '2.2.1'
    kafkaConnectorVersion = '5.0.0-2.2'
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly "org.apache.flink:flink-streaming-java:${flinkVersion}"
    compileOnly "org.apache.flink:flink-clients:${flinkVersion}"
    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    implementation "org.apache.flink:flink-connector-kafka:${kafkaConnectorVersion}"
    implementation "org.apache.flink:flink-statebackend-rocksdb:${flinkVersion}"
    implementation "com.fasterxml.jackson.core:jackson-databind"
}

shadowJar {
    archiveBaseName.set('exponentialbackoffretryjob')
    archiveClassifier.set('')
    archiveVersion.set(project.version.toString())

    manifest {
        attributes 'Main-Class': 'exponentialbackoffretryjob.RetryJob'
    }

    relocate 'org.apache.kafka', 'exponentialbackoffretryjob.shaded.kafka'

    mergeServiceFiles()
}

tasks.named('build') {
    dependsOn tasks.named('shadowJar')
}
