apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      istio.io/gateway-name: cluster-gateway
  jwtRules:
    - issuer: {{ .Values.auth.issuer | quote }}
      jwks: |
        {
          "keys": [
            {
              "kty": "oct",
              "alg": "HS256",
              "k": {{ .Values.auth.base64UrlSecret | quote }}
            }
          ]
        }
      outputClaimToHeaders:
        - claim: sub
          header: X-User-Id
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      istio.io/gateway-name: cluster-gateway
  action: ALLOW
  rules:
    # 1. Hardcoded bypass for the Auth Service
    - to:
        - operation:
            paths:
              - "/auth"
              - "/auth/*"

    # 2. Require a valid JWT for the Chat and Notification services
    - from:
        - source:
            requestPrincipals: ["*"]