apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ $name }}-circuit-breaker
  namespace: {{ .Values.namespace }}
spec:
  host: {{ $name }}
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: {{ $.Values.circuitBreaker.maxConnections }}
    outlierDetection:
      consecutive5xxErrors: {{ $.Values.circuitBreaker.consecutiveErrors }}
      baseEjectionTime: {{ $.Values.circuitBreaker.baseEjectionTime }}
