spec:
  template:
    spec:
      containers:
        - name: nvidia-device-plugin-ctr
          args: ["--config-file=/etc/nvidia-plugin/config.yaml"]
          volumeMounts:
            - name: plugin-config
              mountPath: /etc/nvidia-plugin
      volumes:
        - name: plugin-config
          configMap:
            name: gpu-slicing-config

#kubectl patch daemonset nvidia-device-plugin-daemonset -n kube-system --patch-file gpu-slicing-patch.yaml