apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-system
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: strimzi-operator
            repo: quay.io/strimzi-helm
            chart: strimzi-kafka-operator
            version: 0.45.2
            namespace: kafka-system
            wave: "1"
            customValues: ""

  template:
    metadata:
      name: '{{appName}}'
      annotations:
        # This tells ArgoCD what order to deploy the apps in!
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: default
      source:
        repoURL: '{{repo}}'
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          # Injects the specific values, ignores if empty string
          valuesObject: '{{customValues}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true