---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafanacloud
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_CLOUD_TOKEN: AgBTirYEkvIkw4/D1kH2o+pUVVaG8sQ7rJynpAqKNCgVbpNRjYSLVfBhQvkvgJolrulLp0tuS9CHIACRoxgGdHsOXeJ1wMOvLwEoUZwK9KCfbkNUNQE0X77yUpuggGR/gRN/TcfrHbe3YegXKgzun3MMTSHBa71L/2ogdLyolaa3VcK8IMbGZ/CB7UlqjafaTrAyXqtZY1GOHaEGSo2PeOOcia8/RUmwIK6BevSC5ZKy56cvKu5I5lsdny55JWCRpbQxFJXtX1X6UwHO8GATRiZNi9BPwOifX4ffpiMyObPkPT3n+i+aV4/pkPzSDLNyN/YnLRSh+W3Sp/6E8gQtbtkTVrQGyXMjZjqObaP/GYIizZ4L0Ap9b3twr75xe/VQZxdYCpbeCdSMXCRV2zjRnY+CDBuyeIkCTYg5zak/w7nH0FgvcnjCtd/zWBTJKMi9hi44sukLjyQkYNdN9RmGjPWs6LFmMdQeKf8aSbcvACFoV7ZE4Ns2Avdssf6X3GSipaBM9AloZ++x97EjBczUul9ykCwjFe1+3vIfhNJKFKulyqym4XZblFEgBNmXHgxRpn8du0998slgA7uH32hq6WnsOpflH4i8qya+VyNZYy4qcsTxZqrxwyaz6Y/EmqC8nsnqinJVcxidJZWGYmbz89QU9jcMWcQExRkPL3n0dkIUNepgApyFnZoC4rLvnCb//vibyJTEde18B7FxGVHipq4OvkbIMstOV/LxZlhKba0IMPLTvVspjhY2uIqeGSfACurSXv+noar8vA8khnOT9RGSk94b/sadIpwDR2zN021whrK7AbhGmkpuJeyJz26XmI0c4pKdiNRuui47SoQ6P/upNrmeDgxNC4qZJtpSQyambuTAvX4pHZkyuPClarRHcfQi/qifE1SBnnfouHo=
  template:
    metadata:
      name: grafanacloud
      namespace: monitoring
