apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: valkey
  namespace: valkey-system
spec:
  encryptedData:
    lule: AgCEAWIuKqs4+fVX2JCuCi80Rer+mHrJKEOypLFrNwgvxYDs0xXkZLv5/bu65i50OJtaaZBaO6UxP1zAKdLUJbTii0ETSZ1feH1hvrgu1JsjH0SxFfPS7BRTxrDMiT1msngAh483ISEmEP3H4f09+cedFEbEqRa6lHlTiUpRZXfUGMr5pWpAQjl0qjxpQ/9glh4i1lmut8j1oQXrqzMLPI5H/SDn9u5qnAdG03ldWynqm4oSBnAKGchvRsCh+AVz4YKzwU6cwOciQSmBJFfTdyCaPYrY6lEVLfuwTCjjriW8+kemz4IsaxtDLMUlNgBQqCGemPfEicgDgKrDOY4XQbdQzX0dk5s2wDEwO8u9EpIek0vZFvBe360ClrfW9XFw8qzjrZuwtnAQDCAvPeCL9jcwXwvmZQrS8tiGu8ncB6VZsrue+pDvMfECH7bm2gb69IfV8ehB2MkrheY/zC2avrZbw9gOjFcxB6eqZWMDIbdlvh4GBvjzyPNy8r/hJsVoiIGXe+lqLDUwUAGGFJVBfJMiHvaojkUW7BYTIu7tihvQ107FP8jk6D8jmS4HQLLCQl4iMjFS04VE99bY1IcvSvsbGujYPztdbk7zpT8pNDRD9MwR+zwAf9g3zaLY7roU9pKslDlFiIXMX312JGSeclmRw8sblXc4awR5Bga6Cy1DSG+Fb7tKyJ2o4kLAa1HGOrsTJS2iFK31+coTqA==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: backend
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: backend
      name: valkey
      namespace: valkey-system
    type: Opaque
