// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: proto/messaging.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelayMessagingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ToIds         [][]byte               `protobuf:"bytes,2,rep,name=toIds,proto3" json:"toIds,omitempty"`
	RoomId        []byte                 `protobuf:"bytes,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	FromId        []byte                 `protobuf:"bytes,4,opt,name=fromId,proto3" json:"fromId,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Contents      []string               `protobuf:"bytes,6,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayMessagingRequest) Reset() {
	*x = RelayMessagingRequest{}
	mi := &file_proto_messaging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayMessagingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayMessagingRequest) ProtoMessage() {}

func (x *RelayMessagingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayMessagingRequest.ProtoReflect.Descriptor instead.
func (*RelayMessagingRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *RelayMessagingRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RelayMessagingRequest) GetToIds() [][]byte {
	if x != nil {
		return x.ToIds
	}
	return nil
}

func (x *RelayMessagingRequest) GetRoomId() []byte {
	if x != nil {
		return x.RoomId
	}
	return nil
}

func (x *RelayMessagingRequest) GetFromId() []byte {
	if x != nil {
		return x.FromId
	}
	return nil
}

func (x *RelayMessagingRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *RelayMessagingRequest) GetContents() []string {
	if x != nil {
		return x.Contents
	}
	return nil
}

type RelayMessagingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PushToIds     [][]byte               `protobuf:"bytes,1,rep,name=pushToIds,proto3" json:"pushToIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayMessagingResponse) Reset() {
	*x = RelayMessagingResponse{}
	mi := &file_proto_messaging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayMessagingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayMessagingResponse) ProtoMessage() {}

func (x *RelayMessagingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayMessagingResponse.ProtoReflect.Descriptor instead.
func (*RelayMessagingResponse) Descriptor() ([]byte, []int) {
	return file_proto_messaging_proto_rawDescGZIP(), []int{1}
}

func (x *RelayMessagingResponse) GetPushToIds() [][]byte {
	if x != nil {
		return x.PushToIds
	}
	return nil
}

var File_proto_messaging_proto protoreflect.FileDescriptor

const file_proto_messaging_proto_rawDesc = "" +
	"\n" +
	"\x15proto/messaging.proto\x12\x10messagingservice\"\xab\x01\n" +
	"\x15RelayMessagingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x14\n" +
	"\x05toIds\x18\x02 \x03(\fR\x05toIds\x12\x16\n" +
	"\x06roomId\x18\x03 \x01(\fR\x06roomId\x12\x16\n" +
	"\x06fromId\x18\x04 \x01(\fR\x06fromId\x12 \n" +
	"\vcontentType\x18\x05 \x01(\tR\vcontentType\x12\x1a\n" +
	"\bcontents\x18\x06 \x03(\tR\bcontents\"6\n" +
	"\x16RelayMessagingResponse\x12\x1c\n" +
	"\tpushToIds\x18\x01 \x03(\fR\tpushToIds2w\n" +
	"\x10MessagingService\x12c\n" +
	"\x0eRelayMessaging\x12'.messagingservice.RelayMessagingRequest\x1a(.messagingservice.RelayMessagingResponseB\x0fZ\rbackend/protob\x06proto3"

var (
	file_proto_messaging_proto_rawDescOnce sync.Once
	file_proto_messaging_proto_rawDescData []byte
)

func file_proto_messaging_proto_rawDescGZIP() []byte {
	file_proto_messaging_proto_rawDescOnce.Do(func() {
		file_proto_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messaging_proto_rawDesc), len(file_proto_messaging_proto_rawDesc)))
	})
	return file_proto_messaging_proto_rawDescData
}

var file_proto_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_messaging_proto_goTypes = []any{
	(*RelayMessagingRequest)(nil),  // 0: messagingservice.RelayMessagingRequest
	(*RelayMessagingResponse)(nil), // 1: messagingservice.RelayMessagingResponse
}
var file_proto_messaging_proto_depIdxs = []int32{
	0, // 0: messagingservice.MessagingService.RelayMessaging:input_type -> messagingservice.RelayMessagingRequest
	1, // 1: messagingservice.MessagingService.RelayMessaging:output_type -> messagingservice.RelayMessagingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_messaging_proto_init() }
func file_proto_messaging_proto_init() {
	if File_proto_messaging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messaging_proto_rawDesc), len(file_proto_messaging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_messaging_proto_goTypes,
		DependencyIndexes: file_proto_messaging_proto_depIdxs,
		MessageInfos:      file_proto_messaging_proto_msgTypes,
	}.Build()
	File_proto_messaging_proto = out.File
	file_proto_messaging_proto_goTypes = nil
	file_proto_messaging_proto_depIdxs = nil
}
