// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: proto/notification.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyMessagingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToIds         [][]byte               `protobuf:"bytes,1,rep,name=toIds,proto3" json:"toIds,omitempty"`
	RoomId        []byte                 `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	FromId        []byte                 `protobuf:"bytes,3,opt,name=fromId,proto3" json:"fromId,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyMessagingRequest) Reset() {
	*x = NotifyMessagingRequest{}
	mi := &file_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyMessagingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyMessagingRequest) ProtoMessage() {}

func (x *NotifyMessagingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyMessagingRequest.ProtoReflect.Descriptor instead.
func (*NotifyMessagingRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyMessagingRequest) GetToIds() [][]byte {
	if x != nil {
		return x.ToIds
	}
	return nil
}

func (x *NotifyMessagingRequest) GetRoomId() []byte {
	if x != nil {
		return x.RoomId
	}
	return nil
}

func (x *NotifyMessagingRequest) GetFromId() []byte {
	if x != nil {
		return x.FromId
	}
	return nil
}

func (x *NotifyMessagingRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *NotifyMessagingRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type NotifyMessagingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyMessagingResponse) Reset() {
	*x = NotifyMessagingResponse{}
	mi := &file_proto_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyMessagingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyMessagingResponse) ProtoMessage() {}

func (x *NotifyMessagingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyMessagingResponse.ProtoReflect.Descriptor instead.
func (*NotifyMessagingResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{1}
}

var File_proto_notification_proto protoreflect.FileDescriptor

const file_proto_notification_proto_rawDesc = "" +
	"\n" +
	"\x18proto/notification.proto\x12\x13notificationservice\"\x9a\x01\n" +
	"\x16NotifyMessagingRequest\x12\x14\n" +
	"\x05toIds\x18\x01 \x03(\fR\x05toIds\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\fR\x06roomId\x12\x16\n" +
	"\x06fromId\x18\x03 \x01(\fR\x06fromId\x12 \n" +
	"\vcontentType\x18\x04 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\"\x19\n" +
	"\x17NotifyMessagingResponse2\x83\x01\n" +
	"\x13NotificationService\x12l\n" +
	"\x0fNotifyMessaging\x12+.notificationservice.NotifyMessagingRequest\x1a,.notificationservice.NotifyMessagingResponseB\x0fZ\rbackend/protob\x06proto3"

var (
	file_proto_notification_proto_rawDescOnce sync.Once
	file_proto_notification_proto_rawDescData []byte
)

func file_proto_notification_proto_rawDescGZIP() []byte {
	file_proto_notification_proto_rawDescOnce.Do(func() {
		file_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_proto_rawDesc), len(file_proto_notification_proto_rawDesc)))
	})
	return file_proto_notification_proto_rawDescData
}

var file_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_notification_proto_goTypes = []any{
	(*NotifyMessagingRequest)(nil),  // 0: notificationservice.NotifyMessagingRequest
	(*NotifyMessagingResponse)(nil), // 1: notificationservice.NotifyMessagingResponse
}
var file_proto_notification_proto_depIdxs = []int32{
	0, // 0: notificationservice.NotificationService.NotifyMessaging:input_type -> notificationservice.NotifyMessagingRequest
	1, // 1: notificationservice.NotificationService.NotifyMessaging:output_type -> notificationservice.NotifyMessagingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_notification_proto_init() }
func file_proto_notification_proto_init() {
	if File_proto_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_proto_rawDesc), len(file_proto_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notification_proto_goTypes,
		DependencyIndexes: file_proto_notification_proto_depIdxs,
		MessageInfos:      file_proto_notification_proto_msgTypes,
	}.Build()
	File_proto_notification_proto = out.File
	file_proto_notification_proto_goTypes = nil
	file_proto_notification_proto_depIdxs = nil
}
