// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: proto/signal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelaySignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        []byte                 `protobuf:"bytes,1,opt,name=fromId,proto3" json:"fromId,omitempty"`
	ToId          []byte                 `protobuf:"bytes,2,opt,name=toId,proto3" json:"toId,omitempty"`
	Signal        []byte                 `protobuf:"bytes,3,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelaySignalRequest) Reset() {
	*x = RelaySignalRequest{}
	mi := &file_proto_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelaySignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelaySignalRequest) ProtoMessage() {}

func (x *RelaySignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelaySignalRequest.ProtoReflect.Descriptor instead.
func (*RelaySignalRequest) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{0}
}

func (x *RelaySignalRequest) GetFromId() []byte {
	if x != nil {
		return x.FromId
	}
	return nil
}

func (x *RelaySignalRequest) GetToId() []byte {
	if x != nil {
		return x.ToId
	}
	return nil
}

func (x *RelaySignalRequest) GetSignal() []byte {
	if x != nil {
		return x.Signal
	}
	return nil
}

type RelaySignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelaySignalResponse) Reset() {
	*x = RelaySignalResponse{}
	mi := &file_proto_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelaySignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelaySignalResponse) ProtoMessage() {}

func (x *RelaySignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelaySignalResponse.ProtoReflect.Descriptor instead.
func (*RelaySignalResponse) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{1}
}

var File_proto_signal_proto protoreflect.FileDescriptor

const file_proto_signal_proto_rawDesc = "" +
	"\n" +
	"\x12proto/signal.proto\x12\rsignalservice\"X\n" +
	"\x12RelaySignalRequest\x12\x16\n" +
	"\x06fromId\x18\x01 \x01(\fR\x06fromId\x12\x12\n" +
	"\x04toId\x18\x02 \x01(\fR\x04toId\x12\x16\n" +
	"\x06signal\x18\x03 \x01(\fR\x06signal\"\x15\n" +
	"\x13RelaySignalResponse2e\n" +
	"\rSignalService\x12T\n" +
	"\vRelaySignal\x12!.signalservice.RelaySignalRequest\x1a\".signalservice.RelaySignalResponseB\x0fZ\rbackend/protob\x06proto3"

var (
	file_proto_signal_proto_rawDescOnce sync.Once
	file_proto_signal_proto_rawDescData []byte
)

func file_proto_signal_proto_rawDescGZIP() []byte {
	file_proto_signal_proto_rawDescOnce.Do(func() {
		file_proto_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_signal_proto_rawDesc), len(file_proto_signal_proto_rawDesc)))
	})
	return file_proto_signal_proto_rawDescData
}

var file_proto_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_signal_proto_goTypes = []any{
	(*RelaySignalRequest)(nil),  // 0: signalservice.RelaySignalRequest
	(*RelaySignalResponse)(nil), // 1: signalservice.RelaySignalResponse
}
var file_proto_signal_proto_depIdxs = []int32{
	0, // 0: signalservice.SignalService.RelaySignal:input_type -> signalservice.RelaySignalRequest
	1, // 1: signalservice.SignalService.RelaySignal:output_type -> signalservice.RelaySignalResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_signal_proto_init() }
func file_proto_signal_proto_init() {
	if File_proto_signal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_signal_proto_rawDesc), len(file_proto_signal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_signal_proto_goTypes,
		DependencyIndexes: file_proto_signal_proto_depIdxs,
		MessageInfos:      file_proto_signal_proto_msgTypes,
	}.Build()
	File_proto_signal_proto = out.File
	file_proto_signal_proto_goTypes = nil
	file_proto_signal_proto_depIdxs = nil
}
