apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: {{.Values.namespace}}
data:
  PROFILE: "production"
  KAFKA_ADDRESS: "kafka-cluster-kafka-bootstrap.kafka-system.svc.cluster.local:9093"
  VALKEY_ADDRESS: "valkey-cluster.valkey-system.svc:6379"
  VALKEY_HOST: "valkey-cluster.valkey-system.svc"
  VALKEY_USERNAME: "lule"
  AWS_S3_REGION: "ap-northeast-2"
  AWS_S3_BUCKET_NAME: "chat-bucket-14129"
  AWS_CLOUDFRONT_URL: "https://djxowwus2kgwo.cloudfront.net"
  FROM_EMAIL: "wsxc20xx@gmail.com"
  FROM_EMAIL_SMTP: "smtp.gmail.com"
  SMTP_ADDR: "smtp.gmail.com:587"
  BUNDLE_IDENTIFIER: "com.xcecv.mobile"
