{{- range $name, $app := .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $name }}
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ $app.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ $app.port }}
          resources:
            requests:
              cpu: "0.1"
              memory: "100Mi"
            limits:
              cpu: "0.3"
              memory: "100Mi"
          {{- if $app.valkey }}
          env:
            - name: VALKEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: valkey
                  key: lule
          {{- end}}
          envFrom:
            - configMapRef:
                name: config-map
            {{- if $app.astradb }}
            - secretRef:
                name: astradb
            {{- end }}
            {{- if $app.aws }}
            - secretRef:
                name: aws
            {{- end }}
            {{- if $app.tidb }}
            - secretRef:
                name: tidb
            {{- end }}
            {{- if $app.smtp }}
            - secretRef:
                name: smtp
            {{- end }}
            {{- if $app.twilio }}
            - secretRef:
                name: twilio
            {{- end }}
          {{- if or $app.valkey $app.authentication $app.kafka $app.astradb $app.aws $app.firebase $app.mongodb }}
          volumeMounts:
            {{- if $app.valkey }}
            - name: valkey-cert-volume
              mountPath: "/cert/valkey"
              readOnly: true
            {{- end }}
            {{- if $app.authentication}}
            - name: authentication-volume
              mountPath: "/cert/authentication"
              readOnly: true
            {{- end}}
            {{- if $app.kafka }}
            - name: kafka-user
              mountPath: "/cert/kafka/user"
              readOnly: true
            - name: kafka-cluster-ca
              mountPath: "/cert/kafka/cluster"
              readOnly: true
            {{- end }}
            {{- if $app.astradb }}
            - name: astradb-volume
              mountPath: "/cert/astradb"
              readOnly: true
            {{- end }}
            {{- if $app.aws }}
            - name: aws-volume
              mountPath: "/cert/aws"
              readOnly: true
            {{- end }}
            {{- if $app.firebase }}
            - name: firebase-volume
              mountPath: "/cert/firebase"
              readOnly: true
            {{- end }}
            {{- if $app.mongodb }}
            - name: mongodb-volume
              mountPath: "/cert/mongodb"
              readOnly: true
            {{- end }}
          {{- end }}

      {{- if or $app.valkey $app.kafka $app.authentication $app.astradb $app.aws $app.firebase $app.mongodb }}
      volumes:
        {{- if $app.valkey }}
        - name: valkey-cert-volume
          secret:
            secretName: valkey-cert
            items:
              - key: ca.crt
                path: ca.crt
        {{- end }}
        {{- if $app.kafka }}
        - name: kafka-user
          secret:
            secretName: kafka-user
        - name: kafka-cluster-ca
          secret:
            secretName: kafka-cluster-cluster-ca-cert
        {{- end }}
        {{- if $app.authentication}}
        - name: authentication-volume
          secret:
            secretName: authentication-volume
        {{- end}}
        {{- if $app.astradb }}
        - name: astradb-volume
          secret:
            secretName: astradb-volume
        {{- end }}
        {{- if $app.aws }}
        - name: aws-volume
          secret:
            secretName: aws-volume
        {{- end }}
        {{- if $app.firebase }}
        - name: firebase-volume
          secret:
            secretName: firebase-volume
        {{- end }}
        {{- if $app.mongodb }}
        - name: mongodb-volume
          secret:
            secretName: mongodb-volume
        {{- end }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $name }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ $app.port }}

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

{{- end }}
