{{- range $name, $app := .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $name }}
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ $app.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ $app.port }}

          {{- if or $app.astradb $app.aws $app.mongodb $app.smtp $app.twilio }}
          envFrom:
            {{- if $app.astradb }}
            - secretRef:
                name: astradb
            {{- end }}
            {{- if $app.aws }}
            - secretRef:
                name: aws
            {{- end }}
            {{- if $app.mongodb }}
            - secretRef:
                name: mongodb
            {{- end }}
            {{- if $app.smtp }}
            - secretRef:
                name: smtp
            {{- end }}
            {{- if $app.twilio }}
            - secretRef:
                name: twilio
            {{- end }}
          {{- end }}

          {{- if or $app.authentication $app.kafka $app.astradb $app.aws $app.firebase $app.mongodb }}
          volumeMounts:
            {{- if $app.authentication}}
            - name: authentication-volume
              mountPath: "/authentication"
              readOnly: true
            {{- end}}
            {{- if $app.kafka }}
            - name: kafka-user
              mountPath: "/kafka"
              readOnly: true
            {{- end }}
            {{- if $app.astradb }}
            - name: astradb-volume
              mountPath: "/astradb"
              readOnly: true
            {{- end }}
            {{- if $app.aws }}
            - name: aws-volume
              mountPath: "/aws"
              readOnly: true
            {{- end }}
            {{- if $app.firebase }}
            - name: firebase-volume
              mountPath: "/firebase"
              readOnly: true
            {{- end }}
            {{- if $app.mongodb }}
            - name: mongodb-volume
              mountPath: "/mongodb"
              readOnly: true
            {{- end }}
          {{- end }}

      {{- if or $app.kafka $app.astradb $app.aws $app.firebase $app.mongodb }}
      volumes:
        {{- if $app.kafka }}
        - name: kafka-user
          secret:
            secretName: kafka-user
        {{- end }}
        {{- if $app.authentication}}
        - name: authentication-volume
          secret:
            secretName: authentication-volume
        {{- end}}
        {{- if $app.astradb }}
        - name: astradb-volume
          secret:
            secretName: astradb-volume
        {{- end }}
        {{- if $app.aws }}
        - name: aws-volume
          secret:
            secretName: aws-volume
        {{- end }}
        {{- if $app.firebase }}
        - name: firebase-volume
          secret:
            secretName: firebase-volume
        {{- end }}
        {{- if $app.mongodb }}
        - name: mongodb-volume
          secret:
            secretName: mongodb-volume
        {{- end }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $name }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ $app.port }}
{{- end }}