
apiVersion: v1
kind: ConfigMap
metadata:
  name: public-key-at
  namespace: backend
data:
  jwks: |
    {
      "keys": [
        {
          "alg": "RS256",
          "kty": "RSA",
          "use": "sig",
          "kid": "jwt-rt-key-v1",
          "n": "wYQ4ZgOXrNO9uwb1DEOr0rlEn68kZg9s-WbYY0N3_AxfiU4lp1xGx5fqZHasCqzuEe52-zhj_cEpqiCRgvxMFzy_8JZoyCREr6oA8qrmPV5ZLeanvdKbtDhsvYj5Rd62XqlJkQrVYlRf2U3yIlrYSzyE1AmrehQC3jWAWnZJLJPXs_MCy3uZ2RJSizXA7cD1vvGB5_XFuTD5aUaUODHGFVPq7qB0CeuSwNDy9tEXMe5C_6G88NBoju7MDB_N89Tq9SvuEKA2UnPfrT6MfZlBPQwzesxuIGlWjDVIpXAgv__19F6xTeWln0NTqyjscjFpn6AP8hBUe-xznDLtMQDYcw",
          "e": "AQAB"
        }
      ]
    }

---

{{- range $name, $app := .Values.apps }}
---
{{if $app.routePath}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $name }}-route
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $name }}
spec:
  parentRefs:
    - name: cluster-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "backend.mikekim1032.shop"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ $app.routePath }}
      backendRefs:
        - name: {{ $name }}
          port: 80
{{- end}}

---

{{- if not $app.authentication }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ $name }}-jwt-auth
  namespace: {{ $.Values.namespace }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ $name }}-route
  jwt:
    providers:
      - name: jwt-provider
{{/*        extractFrom:*/}}
{{/*          headers:*/}}
{{/*            - name: Authorization*/}}
{{/*              valuePrefix: "Bearer "*/}}
{{/*            - name: Sec-WebSocket-Protocol*/}}
        claimToHeaders:
          - claim: sub
            header: X-User-Id
        localJWKS:
          type: ValueRef
          valueRef:
            group: ""
            kind: ConfigMap
            name: public-key-at
{{- end }}

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ $name }}-circuit-breaker
  namespace: {{ $.Values.namespace }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ $name }}-route
  circuitBreaker:
    maxConnections: {{ $.Values.circuitBreaker.maxConnections }}
    maxPendingRequests: {{$.Values.circuitBreaker.maxPendingRequests}}
    maxParallelRequests: {{$.Values.circuitBreaker.maxParallelRequests}}
{{/*  rateLimit:*/}}
{{/*    type: Global*/}}
{{/*    global:*/}}
{{/*      rules:*/}}
{{/*        - clientSelectors:*/}}
{{/*            - headers:*/}}
{{/*                - type: Distinct*/}}
{{/*                  name: X-User-Id*/}}
{{/*          limit:*/}}
{{/*            requests: 10*/}}
{{/*            unit: Second*/}}
{{- end}}