{{- range $name, $app := .Values.apps }}
{{- if $app.leaderElection }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}-sa
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}-leader-election-role
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $name }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}-leader-election-binding
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $name }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}-sa
    namespace: {{ $.Values.namespace }}
roleRef:
  kind: Role
  name: {{ $name }}-leader-election-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}