// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"context"

	"github.com/apache/cassandra-gocql-driver/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddBlock provides a mock function for the type MockRepository
func (_mock *MockRepository) AddBlock(ctx context.Context, blockerId gocql.UUID, blockedId gocql.UUID) error {
	ret := _mock.Called(ctx, blockerId, blockedId)

	if len(ret) == 0 {
		panic("no return value specified for AddBlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID, gocql.UUID) error); ok {
		r0 = returnFunc(ctx, blockerId, blockedId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBlock'
type MockRepository_AddBlock_Call struct {
	*mock.Call
}

// AddBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - blockerId gocql.UUID
//   - blockedId gocql.UUID
func (_e *MockRepository_Expecter) AddBlock(ctx any, blockerId any, blockedId any) *MockRepository_AddBlock_Call {
	return &MockRepository_AddBlock_Call{Call: _e.mock.On("AddBlock", ctx, blockerId, blockedId)}
}

func (_c *MockRepository_AddBlock_Call) Run(run func(ctx context.Context, blockerId gocql.UUID, blockedId gocql.UUID)) *MockRepository_AddBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		var arg2 gocql.UUID
		if args[2] != nil {
			arg2 = args[2].(gocql.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_AddBlock_Call) Return(err error) *MockRepository_AddBlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddBlock_Call) RunAndReturn(run func(ctx context.Context, blockerId gocql.UUID, blockedId gocql.UUID) error) *MockRepository_AddBlock_Call {
	_c.Call.Return(run)
	return _c
}

// AddParticipantId provides a mock function for the type MockRepository
func (_mock *MockRepository) AddParticipantId(ctx context.Context, roomId gocql.UUID, participantId gocql.UUID) error {
	ret := _mock.Called(ctx, roomId, participantId)

	if len(ret) == 0 {
		panic("no return value specified for AddParticipantId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID, gocql.UUID) error); ok {
		r0 = returnFunc(ctx, roomId, participantId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddParticipantId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddParticipantId'
type MockRepository_AddParticipantId_Call struct {
	*mock.Call
}

// AddParticipantId is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId gocql.UUID
//   - participantId gocql.UUID
func (_e *MockRepository_Expecter) AddParticipantId(ctx any, roomId any, participantId any) *MockRepository_AddParticipantId_Call {
	return &MockRepository_AddParticipantId_Call{Call: _e.mock.On("AddParticipantId", ctx, roomId, participantId)}
}

func (_c *MockRepository_AddParticipantId_Call) Run(run func(ctx context.Context, roomId gocql.UUID, participantId gocql.UUID)) *MockRepository_AddParticipantId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		var arg2 gocql.UUID
		if args[2] != nil {
			arg2 = args[2].(gocql.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_AddParticipantId_Call) Return(err error) *MockRepository_AddParticipantId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddParticipantId_Call) RunAndReturn(run func(ctx context.Context, roomId gocql.UUID, participantId gocql.UUID) error) *MockRepository_AddParticipantId_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChatRoom provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateChatRoom(ctx context.Context, roomId gocql.UUID, memberId gocql.UUID, roomName string) error {
	ret := _mock.Called(ctx, roomId, memberId, roomName)

	if len(ret) == 0 {
		panic("no return value specified for CreateChatRoom")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID, gocql.UUID, string) error); ok {
		r0 = returnFunc(ctx, roomId, memberId, roomName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateChatRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChatRoom'
type MockRepository_CreateChatRoom_Call struct {
	*mock.Call
}

// CreateChatRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId gocql.UUID
//   - memberId gocql.UUID
//   - roomName string
func (_e *MockRepository_Expecter) CreateChatRoom(ctx any, roomId any, memberId any, roomName any) *MockRepository_CreateChatRoom_Call {
	return &MockRepository_CreateChatRoom_Call{Call: _e.mock.On("CreateChatRoom", ctx, roomId, memberId, roomName)}
}

func (_c *MockRepository_CreateChatRoom_Call) Run(run func(ctx context.Context, roomId gocql.UUID, memberId gocql.UUID, roomName string)) *MockRepository_CreateChatRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		var arg2 gocql.UUID
		if args[2] != nil {
			arg2 = args[2].(gocql.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_CreateChatRoom_Call) Return(err error) *MockRepository_CreateChatRoom_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateChatRoom_Call) RunAndReturn(run func(ctx context.Context, roomId gocql.UUID, memberId gocql.UUID, roomName string) error) *MockRepository_CreateChatRoom_Call {
	_c.Call.Return(run)
	return _c
}

// FindParticipantIds provides a mock function for the type MockRepository
func (_mock *MockRepository) FindParticipantIds(ctx context.Context, roomId gocql.UUID) ([]gocql.UUID, error) {
	ret := _mock.Called(ctx, roomId)

	if len(ret) == 0 {
		panic("no return value specified for FindParticipantIds")
	}

	var r0 []gocql.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID) ([]gocql.UUID, error)); ok {
		return returnFunc(ctx, roomId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID) []gocql.UUID); ok {
		r0 = returnFunc(ctx, roomId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gocql.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gocql.UUID) error); ok {
		r1 = returnFunc(ctx, roomId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindParticipantIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindParticipantIds'
type MockRepository_FindParticipantIds_Call struct {
	*mock.Call
}

// FindParticipantIds is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId gocql.UUID
func (_e *MockRepository_Expecter) FindParticipantIds(ctx any, roomId any) *MockRepository_FindParticipantIds_Call {
	return &MockRepository_FindParticipantIds_Call{Call: _e.mock.On("FindParticipantIds", ctx, roomId)}
}

func (_c *MockRepository_FindParticipantIds_Call) Run(run func(ctx context.Context, roomId gocql.UUID)) *MockRepository_FindParticipantIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindParticipantIds_Call) Return(uUIDs []gocql.UUID, err error) *MockRepository_FindParticipantIds_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockRepository_FindParticipantIds_Call) RunAndReturn(run func(ctx context.Context, roomId gocql.UUID) ([]gocql.UUID, error)) *MockRepository_FindParticipantIds_Call {
	_c.Call.Return(run)
	return _c
}

// IsBlocked provides a mock function for the type MockRepository
func (_mock *MockRepository) IsBlocked(ctx context.Context, blockerId gocql.UUID, blockedId gocql.UUID) (bool, error) {
	ret := _mock.Called(ctx, blockerId, blockedId)

	if len(ret) == 0 {
		panic("no return value specified for IsBlocked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID, gocql.UUID) (bool, error)); ok {
		return returnFunc(ctx, blockerId, blockedId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID, gocql.UUID) bool); ok {
		r0 = returnFunc(ctx, blockerId, blockedId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gocql.UUID, gocql.UUID) error); ok {
		r1 = returnFunc(ctx, blockerId, blockedId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_IsBlocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBlocked'
type MockRepository_IsBlocked_Call struct {
	*mock.Call
}

// IsBlocked is a helper method to define mock.On call
//   - ctx context.Context
//   - blockerId gocql.UUID
//   - blockedId gocql.UUID
func (_e *MockRepository_Expecter) IsBlocked(ctx any, blockerId any, blockedId any) *MockRepository_IsBlocked_Call {
	return &MockRepository_IsBlocked_Call{Call: _e.mock.On("IsBlocked", ctx, blockerId, blockedId)}
}

func (_c *MockRepository_IsBlocked_Call) Run(run func(ctx context.Context, blockerId gocql.UUID, blockedId gocql.UUID)) *MockRepository_IsBlocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		var arg2 gocql.UUID
		if args[2] != nil {
			arg2 = args[2].(gocql.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_IsBlocked_Call) Return(b bool, err error) *MockRepository_IsBlocked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_IsBlocked_Call) RunAndReturn(run func(ctx context.Context, blockerId gocql.UUID, blockedId gocql.UUID) (bool, error)) *MockRepository_IsBlocked_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveBlock provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveBlock(ctx context.Context, blockerId gocql.UUID, blockedId gocql.UUID) error {
	ret := _mock.Called(ctx, blockerId, blockedId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveBlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID, gocql.UUID) error); ok {
		r0 = returnFunc(ctx, blockerId, blockedId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RemoveBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveBlock'
type MockRepository_RemoveBlock_Call struct {
	*mock.Call
}

// RemoveBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - blockerId gocql.UUID
//   - blockedId gocql.UUID
func (_e *MockRepository_Expecter) RemoveBlock(ctx any, blockerId any, blockedId any) *MockRepository_RemoveBlock_Call {
	return &MockRepository_RemoveBlock_Call{Call: _e.mock.On("RemoveBlock", ctx, blockerId, blockedId)}
}

func (_c *MockRepository_RemoveBlock_Call) Run(run func(ctx context.Context, blockerId gocql.UUID, blockedId gocql.UUID)) *MockRepository_RemoveBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		var arg2 gocql.UUID
		if args[2] != nil {
			arg2 = args[2].(gocql.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_RemoveBlock_Call) Return(err error) *MockRepository_RemoveBlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RemoveBlock_Call) RunAndReturn(run func(ctx context.Context, blockerId gocql.UUID, blockedId gocql.UUID) error) *MockRepository_RemoveBlock_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveParticipantId provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveParticipantId(ctx context.Context, roomId gocql.UUID, participantId gocql.UUID) error {
	ret := _mock.Called(ctx, roomId, participantId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveParticipantId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID, gocql.UUID) error); ok {
		r0 = returnFunc(ctx, roomId, participantId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RemoveParticipantId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveParticipantId'
type MockRepository_RemoveParticipantId_Call struct {
	*mock.Call
}

// RemoveParticipantId is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId gocql.UUID
//   - participantId gocql.UUID
func (_e *MockRepository_Expecter) RemoveParticipantId(ctx any, roomId any, participantId any) *MockRepository_RemoveParticipantId_Call {
	return &MockRepository_RemoveParticipantId_Call{Call: _e.mock.On("RemoveParticipantId", ctx, roomId, participantId)}
}

func (_c *MockRepository_RemoveParticipantId_Call) Run(run func(ctx context.Context, roomId gocql.UUID, participantId gocql.UUID)) *MockRepository_RemoveParticipantId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		var arg2 gocql.UUID
		if args[2] != nil {
			arg2 = args[2].(gocql.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_RemoveParticipantId_Call) Return(err error) *MockRepository_RemoveParticipantId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RemoveParticipantId_Call) RunAndReturn(run func(ctx context.Context, roomId gocql.UUID, participantId gocql.UUID) error) *MockRepository_RemoveParticipantId_Call {
	_c.Call.Return(run)
	return _c
}

// SaveIdsByFileName provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveIdsByFileName(ctx context.Context, ids []gocql.UUID, filename gocql.UUID) error {
	ret := _mock.Called(ctx, ids, filename)

	if len(ret) == 0 {
		panic("no return value specified for SaveIdsByFileName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []gocql.UUID, gocql.UUID) error); ok {
		r0 = returnFunc(ctx, ids, filename)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveIdsByFileName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveIdsByFileName'
type MockRepository_SaveIdsByFileName_Call struct {
	*mock.Call
}

// SaveIdsByFileName is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []gocql.UUID
//   - filename gocql.UUID
func (_e *MockRepository_Expecter) SaveIdsByFileName(ctx any, ids any, filename any) *MockRepository_SaveIdsByFileName_Call {
	return &MockRepository_SaveIdsByFileName_Call{Call: _e.mock.On("SaveIdsByFileName", ctx, ids, filename)}
}

func (_c *MockRepository_SaveIdsByFileName_Call) Run(run func(ctx context.Context, ids []gocql.UUID, filename gocql.UUID)) *MockRepository_SaveIdsByFileName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []gocql.UUID
		if args[1] != nil {
			arg1 = args[1].([]gocql.UUID)
		}
		var arg2 gocql.UUID
		if args[2] != nil {
			arg2 = args[2].(gocql.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SaveIdsByFileName_Call) Return(err error) *MockRepository_SaveIdsByFileName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveIdsByFileName_Call) RunAndReturn(run func(ctx context.Context, ids []gocql.UUID, filename gocql.UUID) error) *MockRepository_SaveIdsByFileName_Call {
	_c.Call.Return(run)
	return _c
}
