// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"backend/common/proto"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRelayClient creates a new instance of MockRelayClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRelayClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRelayClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRelayClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRelayClient is an autogenerated mock type for the RelayClient type
type MockRelayClient struct {
	mock.Mock
}

type MockRelayClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRelayClient) EXPECT() *MockRelayClient_Expecter {
	return &MockRelayClient_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockRelayClient
func (_mock *MockRelayClient) Do(ctx context.Context, ip string, req *proto.RelayMessagingRequest) ([][]byte, error) {
	ret := _mock.Called(ctx, ip, req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 [][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *proto.RelayMessagingRequest) ([][]byte, error)); ok {
		return returnFunc(ctx, ip, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *proto.RelayMessagingRequest) [][]byte); ok {
		r0 = returnFunc(ctx, ip, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *proto.RelayMessagingRequest) error); ok {
		r1 = returnFunc(ctx, ip, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRelayClient_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockRelayClient_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - ip string
//   - req *proto.RelayMessagingRequest
func (_e *MockRelayClient_Expecter) Do(ctx any, ip any, req any) *MockRelayClient_Do_Call {
	return &MockRelayClient_Do_Call{Call: _e.mock.On("Do", ctx, ip, req)}
}

func (_c *MockRelayClient_Do_Call) Run(run func(ctx context.Context, ip string, req *proto.RelayMessagingRequest)) *MockRelayClient_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *proto.RelayMessagingRequest
		if args[2] != nil {
			arg2 = args[2].(*proto.RelayMessagingRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRelayClient_Do_Call) Return(pushToIds [][]byte, err error) *MockRelayClient_Do_Call {
	_c.Call.Return(pushToIds, err)
	return _c
}

func (_c *MockRelayClient_Do_Call) RunAndReturn(run func(ctx context.Context, ip string, req *proto.RelayMessagingRequest) ([][]byte, error)) *MockRelayClient_Do_Call {
	_c.Call.Return(run)
	return _c
}
