namespace: backend
email: ""

circuitBreaker:
  maxConnections: 100
  consecutiveErrors: 5
  baseEjectionTime: 30s
  maxPendingRequests: 100 # Limits requests waiting in the queue
  maxParallelRequests: 100 # Limits active, concurrent HTTP requests

apps:
  auth:
    image: "565319458549.dkr.ecr.ap-northeast-2.amazonaws.com/backend/auth:latest"
    port: 8080
    routePath: /auth
    authentication: true
    aws: false
    kafka: false
    astradb: true
    mongodb: false
    tidb: false
    smtp: true
    twilio: true
    firebase: false
    valkey: false
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  chat:
    image: "565319458549.dkr.ecr.ap-northeast-2.amazonaws.com/backend/chat:latest"
    port: 8080
    routePath: /chat
    authentication: false
    aws: true
    kafka: true
    astradb: true
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: true
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  expo-notification:
    image: "565319458549.dkr.ecr.ap-northeast-2.amazonaws.com/backend/expo-notification:latest"
    port: 8080
    routePath: false
    authentication: false
    aws: false
    kafka: true
    astradb: true
    mongodb: false
    tidb: false
    firebase: false
    valkey: true
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  fcmnotification:
    image: "565319458549.dkr.ecr.ap-northeast-2.amazonaws.com/backend/fcmnotification:latest"
    port: 8080
    routePath: false
    authentication: false
    aws: false
    kafka: true
    astradb: true
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: true
    valkey: true
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  messagepersist:
    image: "565319458549.dkr.ecr.ap-northeast-2.amazonaws.com/backend/messagepersist:latest"
    port: 8080
    routePath: false
    authentication: false
    aws: false
    kafka: true
    astradb: true
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: false
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  messagepreprocess:
    image: "565319458549.dkr.ecr.ap-northeast-2.amazonaws.com/backend/messagepreprocess:latest"
    port: 8080
    routePath: false
    authentication: false
    aws: false
    kafka: true
    astradb: true
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: true
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  messagerelay:
    image: "565319458549.dkr.ecr.ap-northeast-2.amazonaws.com/backend/messagerelay:latest"
    port: 8080
    routePath: false
    authentication: false
    aws: false
    kafka: true
    astradb: true
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: true
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  notification:
    image: "565319458549.dkr.ecr.ap-northeast-2.amazonaws.com/backend/notification:latest"
    port: 8080
    routePath: /notification
    authentication: false
    aws: true
    kafka: true
    astradb: true
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: false
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  onlineconversation:
    image: "565319458549.dkr.ecr.ap-northeast-2.amazonaws.com/backend/onlineconversation:latest"
    port: 8080
    routePath: /onlineconversation
    authentication: false
    aws: false
    kafka: true
    astradb: false
    mongodb: true
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: true
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  signalrelay:
    image: "565319458549.dkr.ecr.ap-northeast-2.amazonaws.com/backend/signalrelay:latest"
    port: 8080
    routePath: false
    authentication: false
    aws: false
    kafka: true
    astradb: false
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: true
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  offlineconversation:
    image: "565319458549.dkr.ecr.ap-northeast-2.amazonaws.com/backend/offlineconversation:latest"
    port: 8080
    routePath: /offlineconversation
    authentication: false
    aws: false
    kafka: true
    astradb: false
    mongodb: false
    tidb: true
    smtp: false
    twilio: false
    firebase: false
    valkey: true
    framework: spring-boot
#    cpuRequests: "0.3"
#    memoryRequests: "100Mi"
#    cpuLimits: "0.4"
#    memoryLimits: "100Mi"
