namespace: backend
email: ""
registry: "ghcr.io/seaoferror"

circuitBreaker:
  maxConnections: 100
  consecutiveErrors: 5
  baseEjectionTime: 30s
  maxPendingRequests: 100 # Limits requests waiting in the queue
  maxParallelRequests: 100 # Limits active, concurrent HTTP requests

apps:
  auth:
    image: "backend/auth:latest"
    port: 8080
    routePath: /auth
    authentication: true
    aws: false
    confluent: false
    kafka: false
    k8ssandra: true
    mongodb: false
    tidb: false
    smtp: true
    twilio: true
    firebase: false
    valkey: false
    opensearch: false
    leaderElection: false
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  chat:
    image: "backend/chat:latest"
    port: 8080
    routePath: /chat
    authentication: false
    aws: true
    kafka: true
    k8ssandra: true
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: true
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  expo-notification:
    image: "backend/expo-notification:latest"
    port: 8080
    routePath: false
    authentication: false
    aws: false
    kafka: true
    k8ssandra: true
    mongodb: false
    tidb: false
    firebase: false
    valkey: true
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  fcmnotification:
    image: "backend/fcmnotification:latest"
    port: 8080
    routePath: false
    authentication: false
    aws: false
    kafka: true
    k8ssandra: true
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: true
    valkey: true
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  messagepersist:
    image: "backend/messagepersist:latest"
    port: 8080
    routePath: false
    authentication: false
    aws: false
    kafka: true
    k8ssandra: true
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: false
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  messagepreprocess:
    image: "backend/messagepreprocess:latest"
    port: 8080
    routePath: false
    authentication: false
    aws: false
    kafka: true
    k8ssandra: true
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: true
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  messagerelay:
    image: "backend/messagerelay:latest"
    port: 8080
    routePath: false
    authentication: false
    aws: false
    kafka: true
    k8ssandra: true
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: true
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  notification:
    image: "backend/notification:latest"
    port: 8080
    routePath: /notification
    authentication: false
    aws: true
    kafka: true
    k8ssandra: true
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: false
    leaderElection: true
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  onlineconversation:
    image: "backend/onlineconversation:latest"
    port: 8080
    routePath: /onlineconversation
    authentication: false
    aws: false
    kafka: true
    k8ssandra: false
    mongodb: true
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: true
    opensearch: true
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  signalrelay:
    image: "backend/signalrelay:latest"
    port: 8080
    routePath: false
    authentication: false
    aws: false
    kafka: true
    k8ssandra: false
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: true
#    cpuRequests: "0.03"
#    memoryRequests: "10Mi"
#    cpuLimits: "0.1"
#    memoryLimits: "10Mi"
  offlineconversation:
    image: "backend/offlineconversation:latest"
    port: 8080
    routePath: /offlineconversation
    authentication: false
    aws: false
    kafka: true
    k8ssandra: false
    mongodb: false
    tidb: true
    smtp: false
    twilio: false
    firebase: false
    valkey: true
    opensearch: false
    framework: spring-boot
#    cpuRequests: "0.3"
#    memoryRequests: "100Mi"
#    cpuLimits: "0.4"
#    memoryLimits: "100Mi"
  search:
    image: "backend/search:latest"
    port: 8080
    routePath: /search
    authentication: false
    aws: false
    kafka: true
    k8ssandra: false
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: false
    opensearch: true
    framework: spring-boot
  #    cpuRequests: "0.3"
  #    memoryRequests: "100Mi"
  #    cpuLimits: "0.4"
  #    memoryLimits: "100Mi"
  turn:
    image: "backend/turn:latest"
    port: 3478
    routePath: false
    turn: true
    authentication: false
    aws: false
    kafka: false
    k8ssandra: false
    mongodb: false
    tidb: false
    smtp: false
    twilio: false
    firebase: false
    valkey: false
    opensearch: false
