namespace: default
domain: server.mikekim1032.shop
email: ""

gateway:
  issuer: my-issuer
  tlsSecret: server-mikekim1032-com-tls

auth:
  issuer: "https://your-issuer.com"
  base64UrlSecret: ""

circuitBreaker:
  maxConnections: 100
  consecutiveErrors: 5
  baseEjectionTime: 30s
  maxPendingRequests: 100 # Limits requests waiting in the queue
  maxParallelRequests: 100 # Limits active, concurrent HTTP requests

apps:
  auth:
    image: "backend/auth:latest"
    port: 8080
    routePath: /auth
    authentication: true
    aws: false
    kafka: false
    astradb: true
    mongodb: false
    smtp: true
    twilio: true
    firebase: false
  chat:
    image: "backend/chat:latest"
    port: 8080
    routePath: /chat
    authentication: false
    kafka: true
    astradb: true
    mongodb: false
    smtp: false
    twilio: false
    firebase: false
  expo-notification:
    image: "backend/expo-notification:latest"
    port: 8080
    routePath: false
    authentication: false
    astradb: true
    mongodb: false
    firebase: false
  fcmnotification:
    image: "backend/fcmnotification:latest"
    port: 8080
    routePath: false
    authentication: false
    astradb: true
    mongodb: false
    firebase: true
  messagepersist:
    image: "backend/messagepersist:latest"
    port: 8080
    routePath: false
    authentication: false
    astradb: true
    mongodb: false
    firebase: false
  messagepreprocess:
    image: "backend/messagepreprocess:latest"
    port: 8080
    routePath: false
    authentication: false
    astradb: true
    mongodb: false
    firebase: false
  messagerelay:
    image: "backend/messagerelay:latest"
    port: 8080
    routePath: true
    authentication: false
    astradb: true
    mongodb: false
    firebase: false
  notification:
    image: "backend/notification:latest"
    port: 8080
    routePath: true
    authentication: false
    astradb: true
    mongodb: false
    firebase: false
  onlineconversation:
    image: "backend/onlineconversation:latest"
    port: 8080
    routePath: true
    authentication: false
    astradb: false
    mongodb: true
    firebase: false
  signalrelay:
    image: "backend/signalrelay:latest"
    port: 8080
    routePath: false
    authentication: false
    astradb: false
    mongodb: false
    firebase: false



