// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"backend/onlineconversation/internal/dto"
	"backend/onlineconversation/internal/projection"
	"backend/onlineconversation/internal/repository"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddBanIdIfModerator provides a mock function for the type MockRepository
func (_mock *MockRepository) AddBanIdIfModerator(ctx context.Context, session repository.Session, conversationId uuid.UUID, modId uuid.UUID, banId uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, session, conversationId, modId, banId)

	if len(ret) == 0 {
		panic("no return value specified for AddBanIdIfModerator")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, session, conversationId, modId, banId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, session, conversationId, modId, banId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.Session, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, session, conversationId, modId, banId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_AddBanIdIfModerator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBanIdIfModerator'
type MockRepository_AddBanIdIfModerator_Call struct {
	*mock.Call
}

// AddBanIdIfModerator is a helper method to define mock.On call
//   - ctx context.Context
//   - session repository.Session
//   - conversationId uuid.UUID
//   - modId uuid.UUID
//   - banId uuid.UUID
func (_e *MockRepository_Expecter) AddBanIdIfModerator(ctx any, session any, conversationId any, modId any, banId any) *MockRepository_AddBanIdIfModerator_Call {
	return &MockRepository_AddBanIdIfModerator_Call{Call: _e.mock.On("AddBanIdIfModerator", ctx, session, conversationId, modId, banId)}
}

func (_c *MockRepository_AddBanIdIfModerator_Call) Run(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, modId uuid.UUID, banId uuid.UUID)) *MockRepository_AddBanIdIfModerator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Session
		if args[1] != nil {
			arg1 = args[1].(repository.Session)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_AddBanIdIfModerator_Call) Return(b bool, err error) *MockRepository_AddBanIdIfModerator_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_AddBanIdIfModerator_Call) RunAndReturn(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, modId uuid.UUID, banId uuid.UUID) (bool, error)) *MockRepository_AddBanIdIfModerator_Call {
	_c.Call.Return(run)
	return _c
}

// AddNotificationId provides a mock function for the type MockRepository
func (_mock *MockRepository) AddNotificationId(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID) error {
	ret := _mock.Called(ctx, session, conversationId, memberId)

	if len(ret) == 0 {
		panic("no return value specified for AddNotificationId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, session, conversationId, memberId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddNotificationId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNotificationId'
type MockRepository_AddNotificationId_Call struct {
	*mock.Call
}

// AddNotificationId is a helper method to define mock.On call
//   - ctx context.Context
//   - session repository.Session
//   - conversationId uuid.UUID
//   - memberId uuid.UUID
func (_e *MockRepository_Expecter) AddNotificationId(ctx any, session any, conversationId any, memberId any) *MockRepository_AddNotificationId_Call {
	return &MockRepository_AddNotificationId_Call{Call: _e.mock.On("AddNotificationId", ctx, session, conversationId, memberId)}
}

func (_c *MockRepository_AddNotificationId_Call) Run(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID)) *MockRepository_AddNotificationId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Session
		if args[1] != nil {
			arg1 = args[1].(repository.Session)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_AddNotificationId_Call) Return(err error) *MockRepository_AddNotificationId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddNotificationId_Call) RunAndReturn(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID) error) *MockRepository_AddNotificationId_Call {
	_c.Call.Return(run)
	return _c
}

// AddParticipantId provides a mock function for the type MockRepository
func (_mock *MockRepository) AddParticipantId(ctx context.Context, conversationId string, memberId uuid.UUID) error {
	ret := _mock.Called(ctx, conversationId, memberId)

	if len(ret) == 0 {
		panic("no return value specified for AddParticipantId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, conversationId, memberId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddParticipantId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddParticipantId'
type MockRepository_AddParticipantId_Call struct {
	*mock.Call
}

// AddParticipantId is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationId string
//   - memberId uuid.UUID
func (_e *MockRepository_Expecter) AddParticipantId(ctx any, conversationId any, memberId any) *MockRepository_AddParticipantId_Call {
	return &MockRepository_AddParticipantId_Call{Call: _e.mock.On("AddParticipantId", ctx, conversationId, memberId)}
}

func (_c *MockRepository_AddParticipantId_Call) Run(run func(ctx context.Context, conversationId string, memberId uuid.UUID)) *MockRepository_AddParticipantId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_AddParticipantId_Call) Return(err error) *MockRepository_AddParticipantId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddParticipantId_Call) RunAndReturn(run func(ctx context.Context, conversationId string, memberId uuid.UUID) error) *MockRepository_AddParticipantId_Call {
	_c.Call.Return(run)
	return _c
}

// BeginTx provides a mock function for the type MockRepository
func (_mock *MockRepository) BeginTx(ctx context.Context) (repository.Tx, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 repository.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (repository.Tx, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) repository.Tx); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockRepository_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) BeginTx(ctx any) *MockRepository_BeginTx_Call {
	return &MockRepository_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx)}
}

func (_c *MockRepository_BeginTx_Call) Run(run func(ctx context.Context)) *MockRepository_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_BeginTx_Call) Return(tx repository.Tx, err error) *MockRepository_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockRepository_BeginTx_Call) RunAndReturn(run func(ctx context.Context) (repository.Tx, error)) *MockRepository_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementRegistrants provides a mock function for the type MockRepository
func (_mock *MockRepository) DecrementRegistrants(ctx context.Context, session repository.Session, conversationId uuid.UUID) error {
	ret := _mock.Called(ctx, session, conversationId)

	if len(ret) == 0 {
		panic("no return value specified for DecrementRegistrants")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, session, conversationId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DecrementRegistrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementRegistrants'
type MockRepository_DecrementRegistrants_Call struct {
	*mock.Call
}

// DecrementRegistrants is a helper method to define mock.On call
//   - ctx context.Context
//   - session repository.Session
//   - conversationId uuid.UUID
func (_e *MockRepository_Expecter) DecrementRegistrants(ctx any, session any, conversationId any) *MockRepository_DecrementRegistrants_Call {
	return &MockRepository_DecrementRegistrants_Call{Call: _e.mock.On("DecrementRegistrants", ctx, session, conversationId)}
}

func (_c *MockRepository_DecrementRegistrants_Call) Run(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID)) *MockRepository_DecrementRegistrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Session
		if args[1] != nil {
			arg1 = args[1].(repository.Session)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_DecrementRegistrants_Call) Return(err error) *MockRepository_DecrementRegistrants_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DecrementRegistrants_Call) RunAndReturn(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID) error) *MockRepository_DecrementRegistrants_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOnlineConversationIfModerator provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteOnlineConversationIfModerator(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, session, conversationId, memberId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOnlineConversationIfModerator")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, session, conversationId, memberId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, session, conversationId, memberId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.Session, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, session, conversationId, memberId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_DeleteOnlineConversationIfModerator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOnlineConversationIfModerator'
type MockRepository_DeleteOnlineConversationIfModerator_Call struct {
	*mock.Call
}

// DeleteOnlineConversationIfModerator is a helper method to define mock.On call
//   - ctx context.Context
//   - session repository.Session
//   - conversationId uuid.UUID
//   - memberId uuid.UUID
func (_e *MockRepository_Expecter) DeleteOnlineConversationIfModerator(ctx any, session any, conversationId any, memberId any) *MockRepository_DeleteOnlineConversationIfModerator_Call {
	return &MockRepository_DeleteOnlineConversationIfModerator_Call{Call: _e.mock.On("DeleteOnlineConversationIfModerator", ctx, session, conversationId, memberId)}
}

func (_c *MockRepository_DeleteOnlineConversationIfModerator_Call) Run(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID)) *MockRepository_DeleteOnlineConversationIfModerator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Session
		if args[1] != nil {
			arg1 = args[1].(repository.Session)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteOnlineConversationIfModerator_Call) Return(b bool, err error) *MockRepository_DeleteOnlineConversationIfModerator_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_DeleteOnlineConversationIfModerator_Call) RunAndReturn(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID) (bool, error)) *MockRepository_DeleteOnlineConversationIfModerator_Call {
	_c.Call.Return(run)
	return _c
}

// FindConversationDetail provides a mock function for the type MockRepository
func (_mock *MockRepository) FindConversationDetail(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID) (projection.Detail, error) {
	ret := _mock.Called(ctx, session, conversationId, memberId)

	if len(ret) == 0 {
		panic("no return value specified for FindConversationDetail")
	}

	var r0 projection.Detail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID, uuid.UUID) (projection.Detail, error)); ok {
		return returnFunc(ctx, session, conversationId, memberId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID, uuid.UUID) projection.Detail); ok {
		r0 = returnFunc(ctx, session, conversationId, memberId)
	} else {
		r0 = ret.Get(0).(projection.Detail)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.Session, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, session, conversationId, memberId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindConversationDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindConversationDetail'
type MockRepository_FindConversationDetail_Call struct {
	*mock.Call
}

// FindConversationDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - session repository.Session
//   - conversationId uuid.UUID
//   - memberId uuid.UUID
func (_e *MockRepository_Expecter) FindConversationDetail(ctx any, session any, conversationId any, memberId any) *MockRepository_FindConversationDetail_Call {
	return &MockRepository_FindConversationDetail_Call{Call: _e.mock.On("FindConversationDetail", ctx, session, conversationId, memberId)}
}

func (_c *MockRepository_FindConversationDetail_Call) Run(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID)) *MockRepository_FindConversationDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Session
		if args[1] != nil {
			arg1 = args[1].(repository.Session)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_FindConversationDetail_Call) Return(d projection.Detail, err error) *MockRepository_FindConversationDetail_Call {
	_c.Call.Return(d, err)
	return _c
}

func (_c *MockRepository_FindConversationDetail_Call) RunAndReturn(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID) (projection.Detail, error)) *MockRepository_FindConversationDetail_Call {
	_c.Call.Return(run)
	return _c
}

// FindParticipantIds provides a mock function for the type MockRepository
func (_mock *MockRepository) FindParticipantIds(ctx context.Context, conversationId string) ([]string, error) {
	ret := _mock.Called(ctx, conversationId)

	if len(ret) == 0 {
		panic("no return value specified for FindParticipantIds")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, conversationId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, conversationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, conversationId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindParticipantIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindParticipantIds'
type MockRepository_FindParticipantIds_Call struct {
	*mock.Call
}

// FindParticipantIds is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationId string
func (_e *MockRepository_Expecter) FindParticipantIds(ctx any, conversationId any) *MockRepository_FindParticipantIds_Call {
	return &MockRepository_FindParticipantIds_Call{Call: _e.mock.On("FindParticipantIds", ctx, conversationId)}
}

func (_c *MockRepository_FindParticipantIds_Call) Run(run func(ctx context.Context, conversationId string)) *MockRepository_FindParticipantIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindParticipantIds_Call) Return(strings []string, err error) *MockRepository_FindParticipantIds_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockRepository_FindParticipantIds_Call) RunAndReturn(run func(ctx context.Context, conversationId string) ([]string, error)) *MockRepository_FindParticipantIds_Call {
	_c.Call.Return(run)
	return _c
}

// InsertConversation provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertConversation(ctx context.Context, session repository.Session, conversationId uuid.UUID, req dto.CreateConversationRequest) error {
	ret := _mock.Called(ctx, session, conversationId, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertConversation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID, dto.CreateConversationRequest) error); ok {
		r0 = returnFunc(ctx, session, conversationId, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InsertConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertConversation'
type MockRepository_InsertConversation_Call struct {
	*mock.Call
}

// InsertConversation is a helper method to define mock.On call
//   - ctx context.Context
//   - session repository.Session
//   - conversationId uuid.UUID
//   - req dto.CreateConversationRequest
func (_e *MockRepository_Expecter) InsertConversation(ctx any, session any, conversationId any, req any) *MockRepository_InsertConversation_Call {
	return &MockRepository_InsertConversation_Call{Call: _e.mock.On("InsertConversation", ctx, session, conversationId, req)}
}

func (_c *MockRepository_InsertConversation_Call) Run(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, req dto.CreateConversationRequest)) *MockRepository_InsertConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Session
		if args[1] != nil {
			arg1 = args[1].(repository.Session)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.CreateConversationRequest
		if args[3] != nil {
			arg3 = args[3].(dto.CreateConversationRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_InsertConversation_Call) Return(err error) *MockRepository_InsertConversation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InsertConversation_Call) RunAndReturn(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, req dto.CreateConversationRequest) error) *MockRepository_InsertConversation_Call {
	_c.Call.Return(run)
	return _c
}

// InsertModerator provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertModerator(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID) error {
	ret := _mock.Called(ctx, session, conversationId, memberId)

	if len(ret) == 0 {
		panic("no return value specified for InsertModerator")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, session, conversationId, memberId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InsertModerator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertModerator'
type MockRepository_InsertModerator_Call struct {
	*mock.Call
}

// InsertModerator is a helper method to define mock.On call
//   - ctx context.Context
//   - session repository.Session
//   - conversationId uuid.UUID
//   - memberId uuid.UUID
func (_e *MockRepository_Expecter) InsertModerator(ctx any, session any, conversationId any, memberId any) *MockRepository_InsertModerator_Call {
	return &MockRepository_InsertModerator_Call{Call: _e.mock.On("InsertModerator", ctx, session, conversationId, memberId)}
}

func (_c *MockRepository_InsertModerator_Call) Run(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID)) *MockRepository_InsertModerator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Session
		if args[1] != nil {
			arg1 = args[1].(repository.Session)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_InsertModerator_Call) Return(err error) *MockRepository_InsertModerator_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InsertModerator_Call) RunAndReturn(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID) error) *MockRepository_InsertModerator_Call {
	_c.Call.Return(run)
	return _c
}

// InsertRegistrant provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertRegistrant(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID) error {
	ret := _mock.Called(ctx, session, conversationId, memberId)

	if len(ret) == 0 {
		panic("no return value specified for InsertRegistrant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, session, conversationId, memberId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InsertRegistrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertRegistrant'
type MockRepository_InsertRegistrant_Call struct {
	*mock.Call
}

// InsertRegistrant is a helper method to define mock.On call
//   - ctx context.Context
//   - session repository.Session
//   - conversationId uuid.UUID
//   - memberId uuid.UUID
func (_e *MockRepository_Expecter) InsertRegistrant(ctx any, session any, conversationId any, memberId any) *MockRepository_InsertRegistrant_Call {
	return &MockRepository_InsertRegistrant_Call{Call: _e.mock.On("InsertRegistrant", ctx, session, conversationId, memberId)}
}

func (_c *MockRepository_InsertRegistrant_Call) Run(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID)) *MockRepository_InsertRegistrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Session
		if args[1] != nil {
			arg1 = args[1].(repository.Session)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_InsertRegistrant_Call) Return(err error) *MockRepository_InsertRegistrant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InsertRegistrant_Call) RunAndReturn(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID) error) *MockRepository_InsertRegistrant_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveNotificationId provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveNotificationId(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID) error {
	ret := _mock.Called(ctx, session, conversationId, memberId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveNotificationId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, session, conversationId, memberId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RemoveNotificationId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveNotificationId'
type MockRepository_RemoveNotificationId_Call struct {
	*mock.Call
}

// RemoveNotificationId is a helper method to define mock.On call
//   - ctx context.Context
//   - session repository.Session
//   - conversationId uuid.UUID
//   - memberId uuid.UUID
func (_e *MockRepository_Expecter) RemoveNotificationId(ctx any, session any, conversationId any, memberId any) *MockRepository_RemoveNotificationId_Call {
	return &MockRepository_RemoveNotificationId_Call{Call: _e.mock.On("RemoveNotificationId", ctx, session, conversationId, memberId)}
}

func (_c *MockRepository_RemoveNotificationId_Call) Run(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID)) *MockRepository_RemoveNotificationId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Session
		if args[1] != nil {
			arg1 = args[1].(repository.Session)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_RemoveNotificationId_Call) Return(err error) *MockRepository_RemoveNotificationId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RemoveNotificationId_Call) RunAndReturn(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID) error) *MockRepository_RemoveNotificationId_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveParticipantId provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveParticipantId(ctx context.Context, conversationId string, memberId uuid.UUID) error {
	ret := _mock.Called(ctx, conversationId, memberId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveParticipantId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, conversationId, memberId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RemoveParticipantId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveParticipantId'
type MockRepository_RemoveParticipantId_Call struct {
	*mock.Call
}

// RemoveParticipantId is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationId string
//   - memberId uuid.UUID
func (_e *MockRepository_Expecter) RemoveParticipantId(ctx any, conversationId any, memberId any) *MockRepository_RemoveParticipantId_Call {
	return &MockRepository_RemoveParticipantId_Call{Call: _e.mock.On("RemoveParticipantId", ctx, conversationId, memberId)}
}

func (_c *MockRepository_RemoveParticipantId_Call) Run(run func(ctx context.Context, conversationId string, memberId uuid.UUID)) *MockRepository_RemoveParticipantId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_RemoveParticipantId_Call) Return(err error) *MockRepository_RemoveParticipantId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RemoveParticipantId_Call) RunAndReturn(run func(ctx context.Context, conversationId string, memberId uuid.UUID) error) *MockRepository_RemoveParticipantId_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveRegistrantId provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveRegistrantId(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID) error {
	ret := _mock.Called(ctx, session, conversationId, memberId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveRegistrantId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, session, conversationId, memberId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RemoveRegistrantId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRegistrantId'
type MockRepository_RemoveRegistrantId_Call struct {
	*mock.Call
}

// RemoveRegistrantId is a helper method to define mock.On call
//   - ctx context.Context
//   - session repository.Session
//   - conversationId uuid.UUID
//   - memberId uuid.UUID
func (_e *MockRepository_Expecter) RemoveRegistrantId(ctx any, session any, conversationId any, memberId any) *MockRepository_RemoveRegistrantId_Call {
	return &MockRepository_RemoveRegistrantId_Call{Call: _e.mock.On("RemoveRegistrantId", ctx, session, conversationId, memberId)}
}

func (_c *MockRepository_RemoveRegistrantId_Call) Run(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID)) *MockRepository_RemoveRegistrantId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Session
		if args[1] != nil {
			arg1 = args[1].(repository.Session)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_RemoveRegistrantId_Call) Return(err error) *MockRepository_RemoveRegistrantId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RemoveRegistrantId_Call) RunAndReturn(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID, memberId uuid.UUID) error) *MockRepository_RemoveRegistrantId_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveServerIP provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveServerIP(ctx context.Context, memberId string) error {
	ret := _mock.Called(ctx, memberId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveServerIP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, memberId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RemoveServerIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveServerIP'
type MockRepository_RemoveServerIP_Call struct {
	*mock.Call
}

// RemoveServerIP is a helper method to define mock.On call
//   - ctx context.Context
//   - memberId string
func (_e *MockRepository_Expecter) RemoveServerIP(ctx any, memberId any) *MockRepository_RemoveServerIP_Call {
	return &MockRepository_RemoveServerIP_Call{Call: _e.mock.On("RemoveServerIP", ctx, memberId)}
}

func (_c *MockRepository_RemoveServerIP_Call) Run(run func(ctx context.Context, memberId string)) *MockRepository_RemoveServerIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_RemoveServerIP_Call) Return(err error) *MockRepository_RemoveServerIP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RemoveServerIP_Call) RunAndReturn(run func(ctx context.Context, memberId string) error) *MockRepository_RemoveServerIP_Call {
	_c.Call.Return(run)
	return _c
}

// SetServerIP provides a mock function for the type MockRepository
func (_mock *MockRepository) SetServerIP(ctx context.Context, memberId string, ip string) error {
	ret := _mock.Called(ctx, memberId, ip)

	if len(ret) == 0 {
		panic("no return value specified for SetServerIP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, memberId, ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetServerIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetServerIP'
type MockRepository_SetServerIP_Call struct {
	*mock.Call
}

// SetServerIP is a helper method to define mock.On call
//   - ctx context.Context
//   - memberId string
//   - ip string
func (_e *MockRepository_Expecter) SetServerIP(ctx any, memberId any, ip any) *MockRepository_SetServerIP_Call {
	return &MockRepository_SetServerIP_Call{Call: _e.mock.On("SetServerIP", ctx, memberId, ip)}
}

func (_c *MockRepository_SetServerIP_Call) Run(run func(ctx context.Context, memberId string, ip string)) *MockRepository_SetServerIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SetServerIP_Call) Return(err error) *MockRepository_SetServerIP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetServerIP_Call) RunAndReturn(run func(ctx context.Context, memberId string, ip string) error) *MockRepository_SetServerIP_Call {
	_c.Call.Return(run)
	return _c
}

// TryIncrementRegistrants provides a mock function for the type MockRepository
func (_mock *MockRepository) TryIncrementRegistrants(ctx context.Context, session repository.Session, conversationId uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, session, conversationId)

	if len(ret) == 0 {
		panic("no return value specified for TryIncrementRegistrants")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, session, conversationId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, session, conversationId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.Session, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, session, conversationId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_TryIncrementRegistrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryIncrementRegistrants'
type MockRepository_TryIncrementRegistrants_Call struct {
	*mock.Call
}

// TryIncrementRegistrants is a helper method to define mock.On call
//   - ctx context.Context
//   - session repository.Session
//   - conversationId uuid.UUID
func (_e *MockRepository_Expecter) TryIncrementRegistrants(ctx any, session any, conversationId any) *MockRepository_TryIncrementRegistrants_Call {
	return &MockRepository_TryIncrementRegistrants_Call{Call: _e.mock.On("TryIncrementRegistrants", ctx, session, conversationId)}
}

func (_c *MockRepository_TryIncrementRegistrants_Call) Run(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID)) *MockRepository_TryIncrementRegistrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Session
		if args[1] != nil {
			arg1 = args[1].(repository.Session)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_TryIncrementRegistrants_Call) Return(b bool, err error) *MockRepository_TryIncrementRegistrants_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_TryIncrementRegistrants_Call) RunAndReturn(run func(ctx context.Context, session repository.Session, conversationId uuid.UUID) (bool, error)) *MockRepository_TryIncrementRegistrants_Call {
	_c.Call.Return(run)
	return _c
}

// Tx provides a mock function for the type MockRepository
func (_mock *MockRepository) Tx() repository.Session {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tx")
	}

	var r0 repository.Session
	if returnFunc, ok := ret.Get(0).(func() repository.Session); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Session)
		}
	}
	return r0
}

// MockRepository_Tx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tx'
type MockRepository_Tx_Call struct {
	*mock.Call
}

// Tx is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Tx() *MockRepository_Tx_Call {
	return &MockRepository_Tx_Call{Call: _e.mock.On("Tx")}
}

func (_c *MockRepository_Tx_Call) Run(run func()) *MockRepository_Tx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Tx_Call) Return(session repository.Session) *MockRepository_Tx_Call {
	_c.Call.Return(session)
	return _c
}

func (_c *MockRepository_Tx_Call) RunAndReturn(run func() repository.Session) *MockRepository_Tx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConversationIfModerator provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateConversationIfModerator(ctx context.Context, session repository.Session, memberId uuid.UUID, req dto.UpdateConversationRequest) (bool, error) {
	ret := _mock.Called(ctx, session, memberId, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConversationIfModerator")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID, dto.UpdateConversationRequest) (bool, error)); ok {
		return returnFunc(ctx, session, memberId, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Session, uuid.UUID, dto.UpdateConversationRequest) bool); ok {
		r0 = returnFunc(ctx, session, memberId, req)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.Session, uuid.UUID, dto.UpdateConversationRequest) error); ok {
		r1 = returnFunc(ctx, session, memberId, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_UpdateConversationIfModerator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConversationIfModerator'
type MockRepository_UpdateConversationIfModerator_Call struct {
	*mock.Call
}

// UpdateConversationIfModerator is a helper method to define mock.On call
//   - ctx context.Context
//   - session repository.Session
//   - memberId uuid.UUID
//   - req dto.UpdateConversationRequest
func (_e *MockRepository_Expecter) UpdateConversationIfModerator(ctx any, session any, memberId any, req any) *MockRepository_UpdateConversationIfModerator_Call {
	return &MockRepository_UpdateConversationIfModerator_Call{Call: _e.mock.On("UpdateConversationIfModerator", ctx, session, memberId, req)}
}

func (_c *MockRepository_UpdateConversationIfModerator_Call) Run(run func(ctx context.Context, session repository.Session, memberId uuid.UUID, req dto.UpdateConversationRequest)) *MockRepository_UpdateConversationIfModerator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Session
		if args[1] != nil {
			arg1 = args[1].(repository.Session)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.UpdateConversationRequest
		if args[3] != nil {
			arg3 = args[3].(dto.UpdateConversationRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateConversationIfModerator_Call) Return(b bool, err error) *MockRepository_UpdateConversationIfModerator_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_UpdateConversationIfModerator_Call) RunAndReturn(run func(ctx context.Context, session repository.Session, memberId uuid.UUID, req dto.UpdateConversationRequest) (bool, error)) *MockRepository_UpdateConversationIfModerator_Call {
	_c.Call.Return(run)
	return _c
}
