// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"backend/onlineconversation/internal/dto"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AddParticipant provides a mock function for the type MockService
func (_mock *MockService) AddParticipant(ctx context.Context, conversationId string, memberId uuid.UUID) error {
	ret := _mock.Called(ctx, conversationId, memberId)

	if len(ret) == 0 {
		panic("no return value specified for AddParticipant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, conversationId, memberId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AddParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddParticipant'
type MockService_AddParticipant_Call struct {
	*mock.Call
}

// AddParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationId string
//   - memberId uuid.UUID
func (_e *MockService_Expecter) AddParticipant(ctx any, conversationId any, memberId any) *MockService_AddParticipant_Call {
	return &MockService_AddParticipant_Call{Call: _e.mock.On("AddParticipant", ctx, conversationId, memberId)}
}

func (_c *MockService_AddParticipant_Call) Run(run func(ctx context.Context, conversationId string, memberId uuid.UUID)) *MockService_AddParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_AddParticipant_Call) Return(err error) *MockService_AddParticipant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AddParticipant_Call) RunAndReturn(run func(ctx context.Context, conversationId string, memberId uuid.UUID) error) *MockService_AddParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// BanParticipant provides a mock function for the type MockService
func (_mock *MockService) BanParticipant(ctx context.Context, modId uuid.UUID, conversationId uuid.UUID, banId uuid.UUID) error {
	ret := _mock.Called(ctx, modId, conversationId, banId)

	if len(ret) == 0 {
		panic("no return value specified for BanParticipant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, modId, conversationId, banId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_BanParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BanParticipant'
type MockService_BanParticipant_Call struct {
	*mock.Call
}

// BanParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - modId uuid.UUID
//   - conversationId uuid.UUID
//   - banId uuid.UUID
func (_e *MockService_Expecter) BanParticipant(ctx any, modId any, conversationId any, banId any) *MockService_BanParticipant_Call {
	return &MockService_BanParticipant_Call{Call: _e.mock.On("BanParticipant", ctx, modId, conversationId, banId)}
}

func (_c *MockService_BanParticipant_Call) Run(run func(ctx context.Context, modId uuid.UUID, conversationId uuid.UUID, banId uuid.UUID)) *MockService_BanParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_BanParticipant_Call) Return(err error) *MockService_BanParticipant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_BanParticipant_Call) RunAndReturn(run func(ctx context.Context, modId uuid.UUID, conversationId uuid.UUID, banId uuid.UUID) error) *MockService_BanParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// CancelNotification provides a mock function for the type MockService
func (_mock *MockService) CancelNotification(ctx context.Context, memberId uuid.UUID, conversationId uuid.UUID) error {
	ret := _mock.Called(ctx, memberId, conversationId)

	if len(ret) == 0 {
		panic("no return value specified for CancelNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, memberId, conversationId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CancelNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelNotification'
type MockService_CancelNotification_Call struct {
	*mock.Call
}

// CancelNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - memberId uuid.UUID
//   - conversationId uuid.UUID
func (_e *MockService_Expecter) CancelNotification(ctx any, memberId any, conversationId any) *MockService_CancelNotification_Call {
	return &MockService_CancelNotification_Call{Call: _e.mock.On("CancelNotification", ctx, memberId, conversationId)}
}

func (_c *MockService_CancelNotification_Call) Run(run func(ctx context.Context, memberId uuid.UUID, conversationId uuid.UUID)) *MockService_CancelNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_CancelNotification_Call) Return(err error) *MockService_CancelNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CancelNotification_Call) RunAndReturn(run func(ctx context.Context, memberId uuid.UUID, conversationId uuid.UUID) error) *MockService_CancelNotification_Call {
	_c.Call.Return(run)
	return _c
}

// CreateConversation provides a mock function for the type MockService
func (_mock *MockService) CreateConversation(ctx context.Context, memberId uuid.UUID, req dto.CreateConversationRequest) (map[string]uuid.UUID, error) {
	ret := _mock.Called(ctx, memberId, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateConversation")
	}

	var r0 map[string]uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateConversationRequest) (map[string]uuid.UUID, error)); ok {
		return returnFunc(ctx, memberId, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateConversationRequest) map[string]uuid.UUID); ok {
		r0 = returnFunc(ctx, memberId, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.CreateConversationRequest) error); ok {
		r1 = returnFunc(ctx, memberId, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConversation'
type MockService_CreateConversation_Call struct {
	*mock.Call
}

// CreateConversation is a helper method to define mock.On call
//   - ctx context.Context
//   - memberId uuid.UUID
//   - req dto.CreateConversationRequest
func (_e *MockService_Expecter) CreateConversation(ctx any, memberId any, req any) *MockService_CreateConversation_Call {
	return &MockService_CreateConversation_Call{Call: _e.mock.On("CreateConversation", ctx, memberId, req)}
}

func (_c *MockService_CreateConversation_Call) Run(run func(ctx context.Context, memberId uuid.UUID, req dto.CreateConversationRequest)) *MockService_CreateConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.CreateConversationRequest
		if args[2] != nil {
			arg2 = args[2].(dto.CreateConversationRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_CreateConversation_Call) Return(stringToUUID map[string]uuid.UUID, err error) *MockService_CreateConversation_Call {
	_c.Call.Return(stringToUUID, err)
	return _c
}

func (_c *MockService_CreateConversation_Call) RunAndReturn(run func(ctx context.Context, memberId uuid.UUID, req dto.CreateConversationRequest) (map[string]uuid.UUID, error)) *MockService_CreateConversation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteConversation provides a mock function for the type MockService
func (_mock *MockService) DeleteConversation(ctx context.Context, memberId uuid.UUID, conversationId uuid.UUID) error {
	ret := _mock.Called(ctx, memberId, conversationId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConversation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, memberId, conversationId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConversation'
type MockService_DeleteConversation_Call struct {
	*mock.Call
}

// DeleteConversation is a helper method to define mock.On call
//   - ctx context.Context
//   - memberId uuid.UUID
//   - conversationId uuid.UUID
func (_e *MockService_Expecter) DeleteConversation(ctx any, memberId any, conversationId any) *MockService_DeleteConversation_Call {
	return &MockService_DeleteConversation_Call{Call: _e.mock.On("DeleteConversation", ctx, memberId, conversationId)}
}

func (_c *MockService_DeleteConversation_Call) Run(run func(ctx context.Context, memberId uuid.UUID, conversationId uuid.UUID)) *MockService_DeleteConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteConversation_Call) Return(err error) *MockService_DeleteConversation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteConversation_Call) RunAndReturn(run func(ctx context.Context, memberId uuid.UUID, conversationId uuid.UUID) error) *MockService_DeleteConversation_Call {
	_c.Call.Return(run)
	return _c
}

// DeregisterOnlineConversation provides a mock function for the type MockService
func (_mock *MockService) DeregisterOnlineConversation(ctx context.Context, memberId uuid.UUID, conversationId uuid.UUID) error {
	ret := _mock.Called(ctx, memberId, conversationId)

	if len(ret) == 0 {
		panic("no return value specified for DeregisterOnlineConversation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, memberId, conversationId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeregisterOnlineConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeregisterOnlineConversation'
type MockService_DeregisterOnlineConversation_Call struct {
	*mock.Call
}

// DeregisterOnlineConversation is a helper method to define mock.On call
//   - ctx context.Context
//   - memberId uuid.UUID
//   - conversationId uuid.UUID
func (_e *MockService_Expecter) DeregisterOnlineConversation(ctx any, memberId any, conversationId any) *MockService_DeregisterOnlineConversation_Call {
	return &MockService_DeregisterOnlineConversation_Call{Call: _e.mock.On("DeregisterOnlineConversation", ctx, memberId, conversationId)}
}

func (_c *MockService_DeregisterOnlineConversation_Call) Run(run func(ctx context.Context, memberId uuid.UUID, conversationId uuid.UUID)) *MockService_DeregisterOnlineConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeregisterOnlineConversation_Call) Return(err error) *MockService_DeregisterOnlineConversation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeregisterOnlineConversation_Call) RunAndReturn(run func(ctx context.Context, memberId uuid.UUID, conversationId uuid.UUID) error) *MockService_DeregisterOnlineConversation_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateTurn provides a mock function for the type MockService
func (_mock *MockService) GenerateTurn() *dto.GetTurnResponse {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateTurn")
	}

	var r0 *dto.GetTurnResponse
	if returnFunc, ok := ret.Get(0).(func() *dto.GetTurnResponse); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetTurnResponse)
		}
	}
	return r0
}

// MockService_GenerateTurn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTurn'
type MockService_GenerateTurn_Call struct {
	*mock.Call
}

// GenerateTurn is a helper method to define mock.On call
func (_e *MockService_Expecter) GenerateTurn() *MockService_GenerateTurn_Call {
	return &MockService_GenerateTurn_Call{Call: _e.mock.On("GenerateTurn")}
}

func (_c *MockService_GenerateTurn_Call) Run(run func()) *MockService_GenerateTurn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GenerateTurn_Call) Return(getTurnResponse *dto.GetTurnResponse) *MockService_GenerateTurn_Call {
	_c.Call.Return(getTurnResponse)
	return _c
}

func (_c *MockService_GenerateTurn_Call) RunAndReturn(run func() *dto.GetTurnResponse) *MockService_GenerateTurn_Call {
	_c.Call.Return(run)
	return _c
}

// GetConversationDetail provides a mock function for the type MockService
func (_mock *MockService) GetConversationDetail(ctx context.Context, conversationId uuid.UUID, memberId uuid.UUID) (*dto.OnlineConversationDetailResponse, error) {
	ret := _mock.Called(ctx, conversationId, memberId)

	if len(ret) == 0 {
		panic("no return value specified for GetConversationDetail")
	}

	var r0 *dto.OnlineConversationDetailResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.OnlineConversationDetailResponse, error)); ok {
		return returnFunc(ctx, conversationId, memberId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.OnlineConversationDetailResponse); ok {
		r0 = returnFunc(ctx, conversationId, memberId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OnlineConversationDetailResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, conversationId, memberId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetConversationDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConversationDetail'
type MockService_GetConversationDetail_Call struct {
	*mock.Call
}

// GetConversationDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationId uuid.UUID
//   - memberId uuid.UUID
func (_e *MockService_Expecter) GetConversationDetail(ctx any, conversationId any, memberId any) *MockService_GetConversationDetail_Call {
	return &MockService_GetConversationDetail_Call{Call: _e.mock.On("GetConversationDetail", ctx, conversationId, memberId)}
}

func (_c *MockService_GetConversationDetail_Call) Run(run func(ctx context.Context, conversationId uuid.UUID, memberId uuid.UUID)) *MockService_GetConversationDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetConversationDetail_Call) Return(onlineConversationDetailResponse *dto.OnlineConversationDetailResponse, err error) *MockService_GetConversationDetail_Call {
	_c.Call.Return(onlineConversationDetailResponse, err)
	return _c
}

func (_c *MockService_GetConversationDetail_Call) RunAndReturn(run func(ctx context.Context, conversationId uuid.UUID, memberId uuid.UUID) (*dto.OnlineConversationDetailResponse, error)) *MockService_GetConversationDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipantsWithoutMe provides a mock function for the type MockService
func (_mock *MockService) GetParticipantsWithoutMe(ctx context.Context, conversationId string, memberId uuid.UUID) ([]uuid.UUID, error) {
	ret := _mock.Called(ctx, conversationId, memberId)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipantsWithoutMe")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, conversationId, memberId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) []uuid.UUID); ok {
		r0 = returnFunc(ctx, conversationId, memberId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, conversationId, memberId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetParticipantsWithoutMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipantsWithoutMe'
type MockService_GetParticipantsWithoutMe_Call struct {
	*mock.Call
}

// GetParticipantsWithoutMe is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationId string
//   - memberId uuid.UUID
func (_e *MockService_Expecter) GetParticipantsWithoutMe(ctx any, conversationId any, memberId any) *MockService_GetParticipantsWithoutMe_Call {
	return &MockService_GetParticipantsWithoutMe_Call{Call: _e.mock.On("GetParticipantsWithoutMe", ctx, conversationId, memberId)}
}

func (_c *MockService_GetParticipantsWithoutMe_Call) Run(run func(ctx context.Context, conversationId string, memberId uuid.UUID)) *MockService_GetParticipantsWithoutMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetParticipantsWithoutMe_Call) Return(uUIDs []uuid.UUID, err error) *MockService_GetParticipantsWithoutMe_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockService_GetParticipantsWithoutMe_Call) RunAndReturn(run func(ctx context.Context, conversationId string, memberId uuid.UUID) ([]uuid.UUID, error)) *MockService_GetParticipantsWithoutMe_Call {
	_c.Call.Return(run)
	return _c
}

// PublishConversationSignal provides a mock function for the type MockService
func (_mock *MockService) PublishConversationSignal(fromId uuid.UUID, toIds [][]byte, signal []byte) error {
	ret := _mock.Called(fromId, toIds, signal)

	if len(ret) == 0 {
		panic("no return value specified for PublishConversationSignal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, [][]byte, []byte) error); ok {
		r0 = returnFunc(fromId, toIds, signal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_PublishConversationSignal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishConversationSignal'
type MockService_PublishConversationSignal_Call struct {
	*mock.Call
}

// PublishConversationSignal is a helper method to define mock.On call
//   - fromId uuid.UUID
//   - toIds [][]byte
//   - signal []byte
func (_e *MockService_Expecter) PublishConversationSignal(fromId any, toIds any, signal any) *MockService_PublishConversationSignal_Call {
	return &MockService_PublishConversationSignal_Call{Call: _e.mock.On("PublishConversationSignal", fromId, toIds, signal)}
}

func (_c *MockService_PublishConversationSignal_Call) Run(run func(fromId uuid.UUID, toIds [][]byte, signal []byte)) *MockService_PublishConversationSignal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 [][]byte
		if args[1] != nil {
			arg1 = args[1].([][]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_PublishConversationSignal_Call) Return(err error) *MockService_PublishConversationSignal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_PublishConversationSignal_Call) RunAndReturn(run func(fromId uuid.UUID, toIds [][]byte, signal []byte) error) *MockService_PublishConversationSignal_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterOnlineConversation provides a mock function for the type MockService
func (_mock *MockService) RegisterOnlineConversation(ctx context.Context, memberId uuid.UUID, conversationId uuid.UUID) error {
	ret := _mock.Called(ctx, memberId, conversationId)

	if len(ret) == 0 {
		panic("no return value specified for RegisterOnlineConversation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, memberId, conversationId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RegisterOnlineConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterOnlineConversation'
type MockService_RegisterOnlineConversation_Call struct {
	*mock.Call
}

// RegisterOnlineConversation is a helper method to define mock.On call
//   - ctx context.Context
//   - memberId uuid.UUID
//   - conversationId uuid.UUID
func (_e *MockService_Expecter) RegisterOnlineConversation(ctx any, memberId any, conversationId any) *MockService_RegisterOnlineConversation_Call {
	return &MockService_RegisterOnlineConversation_Call{Call: _e.mock.On("RegisterOnlineConversation", ctx, memberId, conversationId)}
}

func (_c *MockService_RegisterOnlineConversation_Call) Run(run func(ctx context.Context, memberId uuid.UUID, conversationId uuid.UUID)) *MockService_RegisterOnlineConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_RegisterOnlineConversation_Call) Return(err error) *MockService_RegisterOnlineConversation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RegisterOnlineConversation_Call) RunAndReturn(run func(ctx context.Context, memberId uuid.UUID, conversationId uuid.UUID) error) *MockService_RegisterOnlineConversation_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveParticipant provides a mock function for the type MockService
func (_mock *MockService) RemoveParticipant(ctx context.Context, conversationId string, memberId uuid.UUID) error {
	ret := _mock.Called(ctx, conversationId, memberId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveParticipant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, conversationId, memberId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RemoveParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveParticipant'
type MockService_RemoveParticipant_Call struct {
	*mock.Call
}

// RemoveParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationId string
//   - memberId uuid.UUID
func (_e *MockService_Expecter) RemoveParticipant(ctx any, conversationId any, memberId any) *MockService_RemoveParticipant_Call {
	return &MockService_RemoveParticipant_Call{Call: _e.mock.On("RemoveParticipant", ctx, conversationId, memberId)}
}

func (_c *MockService_RemoveParticipant_Call) Run(run func(ctx context.Context, conversationId string, memberId uuid.UUID)) *MockService_RemoveParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_RemoveParticipant_Call) Return(err error) *MockService_RemoveParticipant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RemoveParticipant_Call) RunAndReturn(run func(ctx context.Context, conversationId string, memberId uuid.UUID) error) *MockService_RemoveParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveServerIP provides a mock function for the type MockService
func (_mock *MockService) RemoveServerIP(ctx context.Context, memberId uuid.UUID) error {
	ret := _mock.Called(ctx, memberId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveServerIP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, memberId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RemoveServerIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveServerIP'
type MockService_RemoveServerIP_Call struct {
	*mock.Call
}

// RemoveServerIP is a helper method to define mock.On call
//   - ctx context.Context
//   - memberId uuid.UUID
func (_e *MockService_Expecter) RemoveServerIP(ctx any, memberId any) *MockService_RemoveServerIP_Call {
	return &MockService_RemoveServerIP_Call{Call: _e.mock.On("RemoveServerIP", ctx, memberId)}
}

func (_c *MockService_RemoveServerIP_Call) Run(run func(ctx context.Context, memberId uuid.UUID)) *MockService_RemoveServerIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RemoveServerIP_Call) Return(err error) *MockService_RemoveServerIP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RemoveServerIP_Call) RunAndReturn(run func(ctx context.Context, memberId uuid.UUID) error) *MockService_RemoveServerIP_Call {
	_c.Call.Return(run)
	return _c
}

// ScheduleNotification provides a mock function for the type MockService
func (_mock *MockService) ScheduleNotification(ctx context.Context, memberId uuid.UUID, conversationId uuid.UUID) error {
	ret := _mock.Called(ctx, memberId, conversationId)

	if len(ret) == 0 {
		panic("no return value specified for ScheduleNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, memberId, conversationId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ScheduleNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleNotification'
type MockService_ScheduleNotification_Call struct {
	*mock.Call
}

// ScheduleNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - memberId uuid.UUID
//   - conversationId uuid.UUID
func (_e *MockService_Expecter) ScheduleNotification(ctx any, memberId any, conversationId any) *MockService_ScheduleNotification_Call {
	return &MockService_ScheduleNotification_Call{Call: _e.mock.On("ScheduleNotification", ctx, memberId, conversationId)}
}

func (_c *MockService_ScheduleNotification_Call) Run(run func(ctx context.Context, memberId uuid.UUID, conversationId uuid.UUID)) *MockService_ScheduleNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ScheduleNotification_Call) Return(err error) *MockService_ScheduleNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ScheduleNotification_Call) RunAndReturn(run func(ctx context.Context, memberId uuid.UUID, conversationId uuid.UUID) error) *MockService_ScheduleNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SetServerIP provides a mock function for the type MockService
func (_mock *MockService) SetServerIP(ctx context.Context, memberId uuid.UUID, ip string) error {
	ret := _mock.Called(ctx, memberId, ip)

	if len(ret) == 0 {
		panic("no return value specified for SetServerIP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, memberId, ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SetServerIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetServerIP'
type MockService_SetServerIP_Call struct {
	*mock.Call
}

// SetServerIP is a helper method to define mock.On call
//   - ctx context.Context
//   - memberId uuid.UUID
//   - ip string
func (_e *MockService_Expecter) SetServerIP(ctx any, memberId any, ip any) *MockService_SetServerIP_Call {
	return &MockService_SetServerIP_Call{Call: _e.mock.On("SetServerIP", ctx, memberId, ip)}
}

func (_c *MockService_SetServerIP_Call) Run(run func(ctx context.Context, memberId uuid.UUID, ip string)) *MockService_SetServerIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SetServerIP_Call) Return(err error) *MockService_SetServerIP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SetServerIP_Call) RunAndReturn(run func(ctx context.Context, memberId uuid.UUID, ip string) error) *MockService_SetServerIP_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConversation provides a mock function for the type MockService
func (_mock *MockService) UpdateConversation(ctx context.Context, memberId uuid.UUID, req dto.UpdateConversationRequest) error {
	ret := _mock.Called(ctx, memberId, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConversation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateConversationRequest) error); ok {
		r0 = returnFunc(ctx, memberId, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConversation'
type MockService_UpdateConversation_Call struct {
	*mock.Call
}

// UpdateConversation is a helper method to define mock.On call
//   - ctx context.Context
//   - memberId uuid.UUID
//   - req dto.UpdateConversationRequest
func (_e *MockService_Expecter) UpdateConversation(ctx any, memberId any, req any) *MockService_UpdateConversation_Call {
	return &MockService_UpdateConversation_Call{Call: _e.mock.On("UpdateConversation", ctx, memberId, req)}
}

func (_c *MockService_UpdateConversation_Call) Run(run func(ctx context.Context, memberId uuid.UUID, req dto.UpdateConversationRequest)) *MockService_UpdateConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.UpdateConversationRequest
		if args[2] != nil {
			arg2 = args[2].(dto.UpdateConversationRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UpdateConversation_Call) Return(err error) *MockService_UpdateConversation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateConversation_Call) RunAndReturn(run func(ctx context.Context, memberId uuid.UUID, req dto.UpdateConversationRequest) error) *MockService_UpdateConversation_Call {
	_c.Call.Return(run)
	return _c
}
