// Package mocks provides testify mocks of the common interfaces for the services' tests.
// Only tests import it, so it is never linked into service binaries.
// Generated by go tool mockery, see .mockery.yml.
package mocks
