// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCDNClient creates a new instance of MockCDNClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCDNClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCDNClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCDNClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCDNClient is an autogenerated mock type for the CDNClient type
type MockCDNClient struct {
	mock.Mock
}

type MockCDNClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCDNClient) EXPECT() *MockCDNClient_Expecter {
	return &MockCDNClient_Expecter{mock: &_m.Mock}
}

// SignedURL provides a mock function for the type MockCDNClient
func (_mock *MockCDNClient) SignedURL(contentType string, filename string) (string, error) {
	ret := _mock.Called(contentType, filename)

	if len(ret) == 0 {
		panic("no return value specified for SignedURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(contentType, filename)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(contentType, filename)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(contentType, filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCDNClient_SignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignedURL'
type MockCDNClient_SignedURL_Call struct {
	*mock.Call
}

// SignedURL is a helper method to define mock.On call
//   - contentType string
//   - filename string
func (_e *MockCDNClient_Expecter) SignedURL(contentType any, filename any) *MockCDNClient_SignedURL_Call {
	return &MockCDNClient_SignedURL_Call{Call: _e.mock.On("SignedURL", contentType, filename)}
}

func (_c *MockCDNClient_SignedURL_Call) Run(run func(contentType string, filename string)) *MockCDNClient_SignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCDNClient_SignedURL_Call) Return(s string, err error) *MockCDNClient_SignedURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCDNClient_SignedURL_Call) RunAndReturn(run func(contentType string, filename string) (string, error)) *MockCDNClient_SignedURL_Call {
	_c.Call.Return(run)
	return _c
}
