// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer struct {
	mock.Mock
}

type MockProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducer) EXPECT() *MockProducer_Expecter {
	return &MockProducer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockProducer
func (_mock *MockProducer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockProducer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockProducer_Expecter) Close() *MockProducer_Close_Call {
	return &MockProducer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockProducer_Close_Call) Run(run func()) *MockProducer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProducer_Close_Call) Return(err error) *MockProducer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducer_Close_Call) RunAndReturn(run func() error) *MockProducer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// PushMessage provides a mock function for the type MockProducer
func (_mock *MockProducer) PushMessage(topic string, key []byte, value []byte, headers []sarama.RecordHeader) {
	_mock.Called(topic, key, value, headers)
	return
}

// MockProducer_PushMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushMessage'
type MockProducer_PushMessage_Call struct {
	*mock.Call
}

// PushMessage is a helper method to define mock.On call
//   - topic string
//   - key []byte
//   - value []byte
//   - headers []sarama.RecordHeader
func (_e *MockProducer_Expecter) PushMessage(topic any, key any, value any, headers any) *MockProducer_PushMessage_Call {
	return &MockProducer_PushMessage_Call{Call: _e.mock.On("PushMessage", topic, key, value, headers)}
}

func (_c *MockProducer_PushMessage_Call) Run(run func(topic string, key []byte, value []byte, headers []sarama.RecordHeader)) *MockProducer_PushMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 []sarama.RecordHeader
		if args[3] != nil {
			arg3 = args[3].([]sarama.RecordHeader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProducer_PushMessage_Call) Return() *MockProducer_PushMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProducer_PushMessage_Call) RunAndReturn(run func(topic string, key []byte, value []byte, headers []sarama.RecordHeader)) *MockProducer_PushMessage_Call {
	_c.Run(run)
	return _c
}
