// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"backend/common/proto"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRelayClient creates a new instance of MockRelayClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRelayClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRelayClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRelayClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRelayClient is an autogenerated mock type for the RelayClient type
type MockRelayClient struct {
	mock.Mock
}

type MockRelayClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRelayClient) EXPECT() *MockRelayClient_Expecter {
	return &MockRelayClient_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockRelayClient
func (_mock *MockRelayClient) Do(ctx context.Context, ip string, req *proto.RelaySignalRequest) error {
	ret := _mock.Called(ctx, ip, req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *proto.RelaySignalRequest) error); ok {
		r0 = returnFunc(ctx, ip, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRelayClient_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockRelayClient_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - ip string
//   - req *proto.RelaySignalRequest
func (_e *MockRelayClient_Expecter) Do(ctx any, ip any, req any) *MockRelayClient_Do_Call {
	return &MockRelayClient_Do_Call{Call: _e.mock.On("Do", ctx, ip, req)}
}

func (_c *MockRelayClient_Do_Call) Run(run func(ctx context.Context, ip string, req *proto.RelaySignalRequest)) *MockRelayClient_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *proto.RelaySignalRequest
		if args[2] != nil {
			arg2 = args[2].(*proto.RelaySignalRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRelayClient_Do_Call) Return(err error) *MockRelayClient_Do_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRelayClient_Do_Call) RunAndReturn(run func(ctx context.Context, ip string, req *proto.RelaySignalRequest) error) *MockRelayClient_Do_Call {
	_c.Call.Return(run)
	return _c
}
