// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetServerIP provides a mock function for the type MockRepository
func (_mock *MockRepository) GetServerIP(ctx context.Context, id string) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetServerIP")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetServerIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServerIP'
type MockRepository_GetServerIP_Call struct {
	*mock.Call
}

// GetServerIP is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetServerIP(ctx any, id any) *MockRepository_GetServerIP_Call {
	return &MockRepository_GetServerIP_Call{Call: _e.mock.On("GetServerIP", ctx, id)}
}

func (_c *MockRepository_GetServerIP_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetServerIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetServerIP_Call) Return(s string, err error) *MockRepository_GetServerIP_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRepository_GetServerIP_Call) RunAndReturn(run func(ctx context.Context, id string) (string, error)) *MockRepository_GetServerIP_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveServerIP provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveServerIP(ctx context.Context, memberId string) error {
	ret := _mock.Called(ctx, memberId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveServerIP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, memberId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RemoveServerIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveServerIP'
type MockRepository_RemoveServerIP_Call struct {
	*mock.Call
}

// RemoveServerIP is a helper method to define mock.On call
//   - ctx context.Context
//   - memberId string
func (_e *MockRepository_Expecter) RemoveServerIP(ctx any, memberId any) *MockRepository_RemoveServerIP_Call {
	return &MockRepository_RemoveServerIP_Call{Call: _e.mock.On("RemoveServerIP", ctx, memberId)}
}

func (_c *MockRepository_RemoveServerIP_Call) Run(run func(ctx context.Context, memberId string)) *MockRepository_RemoveServerIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_RemoveServerIP_Call) Return(err error) *MockRepository_RemoveServerIP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RemoveServerIP_Call) RunAndReturn(run func(ctx context.Context, memberId string) error) *MockRepository_RemoveServerIP_Call {
	_c.Call.Return(run)
	return _c
}
