// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"backend/notification/internal/projection"
	"context"

	"github.com/apache/cassandra-gocql-driver/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// DeleteNotificationInfoByIdAndToken provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteNotificationInfoByIdAndToken(ctx context.Context, id gocql.UUID, token string) error {
	ret := _mock.Called(ctx, id, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNotificationInfoByIdAndToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteNotificationInfoByIdAndToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNotificationInfoByIdAndToken'
type MockRepository_DeleteNotificationInfoByIdAndToken_Call struct {
	*mock.Call
}

// DeleteNotificationInfoByIdAndToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id gocql.UUID
//   - token string
func (_e *MockRepository_Expecter) DeleteNotificationInfoByIdAndToken(ctx any, id any, token any) *MockRepository_DeleteNotificationInfoByIdAndToken_Call {
	return &MockRepository_DeleteNotificationInfoByIdAndToken_Call{Call: _e.mock.On("DeleteNotificationInfoByIdAndToken", ctx, id, token)}
}

func (_c *MockRepository_DeleteNotificationInfoByIdAndToken_Call) Run(run func(ctx context.Context, id gocql.UUID, token string)) *MockRepository_DeleteNotificationInfoByIdAndToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteNotificationInfoByIdAndToken_Call) Return(err error) *MockRepository_DeleteNotificationInfoByIdAndToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteNotificationInfoByIdAndToken_Call) RunAndReturn(run func(ctx context.Context, id gocql.UUID, token string) error) *MockRepository_DeleteNotificationInfoByIdAndToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindMemberIdByToken provides a mock function for the type MockRepository
func (_mock *MockRepository) FindMemberIdByToken(ctx context.Context, token string) (gocql.UUID, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindMemberIdByToken")
	}

	var r0 gocql.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (gocql.UUID, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) gocql.UUID); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocql.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindMemberIdByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMemberIdByToken'
type MockRepository_FindMemberIdByToken_Call struct {
	*mock.Call
}

// FindMemberIdByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockRepository_Expecter) FindMemberIdByToken(ctx any, token any) *MockRepository_FindMemberIdByToken_Call {
	return &MockRepository_FindMemberIdByToken_Call{Call: _e.mock.On("FindMemberIdByToken", ctx, token)}
}

func (_c *MockRepository_FindMemberIdByToken_Call) Run(run func(ctx context.Context, token string)) *MockRepository_FindMemberIdByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindMemberIdByToken_Call) Return(id gocql.UUID, err error) *MockRepository_FindMemberIdByToken_Call {
	_c.Call.Return(id, err)
	return _c
}

func (_c *MockRepository_FindMemberIdByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (gocql.UUID, error)) *MockRepository_FindMemberIdByToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindNameById provides a mock function for the type MockRepository
func (_mock *MockRepository) FindNameById(ctx context.Context, id gocql.UUID) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindNameById")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gocql.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindNameById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNameById'
type MockRepository_FindNameById_Call struct {
	*mock.Call
}

// FindNameById is a helper method to define mock.On call
//   - ctx context.Context
//   - id gocql.UUID
func (_e *MockRepository_Expecter) FindNameById(ctx any, id any) *MockRepository_FindNameById_Call {
	return &MockRepository_FindNameById_Call{Call: _e.mock.On("FindNameById", ctx, id)}
}

func (_c *MockRepository_FindNameById_Call) Run(run func(ctx context.Context, id gocql.UUID)) *MockRepository_FindNameById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindNameById_Call) Return(name string, err error) *MockRepository_FindNameById_Call {
	_c.Call.Return(name, err)
	return _c
}

func (_c *MockRepository_FindNameById_Call) RunAndReturn(run func(ctx context.Context, id gocql.UUID) (string, error)) *MockRepository_FindNameById_Call {
	_c.Call.Return(run)
	return _c
}

// FindPushTokensById provides a mock function for the type MockRepository
func (_mock *MockRepository) FindPushTokensById(ctx context.Context, id gocql.UUID) ([]projection.FindPushTokensById, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindPushTokensById")
	}

	var r0 []projection.FindPushTokensById
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID) ([]projection.FindPushTokensById, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID) []projection.FindPushTokensById); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]projection.FindPushTokensById)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gocql.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindPushTokensById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPushTokensById'
type MockRepository_FindPushTokensById_Call struct {
	*mock.Call
}

// FindPushTokensById is a helper method to define mock.On call
//   - ctx context.Context
//   - id gocql.UUID
func (_e *MockRepository_Expecter) FindPushTokensById(ctx any, id any) *MockRepository_FindPushTokensById_Call {
	return &MockRepository_FindPushTokensById_Call{Call: _e.mock.On("FindPushTokensById", ctx, id)}
}

func (_c *MockRepository_FindPushTokensById_Call) Run(run func(ctx context.Context, id gocql.UUID)) *MockRepository_FindPushTokensById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindPushTokensById_Call) Return(result []projection.FindPushTokensById, err error) *MockRepository_FindPushTokensById_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockRepository_FindPushTokensById_Call) RunAndReturn(run func(ctx context.Context, id gocql.UUID) ([]projection.FindPushTokensById, error)) *MockRepository_FindPushTokensById_Call {
	_c.Call.Return(run)
	return _c
}

// FindRoomNameById provides a mock function for the type MockRepository
func (_mock *MockRepository) FindRoomNameById(ctx context.Context, id gocql.UUID) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindRoomNameById")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gocql.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindRoomNameById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRoomNameById'
type MockRepository_FindRoomNameById_Call struct {
	*mock.Call
}

// FindRoomNameById is a helper method to define mock.On call
//   - ctx context.Context
//   - id gocql.UUID
func (_e *MockRepository_Expecter) FindRoomNameById(ctx any, id any) *MockRepository_FindRoomNameById_Call {
	return &MockRepository_FindRoomNameById_Call{Call: _e.mock.On("FindRoomNameById", ctx, id)}
}

func (_c *MockRepository_FindRoomNameById_Call) Run(run func(ctx context.Context, id gocql.UUID)) *MockRepository_FindRoomNameById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindRoomNameById_Call) Return(name string, err error) *MockRepository_FindRoomNameById_Call {
	_c.Call.Return(name, err)
	return _c
}

func (_c *MockRepository_FindRoomNameById_Call) RunAndReturn(run func(ctx context.Context, id gocql.UUID) (string, error)) *MockRepository_FindRoomNameById_Call {
	_c.Call.Return(run)
	return _c
}

// SaveNotificationInfoById provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveNotificationInfoById(ctx context.Context, id gocql.UUID, os string, token string) error {
	ret := _mock.Called(ctx, id, os, token)

	if len(ret) == 0 {
		panic("no return value specified for SaveNotificationInfoById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID, string, string) error); ok {
		r0 = returnFunc(ctx, id, os, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveNotificationInfoById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveNotificationInfoById'
type MockRepository_SaveNotificationInfoById_Call struct {
	*mock.Call
}

// SaveNotificationInfoById is a helper method to define mock.On call
//   - ctx context.Context
//   - id gocql.UUID
//   - os string
//   - token string
func (_e *MockRepository_Expecter) SaveNotificationInfoById(ctx any, id any, os any, token any) *MockRepository_SaveNotificationInfoById_Call {
	return &MockRepository_SaveNotificationInfoById_Call{Call: _e.mock.On("SaveNotificationInfoById", ctx, id, os, token)}
}

func (_c *MockRepository_SaveNotificationInfoById_Call) Run(run func(ctx context.Context, id gocql.UUID, os string, token string)) *MockRepository_SaveNotificationInfoById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_SaveNotificationInfoById_Call) Return(err error) *MockRepository_SaveNotificationInfoById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveNotificationInfoById_Call) RunAndReturn(run func(ctx context.Context, id gocql.UUID, os string, token string) error) *MockRepository_SaveNotificationInfoById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberIdByToken provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateMemberIdByToken(ctx context.Context, token string, id gocql.UUID) error {
	ret := _mock.Called(ctx, token, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberIdByToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, gocql.UUID) error); ok {
		r0 = returnFunc(ctx, token, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateMemberIdByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberIdByToken'
type MockRepository_UpdateMemberIdByToken_Call struct {
	*mock.Call
}

// UpdateMemberIdByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - id gocql.UUID
func (_e *MockRepository_Expecter) UpdateMemberIdByToken(ctx any, token any, id any) *MockRepository_UpdateMemberIdByToken_Call {
	return &MockRepository_UpdateMemberIdByToken_Call{Call: _e.mock.On("UpdateMemberIdByToken", ctx, token, id)}
}

func (_c *MockRepository_UpdateMemberIdByToken_Call) Run(run func(ctx context.Context, token string, id gocql.UUID)) *MockRepository_UpdateMemberIdByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 gocql.UUID
		if args[2] != nil {
			arg2 = args[2].(gocql.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateMemberIdByToken_Call) Return(err error) *MockRepository_UpdateMemberIdByToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateMemberIdByToken_Call) RunAndReturn(run func(ctx context.Context, token string, id gocql.UUID) error) *MockRepository_UpdateMemberIdByToken_Call {
	_c.Call.Return(run)
	return _c
}
