// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// PreprocessMessageNotification provides a mock function for the type MockService
func (_mock *MockService) PreprocessMessageNotification(ctx context.Context, notificationId uint8, messageId uuid.UUID, toIds [][]byte, roomId uuid.UUID, fromId uuid.UUID, contentType string, content []string) {
	_mock.Called(ctx, notificationId, messageId, toIds, roomId, fromId, contentType, content)
	return
}

// MockService_PreprocessMessageNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreprocessMessageNotification'
type MockService_PreprocessMessageNotification_Call struct {
	*mock.Call
}

// PreprocessMessageNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - notificationId uint8
//   - messageId uuid.UUID
//   - toIds [][]byte
//   - roomId uuid.UUID
//   - fromId uuid.UUID
//   - contentType string
//   - content []string
func (_e *MockService_Expecter) PreprocessMessageNotification(ctx any, notificationId any, messageId any, toIds any, roomId any, fromId any, contentType any, content any) *MockService_PreprocessMessageNotification_Call {
	return &MockService_PreprocessMessageNotification_Call{Call: _e.mock.On("PreprocessMessageNotification", ctx, notificationId, messageId, toIds, roomId, fromId, contentType, content)}
}

func (_c *MockService_PreprocessMessageNotification_Call) Run(run func(ctx context.Context, notificationId uint8, messageId uuid.UUID, toIds [][]byte, roomId uuid.UUID, fromId uuid.UUID, contentType string, content []string)) *MockService_PreprocessMessageNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint8
		if args[1] != nil {
			arg1 = args[1].(uint8)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 [][]byte
		if args[3] != nil {
			arg3 = args[3].([][]byte)
		}
		var arg4 uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(uuid.UUID)
		}
		var arg5 uuid.UUID
		if args[5] != nil {
			arg5 = args[5].(uuid.UUID)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 []string
		if args[7] != nil {
			arg7 = args[7].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockService_PreprocessMessageNotification_Call) Return() *MockService_PreprocessMessageNotification_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_PreprocessMessageNotification_Call) RunAndReturn(run func(ctx context.Context, notificationId uint8, messageId uuid.UUID, toIds [][]byte, roomId uuid.UUID, fromId uuid.UUID, contentType string, content []string)) *MockService_PreprocessMessageNotification_Call {
	_c.Run(run)
	return _c
}

// PreprocessScheduledNotification provides a mock function for the type MockService
func (_mock *MockService) PreprocessScheduledNotification(ctx context.Context, partitionId uuid.UUID, notifications map[uuid.UUID]map[int]string, contents map[int]string) {
	_mock.Called(ctx, partitionId, notifications, contents)
	return
}

// MockService_PreprocessScheduledNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreprocessScheduledNotification'
type MockService_PreprocessScheduledNotification_Call struct {
	*mock.Call
}

// PreprocessScheduledNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - partitionId uuid.UUID
//   - notifications map[uuid.UUID]map[int]string
//   - contents map[int]string
func (_e *MockService_Expecter) PreprocessScheduledNotification(ctx any, partitionId any, notifications any, contents any) *MockService_PreprocessScheduledNotification_Call {
	return &MockService_PreprocessScheduledNotification_Call{Call: _e.mock.On("PreprocessScheduledNotification", ctx, partitionId, notifications, contents)}
}

func (_c *MockService_PreprocessScheduledNotification_Call) Run(run func(ctx context.Context, partitionId uuid.UUID, notifications map[uuid.UUID]map[int]string, contents map[int]string)) *MockService_PreprocessScheduledNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 map[uuid.UUID]map[int]string
		if args[2] != nil {
			arg2 = args[2].(map[uuid.UUID]map[int]string)
		}
		var arg3 map[int]string
		if args[3] != nil {
			arg3 = args[3].(map[int]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_PreprocessScheduledNotification_Call) Return() *MockService_PreprocessScheduledNotification_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_PreprocessScheduledNotification_Call) RunAndReturn(run func(ctx context.Context, partitionId uuid.UUID, notifications map[uuid.UUID]map[int]string, contents map[int]string)) *MockService_PreprocessScheduledNotification_Call {
	_c.Run(run)
	return _c
}

// RegisterNotification provides a mock function for the type MockService
func (_mock *MockService) RegisterNotification(ctx context.Context, id uuid.UUID, os string, token string) error {
	ret := _mock.Called(ctx, id, os, token)

	if len(ret) == 0 {
		panic("no return value specified for RegisterNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = returnFunc(ctx, id, os, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RegisterNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterNotification'
type MockService_RegisterNotification_Call struct {
	*mock.Call
}

// RegisterNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - os string
//   - token string
func (_e *MockService_Expecter) RegisterNotification(ctx any, id any, os any, token any) *MockService_RegisterNotification_Call {
	return &MockService_RegisterNotification_Call{Call: _e.mock.On("RegisterNotification", ctx, id, os, token)}
}

func (_c *MockService_RegisterNotification_Call) Run(run func(ctx context.Context, id uuid.UUID, os string, token string)) *MockService_RegisterNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_RegisterNotification_Call) Return(err error) *MockService_RegisterNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RegisterNotification_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, os string, token string) error) *MockService_RegisterNotification_Call {
	_c.Call.Return(run)
	return _c
}
