// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"context"

	"github.com/apache/cassandra-gocql-driver/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// SaveMessage provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveMessage(ctx context.Context, id gocql.UUID, toId gocql.UUID, fromId gocql.UUID, roomId gocql.UUID, contentType string, contents []string) error {
	ret := _mock.Called(ctx, id, toId, fromId, roomId, contentType, contents)

	if len(ret) == 0 {
		panic("no return value specified for SaveMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID, gocql.UUID, gocql.UUID, gocql.UUID, string, []string) error); ok {
		r0 = returnFunc(ctx, id, toId, fromId, roomId, contentType, contents)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMessage'
type MockRepository_SaveMessage_Call struct {
	*mock.Call
}

// SaveMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - id gocql.UUID
//   - toId gocql.UUID
//   - fromId gocql.UUID
//   - roomId gocql.UUID
//   - contentType string
//   - contents []string
func (_e *MockRepository_Expecter) SaveMessage(ctx any, id any, toId any, fromId any, roomId any, contentType any, contents any) *MockRepository_SaveMessage_Call {
	return &MockRepository_SaveMessage_Call{Call: _e.mock.On("SaveMessage", ctx, id, toId, fromId, roomId, contentType, contents)}
}

func (_c *MockRepository_SaveMessage_Call) Run(run func(ctx context.Context, id gocql.UUID, toId gocql.UUID, fromId gocql.UUID, roomId gocql.UUID, contentType string, contents []string)) *MockRepository_SaveMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		var arg2 gocql.UUID
		if args[2] != nil {
			arg2 = args[2].(gocql.UUID)
		}
		var arg3 gocql.UUID
		if args[3] != nil {
			arg3 = args[3].(gocql.UUID)
		}
		var arg4 gocql.UUID
		if args[4] != nil {
			arg4 = args[4].(gocql.UUID)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 []string
		if args[6] != nil {
			arg6 = args[6].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockRepository_SaveMessage_Call) Return(err error) *MockRepository_SaveMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveMessage_Call) RunAndReturn(run func(ctx context.Context, id gocql.UUID, toId gocql.UUID, fromId gocql.UUID, roomId gocql.UUID, contentType string, contents []string) error) *MockRepository_SaveMessage_Call {
	_c.Call.Return(run)
	return _c
}
