---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  encryptedData:
    CF_API_TOKEN: AgCCRPD9Q4/1h86MzfiziNk4QcTcaBr11Bg9hpxFNuuoa/lTkka4yQzmfm/BCTaWeoX9kWcSvtcyvBPB8gqatF9Sii6mb6gJDFmCtXsyOW/txMQ5NOppsMPpzkNLemTSqtEK1NtqON9YzVZOEfeMfcXFtHR5n4b6CpeUbWyn+B9iY4Lr7uoArVNQYTgrAxxmytb4oQ5WoikEZg0iJaNX854nehLMshAjtJx6pFmMn1C6FGno36zua4PBTLurlV8xps86VxQsKnpunPJZSu4b5XNzhNXg/fr5KKVRD2Z25cpKcrc+SOz0jbrbt3AJiT/ShEdTWSAU647fvEhBKeKyXUMQA30hUWCgHq2Azf4VRbFImxlzgdiLEnNjmGB4EqzdJeNIYxy5MpBhD/Kw07sWShKeO0Wo+TXdNKbsTPvJhmZfjw8cPOrIVzPdSocNxnHKdAdhRSXxxBc3EGuPMjTEIjXYgdHGThjZ6607smwp/qSWPDra78fxjvZFg80o6fx369huddpijtI3BfLK//W7ZM9LWkOd71UTWwQ99DcxVYaujIyFj1GQdQfu3OyWYK/wz3E4arg+Erz39llYIMKGmWvSbzc1CHPrZGmxi1G2bZWvkgL0SwUoW7duXCnxGbcd5ZMLNcThUEyRB3VDUtfFwDvDsk5CbE07r6VXELm4e11et63F7DdpRXDBxEbQWlaGQG5csvqu3ZOysFPD3J4aYqHyEzIlXEHzf5aInowu30mwDuBwOyes9nAg3JD7RBbQ7RxLqZWi/A==
  template:
    metadata:
      name: cloudflare
      namespace: cert-manager
