---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr
  namespace: backend
spec:
  encryptedData:
    .dockerconfigjson: AgCdMaUAnvKpezJ2dUIZ7mXMwy+nsbAtIcayBOvcht6NQ+GCZWoY7mL8vQ+bKw+jTTyimLrRkWderpx+znPuxUy+nXiQgOSMqnYOG2CReUDg8jl+bTn6NhzgTeEw/PxLZvVdSPYMdeCpDpdJ8rN6UhrzaTVvXk36QQKxxOZHv+P2cfIJAexfSdUhuKVaAaKhHA2O6JYRe3mB1C8YnkAGibAYJ9vFgUmcX1FNAIYroK7CNI+TWT9+EvPu+KTZYhluFPk9I0Uw4bbaUk/ahN54KGlD/c4DdGrtNlZcM3OK8pX86B897TAsW3w2z9NQEbqBdIzId2zbuKGsGQ3ag3uHotPF8AYdSdDMQYMgxP0HNL5wqfp+nzBLN5kPCSayKuHqjwSwW49kz/gJmDr+S+RrqT41atclbs+Bbl5Jn+BbLI1MlkkYDroZRnNzZgTqSTZqmHsiOXFNUPGRxvlVM1zmLSPfuaYnBIxg7fJCPoVCtta66yYKgg9z/96TfAQeQv8GkWaP78MN/yrUfrHyRwi1lSbR6pXqRVrRBwhpxVZcw9kiGHx2Iumhs5eZuoeovic4PE9zn/3btidr64J/tF6dAOI/eRqQ/WiD8zowcV9iuHZT5cHsTrL1Z49u1BexOTtLWp7J+AYKwuLwivz3amDJNlWBjmctBgW0wCIXYq046ZCmd+Q8VXe/3EWBxfSUjA87S/yYRGW99R0dsm8UKQYZrtqE8yRFKibdJZsj6+VLyyT1qHWaueHJd+g5fR5+5/Fd7EzxDRhd8IPvDs/FoUylhLdxaKrzreM//u61uh/DoMZ8HXLDT5jhkawj/HKF09OX+zH1pzvwtWAKCh7+6iX/oqRwWIJoL63u8pTDRpAH8DoVPUUkcfF2SrVte4yZitLNP1uK2E9g3Qy5R18kVVmwzlDuKFhvhx8C1hmPVfmScmTD9ES0Kg==
  template:
    metadata:
      name: ghcr
      namespace: backend
    type: kubernetes.io/dockerconfigjson
