---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: valkey
  namespace: backend
spec:
  encryptedData:
    VALKEY_PASSWORD: AgAwLM7NYFeT5dbrD7cl1eFG3xURwdusvmcMuxuCWPM9mpI4qX+/InM5MP8P3ff4uNVp2tTlzt42uoAVazDbrvl+eg1b1b4qd9qHjmO0sllQaLFxPdEpgXz8q4m/Wos6n3sNyhMqiX32dm35EWtJ94DZDY3mwmhbEagc1IvoSjO1h7IXmCc+HLuqoIViuK9ITiT9MZ9iUH4de5QY/hqUJkQRjkmsnhFQTm77ydcEaY6uPcmIoMGOvUf3PK0aKPd6SjXYw7ZRAhWF+7yMO1kkfPqvnuULCm2olT7hPxE4S7UozNqzwRxOyXNMJrxHoOBrubyZJkVxHuPlru32nhb6ZxwQldC42P+D/6vL2eYM89ZC2YSEfahUGv+7rhg6yyRiEfRm6qd/skIlY6W5mWSSsQsvmFrXoDlovZU4wQ++UoHr013Og+W8yRGOgVXiKANnDuiJ5M2ZlLm57bUsdfo3DVYAihMgQj4gYP15qSxDaSA94H1Dr8fJQ+0k4OJ/+jUFaS2T1s51jRDWKruYzlw03CSUvG01KciDrxrGP8DO919UCIZ0Ea5raaBlLgi8+sbxa0/AL+bs6a3m387dz02wMhbv9s3WjxKRfMIHDJZ0ucgh8YeDKiXdScEXYBFo+idakQsN4Vq2DLJYjAKf77eV/ZW+cMKqGwYEvFZ3LtmmIuAjS2POKp2zcNpNBEMH6kQtAUUqiOOzgEeNstchLUo/HKikonRs/i5pNIM=
  template:
    metadata:
      name: valkey
      namespace: backend
