---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr
  namespace: flink
spec:
  encryptedData:
    .dockerconfigjson: AgBtoSfs4h7d9+N9UW5x/ksxoYIl6RULA0tVkfgaoKCeeWB3yg8SN8rthpH78RsmSuDu1qAylm5KdGHjyMTnhnXZfcXlbX1FXkRVLj0aHRoMdRUZVnBuLgNYfh/bMiCGzDj7AAT9S04PL8u2c+/xBJEdXDcug1tpPJWTcz+7CzfEst+12AJv0C5L1glCN4WEYM4/AkipWUPX7M30i3TzMiZPa8xKXDHpmfS2lGJzdW5Xeq7ZMqpUXiw5a/PeC70qLPrd3emrrvmp8p1EPlR3jvtu+Zaz/OxQ1B9xH/o3/RYf/uIv9vkhvPuymEKTdyAcjoB8+K5DdBcOEkb+Fsp0jxRNvFOCFu4qs3aP6isMDpkO5FOLEPd+y9VD0xELdKsh6dfz6UZFNY8MNuDY8bhbLFMJ7VxUT5kep7mqmydITENqj6OfnAgoedItmVVEVOyJt7Kh2rrMwTQYZC+qVxlBzFD0NNdMrKh+Zu9jM1gXzO0rCFzteAy5gAFhzFw9vlXwyG1Wfxtuj1LzeMlEHteUQ+hp0dL5CGqTDIPnxC3/SQqRXKwqq/mTujCOuhPJtXwYIsXKfX9bW/iJdXTzXHy+vZL8NyFebRb1oS7VWkKWTdKtnnXXCQtTvBNhHWdIgn5Gv6YHd+rdk0O9WdvYpcHrKAWSBKRm2gpK+tRfyE6E6dZyu7xypsDj4qnah/TrMTJV9uFjusquJtIHAI3aStgdJ+ejXP43tluT831z504hxpMJ4ujKZfBfruHKYlIMBGKSKq6aUkTR8SgxcK9sTYoeMitXRO4CdOyETewM0gZ1uddLAnPrIxS4YQErf/T4t92YVew9Ufab0+gbUkrKtcV+jhskBUY+6MT4YnKq6gxQbeIaYWBnawwX6MNEGvrz5K8hm220kMzVs/+ZYzLAw1e7W8zCHC8VuIDLtj4JGqfIcCs9d1h6vg==
  template:
    metadata:
      name: ghcr
      namespace: flink
    type: kubernetes.io/dockerconfigjson
