---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: default
spec:
  encryptedData:
    TUNNEL_TOKEN: AgBwXxBs4YsSS6iFAhu+GEz4+H5PyqSKxv9aMIKtuxnaJd/oVL8CWGrJlhv/hAp1bSmyIAdXP1UUmLyP4Yo/GEXbmDBXe61rq2TGvk2YfwWj7o4M+kaDI0LlxmyGQQ1BN645TMRZAOOs65uRO4TeKlgcpQg8/3+VWRWiE14ahsRNfTOOyAVlrX2hf0wzhpl5hVxnnoKqRGyJBysZ3KdRgUUu7SyKdoV5NEwUvUh+pTXseb8V5BJw7g4Xz/zVwOkGOdBLAciO05ppEs4woENUS2O0cngGhUcSnRsBslfRfsQh4ZiMAUDMiJBpzYirxctOtVrYd/9bAds+07ILxogFCD5Jkwy3lUmk0YpEGXUqimbJ3iiscNbygsREQn91xE+09zVa/mUGyr87zQz92FMGxyBdufLZTGP68DvQtt2Ty9gy8Lxj7d3dCJOUhZJzZNn591qsshKEPURmy77aRFiL/EExK0YfDPgA5R6OG7XLwjYIlUPakqJ3L0hYN6EpUHYnfZU3oPYeyd7d7MoHsKfTmmRqahiV676O3uegwUmC8Cl3hgI8un39r02WKVext0lkXu64ZajkQSpQa5atHGxoAZKbrFYKh3hKMGhuxFgXDvgCqeTeaYYt67JHn7ariGgTFt6AGpIVz6ttMt0dzcud4EeL1Le4zXctuIihSSKe+vEsmW/6PrPfc6un8KxEu9L5l8aYXA8e7mfd6ji/woE32lLhS7bM8GPDnGeIoWl6Zwlb9SHVVJW9uqUZR1ofvAX8zukXqsY+D76RHAyc6QWhVp6UmaAPg4LrVZ+ZsSljBFhDO8jrpC6rrm2txlpqrgr3zmUXSpzobA2V7ZYoX4d/8jL6vjXyaDv8Yy3jAzzTr/YhxQlwny0wYOyI9btIASADgLU1j84i57JdJRdZwHeWhd2tn6CLBe4xrUbUPfneBe5pNANjtco/fvXZ
  template:
    metadata:
      name: cloudflare
      namespace: default
