---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared
  namespace: default
spec:
  encryptedData:
    TUNNEL_TOKEN: AgBY84DQ7vXjEnuaTglJi15bByxNrXFsSAcFIMm9O6jk5jcYf/SDCQ6HaMKCyWMSQhwzBDhezT4sT3fIsWzypAGII6LLcZV4OsoFgvSXsVTDaKRjuSGj6s7JQLyDxV0bQQykayBSgj4lePy2a2qVIeraQU1a6PVARyZm+8PMgN68Vizh5boLh/ct8ERRJ/BqoKzQow3b3Zs4c727TMWcvBK4pcPY0caLMxA32KkKcZnuSaR3t8k0GkVrx5CptjlnfDY3d1t/nsWFWELpvG/M1uHJ+ST5GwbrgRS6DXfk9W95LhEy/hfCsBGHKmLX+6s4b6DD+SU8lt28CHmvjFBcHsHNqkwcHSAOOkxtX6Wym6imXGMvVdpQBP5a7GQXsqCqFygdwv0jXu1dgqXbil1+/LHIrbVE1MwtiLQGAHoovPivuiCvbrSHGrwOsQRy7vKKpaIbBQiz7H7/D+LWHK9asnK6uVPYozkmaV9A1KTQ26OQhMhJ82KfvnuCphD0VuzxCVgfuOJzELGWVRW07EQ3YObCsw61p48nrQ5nDmUubzBs62/ZzJmlC3GwUKMwqUTv9TreY0z4jFf3vjyXdojfrjLL8MzGlgmB/b4/YW1FgBl505nNNyRRCB6pv1zFFZRmYFE0Rk9apIh/jbkps2c0rmZRc4BEvOSk7gOkZSKi1PzrruTa97WTBGCv1lymsGx2N9qXf4tDT77EYSP94A8TcfaMdnMbBE6wnBSmTcudyWfWoLTttCO4FY5NrC+lw+Jm+bNPCwgbtCV8iBMdbwtmgZHxJRByKoN9bkTnqXuRfPhOsRBljM+xzuPiVcibU22VUtSC2WDHe/XwlqXqjLi6CI47Z6ef71LSB3znZb0eVsvYO5V3MVDXvjfb45Ot5sFEcsg5SDnwIh+1M6KjHKTBK5RU3Vps9gU5LdQcrVHNX/M1EEp1cu6JGzwv
  template:
    metadata:
      name: cloudflared
      namespace: default
