---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: valkey-user
  namespace: valkey-system
spec:
  encryptedData:
    lule: AgA3GhdGxPA08/2vfw8sv/jontUVzuvWYScaj+dRQ0vwr8j/Rjp7wPJiCYdOuqqr/vYmCJiQzBETo1MaUk6BdzSKQY1UyuLqw8jYoHfbWN0r0s/XIe42zCLpmDNz/lFKjFsH1o9H3TEosfrgnheXLW0cJ03FtEhBLAS7HqkfkCISEOQ43hrHNSjBsg4jbAZVFny/btEZ/uyme/vgeMf3x1Y5O977z3DCz9GhsThMyN4cFMHjsah/JsX3ouDi5BapHY4zs+HM80Uq++6ClTIk9s/KY+W2sYxBi+IqetbKmod9//XxBNMTLSgKq1sGlkqyquMJZriVgwnNx8Dkq29Uk2JrIhO//d1ZQIFql1S/Z3oz2px299nhtFElrLvs5ZQ28Ev6RF+iLfPiNH33xj+Bgd9SUUgKUps67F9Px1LiRI5ZIinM2WB1NJFV6idgf94ZfpFwNlslhwEaIhRA1QcAhMcoBgPzSvLr/V9ET6lggrg6sTMrgHemOomQYeS20jRAmI/BNlS3bnyXVSuuLySCTJW0aAcTSN1yg9DdxX9RTqTuGOarhGh8LstBNrbRSYeDICuVCnpKcp72bdg2JV5Ess3GC5wTGlBKiU1sMQXJP35U8Pa0GM3bS8yfLG1cch2W/K2UKaeOhmLRN1CxLvZr3MygW1UHjNGFBOLAjiKYxAsm09J6oPkd9B1dku/MvolOlI563eOJYQ30Ee6e6w==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: backend
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: backend
      name: valkey-user
      namespace: valkey-system
    type: Opaque
