---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql
  namespace: backend
spec:
  encryptedData:
    MYSQL_PASSWORD: AgA9rh3UCSjjzCQW1m1kyUa7duOijUM0ARF2+n+oKe4kBGFYaMuaG7HQ/AhVBeMSfYmPgZaaIE5q55vZbRn+t5ocL1I8i0QIu49iTAPoGLln+E1jpXxGzMQGBDiQRXRLTPwuC0An/WuCE6uDi8KYoFB6XH2zCfgej+KJrxcOvf2l0K35OkY66r4NsL7QuZEYC0s6e12Y90kddFF8IkdiUc4W31Ah8fb9t5XjVJZwXeQwd4Wkb9WGphn7ItnjW38g6yTuLXtCE+HM8/6fxwSaN3dQ7gRLf1HLre5iQFNo9hDtsEOlxBmoQF0HCGuQ1xjNazD5S+6J02Q4++slddPoyhTxsq5EfMtkESiSWwV6jN+5+lDGTTKqf+pM+0YKfEdwcPCuVIrK4gEIDqwrgCwdFgjXQm+NBRtvyegXlWMpYYqE+cW5Na1osw8UPAbbChlOL9chajNjrxckfCf4PUTDg95bYc0q7YRM/HMYJ5u9HbcjIvfRyq4vU7Fb2athcf4TZW/rNLFYfg0RoGpXZl8COQTMItbJ0M6ISx447vA5hNnWJ63RTm7xbVxxmb1z9pfnevAbY/VJYL6RvypMZhKUgNBCk5mGc+kLqCRke5Se7+GzrqMvlu/xXdAfu8G0WcDFc7ieca81rrIoiRIJqQ/gn1evRYZtGMUCmmAJdvR2xwjpWAic7h7n2iHJAZim2BllDMWuyAe05y20ig==
    MYSQL_USERNAME: AgAMwGW5kC75VxxjjA4CBVJjL6tHKP5GiKBRCBmGTDTc7j6n6Q9IrmxYFhS4bFewqX6UA5G4dvOdWkOjpsXrbazzXBiS7w8cJgPWCXQFx2OiPsDjJT1yt3tNLJGQxCXf3nGJpJQv+CKKevWxpAs2L/LLBKUiRC7BSqXYZP/jQ3WnpkCT4mHcR8nrESBq4gitDprhZ6Tj1D9IqKb/N5XEsMuoJYV8aU4Y1SPDC8ngu1nYJjQjhn5ymqGTZL4f7q3Y2f5nCpGsAMtqQBx6mIf8Z+fJHRYRwRge91Dq3fAphSqHxxC5Z3Ynz5/3u5V2qPdHNt7a6W5fhSyIZlI/wg/AMHtvrIpita2c7VSnuKjo4WjeV19Mkuv3r+9SfhCXj+nOITuAdNcROcZeTSbJN0jga7ENDmbIISDv2X9xXsyCQnoNIA4M8GNk2piyyqwfrW3h7Kx7b0HMRWC41iYG4gpN9AS+YPTPQT3ShanGigar1aiqxJbdl1Voh+rXCNk5xSmNBHu4nSl1xmLJJq2V4wjn4zdD6wT5SUM8E73wWwkdFmNsafoNXf7ZdwKG0FGZABOp7zVuXLVPeECYhDd/kUt7AIOskMs2SSRs5knoIe6UJGb6du+mBvZTpbDnIadgr4CYFH0ITpbASkBoC981mMVFBFHvO9IZnxDnlf5L6gabAH5ZMPu+FRNLKATWpoU5eF9iOa45BEn1
  template:
    metadata:
      name: mysql
      namespace: backend
    type: Opaque
