---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opensearch
  namespace: backend
spec:
  encryptedData:
    OPENSEARCH_PASSWORD: AgB/Qbv7ITHKsP+Jy7snt4eeT0G9ie7sw9kLcm6tm92ROQUcsrYBJspIsvFyfgZKG/8YVvp+fvHvacqjkbYknsU7gLvjUoLYXzCKx0GtZg7t/aGipTXVqS02zDU7vSOKi2KYfpaFAuUytXE5T4Aou+DajIxygewO/7HSjkMWCV5pBhVYcDb8nDpgMlu8McujGTNrfJslh5OZ4LkDNSnJLpr/XYNAI3n2PW7SMJKgXzexaCu8tiX15XK/biLG+rMbUAR+KKTFnadTosKUWxT80iPXFsgr2IAzztrDG0sGqRsACXdKj0IysRaa6bG1C0tdzKwtu3ru1pHJDuX0euB3qXzlePbQ8vmwudcVbVV+emOVyhi5H0wEd4bw+LK78d6uNlZvvJnEwADPzI2aZdy5MRhTkcRkuJ5P2dDwsESHy0X4LpIs9wIJPw8zpmpjueSGUJcfYIuZ+y6brdg5p5mm+Chdywv6+bTbYko7mQykBUZsh6Py5iXQu2M5vaz3QxSq4bTTe5BMpllAmukr0TlIKzU2ek47B9GcMlrb2CIC/Eh1K8P3gAJaiTKACx3AAumVLQ6eSiZqSz+0rYShIDYOV7Ss1abprAIWLBfNJSym64U6ltEG/6AOUgKcsRirXz9oT0LN3fx6pEOaKXk0MaBfej0es04+NhUITF5PB2jpjN9UbwbgcMyUJwjc3Wak/Ot23VSSfpZlVRVZi2jJccCAVxCZy5L4eSeqqi4=
  template:
    metadata:
      name: opensearch
      namespace: backend
