---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql
  namespace: backend
spec:
  encryptedData:
    MYSQL_PASSWORD: AgBB5yjDPa3QpSnnEqXqbzuN3LlNrjkVvEr7yLA2xym1XMfpxiavX0D7p3YVMqtPfJyCJ7bdAajGOiUMG3yV1YubOI+wGntZy4FFRIEOaztxa7DrBI12/1rqh0zhIlAHpZwRg8kKw8yzheuYM+jHDzNeWg46JpSj+ht9F44VgTjKrr8vtE2m10ekkwq/bpF/1DPwcuAwyIa1l2/7nnf+hvaPOtJSv2HJRmzTHWTR17L2aQePKlrhncNG1BWSKBHtUq/FAZiHGfKIqsGDt+cMXzf/wriYAll1urd4wtqdrQLOxiQUP6FOMfX2tM37Pe0D5gSq4I/lYjU6KdlqZ9Snf7Ce/sgDudO9mZOiZtCU85u/XSjZL03bvsu9Nm60FrIkrfmw1J4HShcd0KffSyPN3+z4P0fmLRvE37TKNI5/4/0aK9u89rtxyj4vLNbQp5HnTRjTkAcRR3vja7oZ5d729To8Y/LlJMdss7zMitq6GPoWTqFy0j2fCQxOZDcF3Mo2wD0wUEL8BefqyxrD2xalCGnqj/WKOV6FJqVlOGJDJNKwE7l3tlft72Ka2xwPFAMwVZGhhInSHitUzGUfiXf9QS6keSKz5bnqpESCJpgr0PDBW0mkUxU6Lm3Nxx2XZUbP/uiTbiIdE//+7zoHRuTTFewLo59WuI0OOnTm6Df9Vj9hg2PBL7ycvUbyBG7n0gT/Cu00gIXq
    MYSQL_USERNAME: AgCmuq4whWS7ga/IQnpk2o8qoh0MX3yjyCvxlUBw/n+Dl2OjXI+g+tkg19/edLUbL+5slitPnw1tHTO5CI/nEOMEuevbJ1UsQEtv7/+0BAKUqm5j/zs5cSczOH4QB44WSpg/7TX28XOEL8D4OpV2+YMc6ftd3A8Er3eELcWnm6LWeMLnXSCeM1+s3rSpoIpL641HUvTqk2ZIhjs8156DhlpMFb0XpO5oS94nY73kDv0qDqhyzSlsVx4Tlv+NjrYI+nNQgA+lJsmYBmZuIvC2NVBXpQhJCozDGCq7cP43AfcBCx19NiWg2jRPjtbcKKxHnUp5BXK4d2TBMdM487kCQiGVx17msgXQ6Xn6ypFK61JOPDWNhxm9J/gKnVtXACHTI6NMUcjGWauE7aO7kx4Js9veNnKcADTceCxbqSpou0ydHLG/fxKDHYo/lpqh0ZofdSV1KxNxS/sVV1zp9HDaS/QoIPJJOZoBUm/zO9a6h4czsyJD/Byi+nNkKDuJrRyjvgEZaZJ+DdA3GNB9uTOWhcZd5C769DPoVySsu3jMNEXUtF1o321cJ0NDNT3Nvlrsy0ZtGQVdytl6XDALfc8MYXGIoqOFscu0SQUAnepCIkzZHzgLx5ingEfVeNRoYUXkWcqrQ386zxuiYk3zDoBW+m8l0YPDfmSscgLgJ/CA1S0cmHZo0+t3W9KBdKYEgdMCuPfbm281Uc5yKA==
  template:
    metadata:
      name: mysql
      namespace: backend
    type: Opaque
