---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tidb
  namespace: backend
spec:
  encryptedData:
    TIDB_PASSWORD: AgAarmA791PIng34i9Tj9cqlG+HPOcqpP/tZD4O28RsmeR7wlPcuGB7GAE5FM8IKk/8WzEWrSHSQ43n/dBqsi2Yz2865rPBG9wYJgCJy4cw1qeyOKEXFt7DWE48K2I8xQWvcTW/USpobPgCl2KzPi6ofcJ3hVUx1UKr95kBsHl2WWGHMMF5gjC1ZBBnyph4f1c6DpgEZA9/qv8Yb8WvLNf5wROgLNqv9iRfTCTE1T99sUU7QdDrw3yw3XvgdXdn5/eEwbBblv3kywhYB7yw39ICZ0Zf2hPFaXPgsQOIV2gi1yUVgkgQmJiV2M0jLdVOGRVTfNlQoO70Cwr490IAfIpTv8R3nVRxRKegfj9O//p4gRnewKv4mQwQY0JuMBTVNqVyDkDKEZhwPBNGCW//a76uOpqAbK9uydlhRctaqVFRTXZ9Xx6V0gUYeHQ3LKAThlPwa3PpfZ1QnhM2heQMAVfbQylJdcbETUHBV7EaabvXLXqcUf8r4u/9Jm0DzKnOb7LkJvnKRJzWz6u8PqMuC0/uiO50/iv8SY0y76z3pHIeq+GKUTkd3v4bJY0P14QngqpW3jAnB0Elk96g1wdkra9Yt3oHTNXXyn3bEvBPHlqD5T5lvwE7NsweHNLqv8Ma2ckyFtdzuPKqQFxPgmGUP00vKeUjID9Li7SJph1TTf4V8pTe5D+dJG1n0q+ZaEbgiFxT3HD+XuQclDPUk97eFf70g
    TIDB_USERNAME: AgBSf7TUL0fnU6VKDs8HvpREwbPp0P14eTo0LdSDS9euH4849uXg131yJIUhoiCpT0PRqXZPbBSllX1DGxFMjXmYkDFjsYADDdq1U2n7JqPLFw+Ue0CerJys1e2qk93KSNxIcuo/eKJl0U49XHbj+NuS9hMirfmBUec77xFo6ziButhay3oCc7OixmKsArzoBbg+TZc4ZsAguNd3Q/SyIYSBj+KdCyZel8bnhn2GyOZ9SFkJluJE3aBxS435kdt9/0148dCOuB2hs4S3ruvgFUDKW6ERliSUGnj+l086mv1hLDwZQQniPY9UKlgXDSW4sY7Stn/CH4Yr6CUukGP0iwY+Q0KkamlVzFe6bLQSBBYfFGzWcMz5le7ZkZq5/XA+Dlkq1OVBavz7jtvWe4AS3MwD0ct0yf9lkawPsFk50dju5WEQnQI8x/pqu0QTmYsuIwx7QNwYvyceSfDQoYaGeAQJDrWmaEyP8hYiEHcFhcw9V+BqmGQpf6FxTkDTKuuVzi1T3Ai7xsKfXsE73hMPhFN1K/136IIwDSJeV8sMCmlzNUG2s+uex7f6aOc+Kyw0Q4W2hgkRQm7qCOC+qtNgl9VWl8ART7v+PdYqEQUKBMDMqRchBx6iqCtun/BxDezjCCSFvBg7EM93GYoK0uomqZuN9Ij4i8KDb4MqoZ0NS1rxD89uRvUr6fyBWAFSBdR2oWJZOZLoslju6fATYHw4I7aYsVLXyw==
  template:
    metadata:
      name: tidb
      namespace: backend
