---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: turn
  namespace: backend
spec:
  encryptedData:
    TURN_SECRET: AgACrAhOe+1kZAdsGj8ZYSUuHaQ51u8lrwZ66yhLEZnIQUbrwx/QurkHuSoeAi8OQcmi5QtyCRPV1z0vIB1QRECuO74RjEUoEYoOprwSbkq/1ch8SiXnlRyAk0UXzKmh2p+nqRnVcHP0AtzgDpdZKFECj93lhHcXmuwrsIbeqqvxNmkxOss5tDrYVr0TN647VNW0gmDhHa7zIoT02ciSCuXWAuSS91Tae/AxwjId4YcAt2GWbxdwS2tR+e2Eki/6fMyxEcAsB9z/drjxufl25F5yrJAqZ2+rgLiknzNkJbX3E2mm/ljesk+mswdARe4vPD1QzKRIStboOsp7lYh4tC06vQwcePcFf2MfEJo2sZz67aEF2zrU3hfMv3mNzcc45dAWY4KyAspJrUYbGSTnKw5OYNefSnOGAm1clqIG6n8wa3NAKv4Epvl6FnUF8i/SDL6F5cywCr+ZMWW09dcIyQ84mHxeQdr19l4+OHJnXrzcVn1f9b5qBtgOtC8x2Eu6RoKaWo76CmkWAvkIhx47Qq0YuDbJ8lS6l3X642F5KFtwfJQsKWz410SvFnxxLBOuSNm00yKlEik1kOWGhYsiZGtQ/cLf3Sn98lnSD10Xser7hgOyd+P02qt+bLNLu0xG4reIYKym34wu/qpyxpy1LAYqKKt+rov17ONhMKOqWNDOJl8YO2YgNqyLV+EtZFRWWJR9RtB4t2zrm2paOqjSYdosKUHLsUuiz44YaFXOctRN9uBGtXe0ZBOx6vC27eifFCqUnsSQexHkDm72QulP6rFy
  template:
    metadata:
      name: turn
      namespace: backend
