---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vitess-users
  namespace: vitess
spec:
  encryptedData:
    users.json: AgAx24BQrLi46NT0UvVHANLv07jiw/6cXCnhWwk6pFe5P+4rUNg+GGLjyUgJmDs1zcmIFRdonm/8fHQz2PlfErYggpUbezzL+lm147wUnRVXYzL773sMkZFoaJSR1DXMcZmUMD5ZEev71zMAAKA+iPvDBUUBkCzxlr7cO4BYLDgImN4/1JVIpmu2Jqgk6JAG21I/xWIQ6TMHaQ8TQKDXEVlIwAmJfYHqjSODbIixtLfnzSOGYyeGsx7WLX6nZbWWrMpebUNEnkaQpSKbvPlRCFq9QFoX8gueX/tRirTXl+8gL+LoU9/lYfFdeyipi7VaExm4PUOJx0/o20cdwycjhBYxsmX7FaTpABthuuC9+082eBnQVhRkiATcfEhIvxZRW0KxWrrBn+5xK2Co+3rm91zkUthcp5S8ZbET/BMEnijQymwy3BU9X52/ZZECiDS4iDmLpopd6AimErsl6+/JVPHJD/uOTNv3Kij9h6d8XUmbiR4WUdndmeZWoNVINJEqWfhJufuxeDTw5rfS8wVS3tTSeLVO+wlxgrhWGMjJnZhONcTQ1kP2nEd7Luo+JyTWYRjhQp7IgFwMC2ubO9IXRTAAnXUTkSGZb5hckJl2xy6XGLmL07IScPADbKPLB8iXCheRAOumwdWCldkSb+MSUDU8d8uHgkiKi7rkeY2RsG0DVsWryODRGo04kLsmOZ/ZuKxDy1Bk1GylxDnDXSmuUleP0pv53XwhbXelGoaXCCnvGpoIZg86SBkyk3Z9n+TFqwqgVKiPuGEhshk6K37NM3LrJKAd7uLy47TWM56WsMgwcLP64/x3DbY=
  template:
    metadata:
      name: vitess-users
      namespace: vitess
    type: Opaque
