// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGoogleAuthClient creates a new instance of MockGoogleAuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoogleAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoogleAuthClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGoogleAuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGoogleAuthClient is an autogenerated mock type for the GoogleAuthClient type
type MockGoogleAuthClient struct {
	mock.Mock
}

type MockGoogleAuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoogleAuthClient) EXPECT() *MockGoogleAuthClient_Expecter {
	return &MockGoogleAuthClient_Expecter{mock: &_m.Mock}
}

// Email provides a mock function for the type MockGoogleAuthClient
func (_mock *MockGoogleAuthClient) Email(ctx context.Context, idToken string) (string, error) {
	ret := _mock.Called(ctx, idToken)

	if len(ret) == 0 {
		panic("no return value specified for Email")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, idToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, idToken)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, idToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGoogleAuthClient_Email_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Email'
type MockGoogleAuthClient_Email_Call struct {
	*mock.Call
}

// Email is a helper method to define mock.On call
//   - ctx context.Context
//   - idToken string
func (_e *MockGoogleAuthClient_Expecter) Email(ctx any, idToken any) *MockGoogleAuthClient_Email_Call {
	return &MockGoogleAuthClient_Email_Call{Call: _e.mock.On("Email", ctx, idToken)}
}

func (_c *MockGoogleAuthClient_Email_Call) Run(run func(ctx context.Context, idToken string)) *MockGoogleAuthClient_Email_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGoogleAuthClient_Email_Call) Return(s string, err error) *MockGoogleAuthClient_Email_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGoogleAuthClient_Email_Call) RunAndReturn(run func(ctx context.Context, idToken string) (string, error)) *MockGoogleAuthClient_Email_Call {
	_c.Call.Return(run)
	return _c
}
