// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"backend/auth/internal/dto"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateMemberByEmail provides a mock function for the type MockService
func (_mock *MockService) CreateMemberByEmail(ctx context.Context, email string, password string) (map[string]uuid.UUID, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateMemberByEmail")
	}

	var r0 map[string]uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (map[string]uuid.UUID, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) map[string]uuid.UUID); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateMemberByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMemberByEmail'
type MockService_CreateMemberByEmail_Call struct {
	*mock.Call
}

// CreateMemberByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockService_Expecter) CreateMemberByEmail(ctx any, email any, password any) *MockService_CreateMemberByEmail_Call {
	return &MockService_CreateMemberByEmail_Call{Call: _e.mock.On("CreateMemberByEmail", ctx, email, password)}
}

func (_c *MockService_CreateMemberByEmail_Call) Run(run func(ctx context.Context, email string, password string)) *MockService_CreateMemberByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_CreateMemberByEmail_Call) Return(stringToUUID map[string]uuid.UUID, err error) *MockService_CreateMemberByEmail_Call {
	_c.Call.Return(stringToUUID, err)
	return _c
}

func (_c *MockService_CreateMemberByEmail_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (map[string]uuid.UUID, error)) *MockService_CreateMemberByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function for the type MockService
func (_mock *MockService) DeleteAccount(ctx context.Context, refreshToken string) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockService_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockService_Expecter) DeleteAccount(ctx any, refreshToken any) *MockService_DeleteAccount_Call {
	return &MockService_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, refreshToken)}
}

func (_c *MockService_DeleteAccount_Call) Run(run func(ctx context.Context, refreshToken string)) *MockService_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeleteAccount_Call) Return(err error) *MockService_DeleteAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteAccount_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) error) *MockService_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// ForgetPassword provides a mock function for the type MockService
func (_mock *MockService) ForgetPassword(ctx context.Context, email string) (map[string]uuid.UUID, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ForgetPassword")
	}

	var r0 map[string]uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]uuid.UUID, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]uuid.UUID); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ForgetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgetPassword'
type MockService_ForgetPassword_Call struct {
	*mock.Call
}

// ForgetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockService_Expecter) ForgetPassword(ctx any, email any) *MockService_ForgetPassword_Call {
	return &MockService_ForgetPassword_Call{Call: _e.mock.On("ForgetPassword", ctx, email)}
}

func (_c *MockService_ForgetPassword_Call) Run(run func(ctx context.Context, email string)) *MockService_ForgetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ForgetPassword_Call) Return(stringToUUID map[string]uuid.UUID, err error) *MockService_ForgetPassword_Call {
	_c.Call.Return(stringToUUID, err)
	return _c
}

func (_c *MockService_ForgetPassword_Call) RunAndReturn(run func(ctx context.Context, email string) (map[string]uuid.UUID, error)) *MockService_ForgetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateAccessToken provides a mock function for the type MockService
func (_mock *MockService) GenerateAccessToken(refreshToken string) (map[string]string, error) {
	ret := _mock.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (map[string]string, error)); ok {
		return returnFunc(refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) map[string]string); ok {
		r0 = returnFunc(refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockService_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - refreshToken string
func (_e *MockService_Expecter) GenerateAccessToken(refreshToken any) *MockService_GenerateAccessToken_Call {
	return &MockService_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", refreshToken)}
}

func (_c *MockService_GenerateAccessToken_Call) Run(run func(refreshToken string)) *MockService_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GenerateAccessToken_Call) Return(stringToString map[string]string, err error) *MockService_GenerateAccessToken_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockService_GenerateAccessToken_Call) RunAndReturn(run func(refreshToken string) (map[string]string, error)) *MockService_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// LoginWithEmail provides a mock function for the type MockService
func (_mock *MockService) LoginWithEmail(email string, password string) (*dto.LoginWithEmailResponse, string, error) {
	ret := _mock.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for LoginWithEmail")
	}

	var r0 *dto.LoginWithEmailResponse
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*dto.LoginWithEmailResponse, string, error)); ok {
		return returnFunc(email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *dto.LoginWithEmailResponse); ok {
		r0 = returnFunc(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LoginWithEmailResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = returnFunc(email, password)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = returnFunc(email, password)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_LoginWithEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginWithEmail'
type MockService_LoginWithEmail_Call struct {
	*mock.Call
}

// LoginWithEmail is a helper method to define mock.On call
//   - email string
//   - password string
func (_e *MockService_Expecter) LoginWithEmail(email any, password any) *MockService_LoginWithEmail_Call {
	return &MockService_LoginWithEmail_Call{Call: _e.mock.On("LoginWithEmail", email, password)}
}

func (_c *MockService_LoginWithEmail_Call) Run(run func(email string, password string)) *MockService_LoginWithEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_LoginWithEmail_Call) Return(loginWithEmailResponse *dto.LoginWithEmailResponse, s string, err error) *MockService_LoginWithEmail_Call {
	_c.Call.Return(loginWithEmailResponse, s, err)
	return _c
}

func (_c *MockService_LoginWithEmail_Call) RunAndReturn(run func(email string, password string) (*dto.LoginWithEmailResponse, string, error)) *MockService_LoginWithEmail_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveJTI provides a mock function for the type MockService
func (_mock *MockService) RemoveJTI(refreshToken string) error {
	ret := _mock.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RemoveJTI")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RemoveJTI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveJTI'
type MockService_RemoveJTI_Call struct {
	*mock.Call
}

// RemoveJTI is a helper method to define mock.On call
//   - refreshToken string
func (_e *MockService_Expecter) RemoveJTI(refreshToken any) *MockService_RemoveJTI_Call {
	return &MockService_RemoveJTI_Call{Call: _e.mock.On("RemoveJTI", refreshToken)}
}

func (_c *MockService_RemoveJTI_Call) Run(run func(refreshToken string)) *MockService_RemoveJTI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_RemoveJTI_Call) Return(err error) *MockService_RemoveJTI_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RemoveJTI_Call) RunAndReturn(run func(refreshToken string) error) *MockService_RemoveJTI_Call {
	_c.Call.Return(run)
	return _c
}

// SendSMSOTP provides a mock function for the type MockService
func (_mock *MockService) SendSMSOTP(sessionId uuid.UUID, phoneNumber string) (map[string]uuid.UUID, error) {
	ret := _mock.Called(sessionId, phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for SendSMSOTP")
	}

	var r0 map[string]uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, string) (map[string]uuid.UUID, error)); ok {
		return returnFunc(sessionId, phoneNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, string) map[string]uuid.UUID); ok {
		r0 = returnFunc(sessionId, phoneNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = returnFunc(sessionId, phoneNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SendSMSOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSMSOTP'
type MockService_SendSMSOTP_Call struct {
	*mock.Call
}

// SendSMSOTP is a helper method to define mock.On call
//   - sessionId uuid.UUID
//   - phoneNumber string
func (_e *MockService_Expecter) SendSMSOTP(sessionId any, phoneNumber any) *MockService_SendSMSOTP_Call {
	return &MockService_SendSMSOTP_Call{Call: _e.mock.On("SendSMSOTP", sessionId, phoneNumber)}
}

func (_c *MockService_SendSMSOTP_Call) Run(run func(sessionId uuid.UUID, phoneNumber string)) *MockService_SendSMSOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_SendSMSOTP_Call) Return(stringToUUID map[string]uuid.UUID, err error) *MockService_SendSMSOTP_Call {
	_c.Call.Return(stringToUUID, err)
	return _c
}

func (_c *MockService_SendSMSOTP_Call) RunAndReturn(run func(sessionId uuid.UUID, phoneNumber string) (map[string]uuid.UUID, error)) *MockService_SendSMSOTP_Call {
	_c.Call.Return(run)
	return _c
}

// SetNewPassword provides a mock function for the type MockService
func (_mock *MockService) SetNewPassword(ctx context.Context, password string, sessionId uuid.UUID) error {
	ret := _mock.Called(ctx, password, sessionId)

	if len(ret) == 0 {
		panic("no return value specified for SetNewPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, password, sessionId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SetNewPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNewPassword'
type MockService_SetNewPassword_Call struct {
	*mock.Call
}

// SetNewPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - password string
//   - sessionId uuid.UUID
func (_e *MockService_Expecter) SetNewPassword(ctx any, password any, sessionId any) *MockService_SetNewPassword_Call {
	return &MockService_SetNewPassword_Call{Call: _e.mock.On("SetNewPassword", ctx, password, sessionId)}
}

func (_c *MockService_SetNewPassword_Call) Run(run func(ctx context.Context, password string, sessionId uuid.UUID)) *MockService_SetNewPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SetNewPassword_Call) Return(err error) *MockService_SetNewPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SetNewPassword_Call) RunAndReturn(run func(ctx context.Context, password string, sessionId uuid.UUID) error) *MockService_SetNewPassword_Call {
	_c.Call.Return(run)
	return _c
}

// SignInWithApple provides a mock function for the type MockService
func (_mock *MockService) SignInWithApple(ctx context.Context, identityToken string) (*dto.SignInWithThirdPartyResponse, string, error) {
	ret := _mock.Called(ctx, identityToken)

	if len(ret) == 0 {
		panic("no return value specified for SignInWithApple")
	}

	var r0 *dto.SignInWithThirdPartyResponse
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.SignInWithThirdPartyResponse, string, error)); ok {
		return returnFunc(ctx, identityToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.SignInWithThirdPartyResponse); ok {
		r0 = returnFunc(ctx, identityToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SignInWithThirdPartyResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, identityToken)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, identityToken)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_SignInWithApple_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignInWithApple'
type MockService_SignInWithApple_Call struct {
	*mock.Call
}

// SignInWithApple is a helper method to define mock.On call
//   - ctx context.Context
//   - identityToken string
func (_e *MockService_Expecter) SignInWithApple(ctx any, identityToken any) *MockService_SignInWithApple_Call {
	return &MockService_SignInWithApple_Call{Call: _e.mock.On("SignInWithApple", ctx, identityToken)}
}

func (_c *MockService_SignInWithApple_Call) Run(run func(ctx context.Context, identityToken string)) *MockService_SignInWithApple_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_SignInWithApple_Call) Return(signInWithThirdPartyResponse *dto.SignInWithThirdPartyResponse, s string, err error) *MockService_SignInWithApple_Call {
	_c.Call.Return(signInWithThirdPartyResponse, s, err)
	return _c
}

func (_c *MockService_SignInWithApple_Call) RunAndReturn(run func(ctx context.Context, identityToken string) (*dto.SignInWithThirdPartyResponse, string, error)) *MockService_SignInWithApple_Call {
	_c.Call.Return(run)
	return _c
}

// SignInWithGoogle provides a mock function for the type MockService
func (_mock *MockService) SignInWithGoogle(ctx context.Context, token string) (*dto.SignInWithThirdPartyResponse, string, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for SignInWithGoogle")
	}

	var r0 *dto.SignInWithThirdPartyResponse
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.SignInWithThirdPartyResponse, string, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.SignInWithThirdPartyResponse); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SignInWithThirdPartyResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, token)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_SignInWithGoogle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignInWithGoogle'
type MockService_SignInWithGoogle_Call struct {
	*mock.Call
}

// SignInWithGoogle is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockService_Expecter) SignInWithGoogle(ctx any, token any) *MockService_SignInWithGoogle_Call {
	return &MockService_SignInWithGoogle_Call{Call: _e.mock.On("SignInWithGoogle", ctx, token)}
}

func (_c *MockService_SignInWithGoogle_Call) Run(run func(ctx context.Context, token string)) *MockService_SignInWithGoogle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_SignInWithGoogle_Call) Return(signInWithThirdPartyResponse *dto.SignInWithThirdPartyResponse, s string, err error) *MockService_SignInWithGoogle_Call {
	_c.Call.Return(signInWithThirdPartyResponse, s, err)
	return _c
}

func (_c *MockService_SignInWithGoogle_Call) RunAndReturn(run func(ctx context.Context, token string) (*dto.SignInWithThirdPartyResponse, string, error)) *MockService_SignInWithGoogle_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmailOTP provides a mock function for the type MockService
func (_mock *MockService) VerifyEmailOTP(otp string, verificationId uuid.UUID) (*dto.VerifyEmailOTPResponse, error) {
	ret := _mock.Called(otp, verificationId)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmailOTP")
	}

	var r0 *dto.VerifyEmailOTPResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, uuid.UUID) (*dto.VerifyEmailOTPResponse, error)); ok {
		return returnFunc(otp, verificationId)
	}
	if returnFunc, ok := ret.Get(0).(func(string, uuid.UUID) *dto.VerifyEmailOTPResponse); ok {
		r0 = returnFunc(otp, verificationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.VerifyEmailOTPResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, uuid.UUID) error); ok {
		r1 = returnFunc(otp, verificationId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_VerifyEmailOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmailOTP'
type MockService_VerifyEmailOTP_Call struct {
	*mock.Call
}

// VerifyEmailOTP is a helper method to define mock.On call
//   - otp string
//   - verificationId uuid.UUID
func (_e *MockService_Expecter) VerifyEmailOTP(otp any, verificationId any) *MockService_VerifyEmailOTP_Call {
	return &MockService_VerifyEmailOTP_Call{Call: _e.mock.On("VerifyEmailOTP", otp, verificationId)}
}

func (_c *MockService_VerifyEmailOTP_Call) Run(run func(otp string, verificationId uuid.UUID)) *MockService_VerifyEmailOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_VerifyEmailOTP_Call) Return(verifyEmailOTPResponse *dto.VerifyEmailOTPResponse, err error) *MockService_VerifyEmailOTP_Call {
	_c.Call.Return(verifyEmailOTPResponse, err)
	return _c
}

func (_c *MockService_VerifyEmailOTP_Call) RunAndReturn(run func(otp string, verificationId uuid.UUID) (*dto.VerifyEmailOTPResponse, error)) *MockService_VerifyEmailOTP_Call {
	_c.Call.Return(run)
	return _c
}

// VerifySMSOTP provides a mock function for the type MockService
func (_mock *MockService) VerifySMSOTP(sessionId uuid.UUID, verificationId uuid.UUID, otp string) (*dto.VerifySMSOTPResponse, string, error) {
	ret := _mock.Called(sessionId, verificationId, otp)

	if len(ret) == 0 {
		panic("no return value specified for VerifySMSOTP")
	}

	var r0 *dto.VerifySMSOTPResponse
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, string) (*dto.VerifySMSOTPResponse, string, error)); ok {
		return returnFunc(sessionId, verificationId, otp)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, string) *dto.VerifySMSOTPResponse); ok {
		r0 = returnFunc(sessionId, verificationId, otp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.VerifySMSOTPResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID, string) string); ok {
		r1 = returnFunc(sessionId, verificationId, otp)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(uuid.UUID, uuid.UUID, string) error); ok {
		r2 = returnFunc(sessionId, verificationId, otp)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_VerifySMSOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifySMSOTP'
type MockService_VerifySMSOTP_Call struct {
	*mock.Call
}

// VerifySMSOTP is a helper method to define mock.On call
//   - sessionId uuid.UUID
//   - verificationId uuid.UUID
//   - otp string
func (_e *MockService_Expecter) VerifySMSOTP(sessionId any, verificationId any, otp any) *MockService_VerifySMSOTP_Call {
	return &MockService_VerifySMSOTP_Call{Call: _e.mock.On("VerifySMSOTP", sessionId, verificationId, otp)}
}

func (_c *MockService_VerifySMSOTP_Call) Run(run func(sessionId uuid.UUID, verificationId uuid.UUID, otp string)) *MockService_VerifySMSOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_VerifySMSOTP_Call) Return(verifySMSOTPResponse *dto.VerifySMSOTPResponse, s string, err error) *MockService_VerifySMSOTP_Call {
	_c.Call.Return(verifySMSOTPResponse, s, err)
	return _c
}

func (_c *MockService_VerifySMSOTP_Call) RunAndReturn(run func(sessionId uuid.UUID, verificationId uuid.UUID, otp string) (*dto.VerifySMSOTPResponse, string, error)) *MockService_VerifySMSOTP_Call {
	_c.Call.Return(run)
	return _c
}
