// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSMTPClient creates a new instance of MockSMTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSMTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSMTPClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSMTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSMTPClient is an autogenerated mock type for the SMTPClient type
type MockSMTPClient struct {
	mock.Mock
}

type MockSMTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSMTPClient) EXPECT() *MockSMTPClient_Expecter {
	return &MockSMTPClient_Expecter{mock: &_m.Mock}
}

// SendOTP provides a mock function for the type MockSMTPClient
func (_mock *MockSMTPClient) SendOTP(to string, otp string) error {
	ret := _mock.Called(to, otp)

	if len(ret) == 0 {
		panic("no return value specified for SendOTP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(to, otp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSMTPClient_SendOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOTP'
type MockSMTPClient_SendOTP_Call struct {
	*mock.Call
}

// SendOTP is a helper method to define mock.On call
//   - to string
//   - otp string
func (_e *MockSMTPClient_Expecter) SendOTP(to any, otp any) *MockSMTPClient_SendOTP_Call {
	return &MockSMTPClient_SendOTP_Call{Call: _e.mock.On("SendOTP", to, otp)}
}

func (_c *MockSMTPClient_SendOTP_Call) Run(run func(to string, otp string)) *MockSMTPClient_SendOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSMTPClient_SendOTP_Call) Return(err error) *MockSMTPClient_SendOTP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSMTPClient_SendOTP_Call) RunAndReturn(run func(to string, otp string) error) *MockSMTPClient_SendOTP_Call {
	_c.Call.Return(run)
	return _c
}
