// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"context"

	"github.com/apache/cassandra-gocql-driver/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CheckNonce provides a mock function for the type MockRepository
func (_mock *MockRepository) CheckNonce(nonce string) (bool, error) {
	ret := _mock.Called(nonce)

	if len(ret) == 0 {
		panic("no return value specified for CheckNonce")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(nonce)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(nonce)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(nonce)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CheckNonce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckNonce'
type MockRepository_CheckNonce_Call struct {
	*mock.Call
}

// CheckNonce is a helper method to define mock.On call
//   - nonce string
func (_e *MockRepository_Expecter) CheckNonce(nonce any) *MockRepository_CheckNonce_Call {
	return &MockRepository_CheckNonce_Call{Call: _e.mock.On("CheckNonce", nonce)}
}

func (_c *MockRepository_CheckNonce_Call) Run(run func(nonce string)) *MockRepository_CheckNonce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_CheckNonce_Call) Return(b bool, err error) *MockRepository_CheckNonce_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_CheckNonce_Call) RunAndReturn(run func(nonce string) (bool, error)) *MockRepository_CheckNonce_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteAccount(ctx context.Context, id gocql.UUID, email string, phoneNumber string) error {
	ret := _mock.Called(ctx, id, email, phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID, string, string) error); ok {
		r0 = returnFunc(ctx, id, email, phoneNumber)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockRepository_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id gocql.UUID
//   - email string
//   - phoneNumber string
func (_e *MockRepository_Expecter) DeleteAccount(ctx any, id any, email any, phoneNumber any) *MockRepository_DeleteAccount_Call {
	return &MockRepository_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, id, email, phoneNumber)}
}

func (_c *MockRepository_DeleteAccount_Call) Run(run func(ctx context.Context, id gocql.UUID, email string, phoneNumber string)) *MockRepository_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteAccount_Call) Return(err error) *MockRepository_DeleteAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteAccount_Call) RunAndReturn(run func(ctx context.Context, id gocql.UUID, email string, phoneNumber string) error) *MockRepository_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// FindEmailAndOTPByVerificationId provides a mock function for the type MockRepository
func (_mock *MockRepository) FindEmailAndOTPByVerificationId(verificationId gocql.UUID) (string, string, error) {
	ret := _mock.Called(verificationId)

	if len(ret) == 0 {
		panic("no return value specified for FindEmailAndOTPByVerificationId")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID) (string, string, error)); ok {
		return returnFunc(verificationId)
	}
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID) string); ok {
		r0 = returnFunc(verificationId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(gocql.UUID) string); ok {
		r1 = returnFunc(verificationId)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(gocql.UUID) error); ok {
		r2 = returnFunc(verificationId)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_FindEmailAndOTPByVerificationId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindEmailAndOTPByVerificationId'
type MockRepository_FindEmailAndOTPByVerificationId_Call struct {
	*mock.Call
}

// FindEmailAndOTPByVerificationId is a helper method to define mock.On call
//   - verificationId gocql.UUID
func (_e *MockRepository_Expecter) FindEmailAndOTPByVerificationId(verificationId any) *MockRepository_FindEmailAndOTPByVerificationId_Call {
	return &MockRepository_FindEmailAndOTPByVerificationId_Call{Call: _e.mock.On("FindEmailAndOTPByVerificationId", verificationId)}
}

func (_c *MockRepository_FindEmailAndOTPByVerificationId_Call) Run(run func(verificationId gocql.UUID)) *MockRepository_FindEmailAndOTPByVerificationId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocql.UUID
		if args[0] != nil {
			arg0 = args[0].(gocql.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_FindEmailAndOTPByVerificationId_Call) Return(email string, otp string, err error) *MockRepository_FindEmailAndOTPByVerificationId_Call {
	_c.Call.Return(email, otp, err)
	return _c
}

func (_c *MockRepository_FindEmailAndOTPByVerificationId_Call) RunAndReturn(run func(verificationId gocql.UUID) (string, string, error)) *MockRepository_FindEmailAndOTPByVerificationId_Call {
	_c.Call.Return(run)
	return _c
}

// FindEmailAndPhoneNumberById provides a mock function for the type MockRepository
func (_mock *MockRepository) FindEmailAndPhoneNumberById(ctx context.Context, id gocql.UUID) (string, string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindEmailAndPhoneNumberById")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID) (string, string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gocql.UUID) string); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, gocql.UUID) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_FindEmailAndPhoneNumberById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindEmailAndPhoneNumberById'
type MockRepository_FindEmailAndPhoneNumberById_Call struct {
	*mock.Call
}

// FindEmailAndPhoneNumberById is a helper method to define mock.On call
//   - ctx context.Context
//   - id gocql.UUID
func (_e *MockRepository_Expecter) FindEmailAndPhoneNumberById(ctx any, id any) *MockRepository_FindEmailAndPhoneNumberById_Call {
	return &MockRepository_FindEmailAndPhoneNumberById_Call{Call: _e.mock.On("FindEmailAndPhoneNumberById", ctx, id)}
}

func (_c *MockRepository_FindEmailAndPhoneNumberById_Call) Run(run func(ctx context.Context, id gocql.UUID)) *MockRepository_FindEmailAndPhoneNumberById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindEmailAndPhoneNumberById_Call) Return(email string, phoneNumber string, err error) *MockRepository_FindEmailAndPhoneNumberById_Call {
	_c.Call.Return(email, phoneNumber, err)
	return _c
}

func (_c *MockRepository_FindEmailAndPhoneNumberById_Call) RunAndReturn(run func(ctx context.Context, id gocql.UUID) (string, string, error)) *MockRepository_FindEmailAndPhoneNumberById_Call {
	_c.Call.Return(run)
	return _c
}

// FindEmailByPhoneNumber provides a mock function for the type MockRepository
func (_mock *MockRepository) FindEmailByPhoneNumber(phoneNumber string) (string, error) {
	ret := _mock.Called(phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for FindEmailByPhoneNumber")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(phoneNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(phoneNumber)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(phoneNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindEmailByPhoneNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindEmailByPhoneNumber'
type MockRepository_FindEmailByPhoneNumber_Call struct {
	*mock.Call
}

// FindEmailByPhoneNumber is a helper method to define mock.On call
//   - phoneNumber string
func (_e *MockRepository_Expecter) FindEmailByPhoneNumber(phoneNumber any) *MockRepository_FindEmailByPhoneNumber_Call {
	return &MockRepository_FindEmailByPhoneNumber_Call{Call: _e.mock.On("FindEmailByPhoneNumber", phoneNumber)}
}

func (_c *MockRepository_FindEmailByPhoneNumber_Call) Run(run func(phoneNumber string)) *MockRepository_FindEmailByPhoneNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_FindEmailByPhoneNumber_Call) Return(email string, err error) *MockRepository_FindEmailByPhoneNumber_Call {
	_c.Call.Return(email, err)
	return _c
}

func (_c *MockRepository_FindEmailByPhoneNumber_Call) RunAndReturn(run func(phoneNumber string) (string, error)) *MockRepository_FindEmailByPhoneNumber_Call {
	_c.Call.Return(run)
	return _c
}

// FindEmailBySessionId provides a mock function for the type MockRepository
func (_mock *MockRepository) FindEmailBySessionId(sessionId gocql.UUID) (string, error) {
	ret := _mock.Called(sessionId)

	if len(ret) == 0 {
		panic("no return value specified for FindEmailBySessionId")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID) (string, error)); ok {
		return returnFunc(sessionId)
	}
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID) string); ok {
		r0 = returnFunc(sessionId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(gocql.UUID) error); ok {
		r1 = returnFunc(sessionId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindEmailBySessionId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindEmailBySessionId'
type MockRepository_FindEmailBySessionId_Call struct {
	*mock.Call
}

// FindEmailBySessionId is a helper method to define mock.On call
//   - sessionId gocql.UUID
func (_e *MockRepository_Expecter) FindEmailBySessionId(sessionId any) *MockRepository_FindEmailBySessionId_Call {
	return &MockRepository_FindEmailBySessionId_Call{Call: _e.mock.On("FindEmailBySessionId", sessionId)}
}

func (_c *MockRepository_FindEmailBySessionId_Call) Run(run func(sessionId gocql.UUID)) *MockRepository_FindEmailBySessionId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocql.UUID
		if args[0] != nil {
			arg0 = args[0].(gocql.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_FindEmailBySessionId_Call) Return(email string, err error) *MockRepository_FindEmailBySessionId_Call {
	_c.Call.Return(email, err)
	return _c
}

func (_c *MockRepository_FindEmailBySessionId_Call) RunAndReturn(run func(sessionId gocql.UUID) (string, error)) *MockRepository_FindEmailBySessionId_Call {
	_c.Call.Return(run)
	return _c
}

// FindIdByPhoneNumber provides a mock function for the type MockRepository
func (_mock *MockRepository) FindIdByPhoneNumber(phoneNumber string) (gocql.UUID, error) {
	ret := _mock.Called(phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for FindIdByPhoneNumber")
	}

	var r0 gocql.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (gocql.UUID, error)); ok {
		return returnFunc(phoneNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(string) gocql.UUID); ok {
		r0 = returnFunc(phoneNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocql.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(phoneNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindIdByPhoneNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIdByPhoneNumber'
type MockRepository_FindIdByPhoneNumber_Call struct {
	*mock.Call
}

// FindIdByPhoneNumber is a helper method to define mock.On call
//   - phoneNumber string
func (_e *MockRepository_Expecter) FindIdByPhoneNumber(phoneNumber any) *MockRepository_FindIdByPhoneNumber_Call {
	return &MockRepository_FindIdByPhoneNumber_Call{Call: _e.mock.On("FindIdByPhoneNumber", phoneNumber)}
}

func (_c *MockRepository_FindIdByPhoneNumber_Call) Run(run func(phoneNumber string)) *MockRepository_FindIdByPhoneNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_FindIdByPhoneNumber_Call) Return(id gocql.UUID, err error) *MockRepository_FindIdByPhoneNumber_Call {
	_c.Call.Return(id, err)
	return _c
}

func (_c *MockRepository_FindIdByPhoneNumber_Call) RunAndReturn(run func(phoneNumber string) (gocql.UUID, error)) *MockRepository_FindIdByPhoneNumber_Call {
	_c.Call.Return(run)
	return _c
}

// FindLoginInfoByEmail provides a mock function for the type MockRepository
func (_mock *MockRepository) FindLoginInfoByEmail(email string) (bool, bool, gocql.UUID, string, string, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindLoginInfoByEmail")
	}

	var r0 bool
	var r1 bool
	var r2 gocql.UUID
	var r3 string
	var r4 string
	var r5 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, bool, gocql.UUID, string, string, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(string) gocql.UUID); ok {
		r2 = returnFunc(email)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(gocql.UUID)
		}
	}
	if returnFunc, ok := ret.Get(3).(func(string) string); ok {
		r3 = returnFunc(email)
	} else {
		r3 = ret.Get(3).(string)
	}
	if returnFunc, ok := ret.Get(4).(func(string) string); ok {
		r4 = returnFunc(email)
	} else {
		r4 = ret.Get(4).(string)
	}
	if returnFunc, ok := ret.Get(5).(func(string) error); ok {
		r5 = returnFunc(email)
	} else {
		r5 = ret.Error(5)
	}
	return r0, r1, r2, r3, r4, r5
}

// MockRepository_FindLoginInfoByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLoginInfoByEmail'
type MockRepository_FindLoginInfoByEmail_Call struct {
	*mock.Call
}

// FindLoginInfoByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockRepository_Expecter) FindLoginInfoByEmail(email any) *MockRepository_FindLoginInfoByEmail_Call {
	return &MockRepository_FindLoginInfoByEmail_Call{Call: _e.mock.On("FindLoginInfoByEmail", email)}
}

func (_c *MockRepository_FindLoginInfoByEmail_Call) Run(run func(email string)) *MockRepository_FindLoginInfoByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_FindLoginInfoByEmail_Call) Return(emailVerified bool, phoneNumberVerified bool, id gocql.UUID, password string, role string, err error) *MockRepository_FindLoginInfoByEmail_Call {
	_c.Call.Return(emailVerified, phoneNumberVerified, id, password, role, err)
	return _c
}

func (_c *MockRepository_FindLoginInfoByEmail_Call) RunAndReturn(run func(email string) (bool, bool, gocql.UUID, string, string, error)) *MockRepository_FindLoginInfoByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindPhoneNumberByVerificationId provides a mock function for the type MockRepository
func (_mock *MockRepository) FindPhoneNumberByVerificationId(verificationId gocql.UUID) (string, error) {
	ret := _mock.Called(verificationId)

	if len(ret) == 0 {
		panic("no return value specified for FindPhoneNumberByVerificationId")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID) (string, error)); ok {
		return returnFunc(verificationId)
	}
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID) string); ok {
		r0 = returnFunc(verificationId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(gocql.UUID) error); ok {
		r1 = returnFunc(verificationId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindPhoneNumberByVerificationId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPhoneNumberByVerificationId'
type MockRepository_FindPhoneNumberByVerificationId_Call struct {
	*mock.Call
}

// FindPhoneNumberByVerificationId is a helper method to define mock.On call
//   - verificationId gocql.UUID
func (_e *MockRepository_Expecter) FindPhoneNumberByVerificationId(verificationId any) *MockRepository_FindPhoneNumberByVerificationId_Call {
	return &MockRepository_FindPhoneNumberByVerificationId_Call{Call: _e.mock.On("FindPhoneNumberByVerificationId", verificationId)}
}

func (_c *MockRepository_FindPhoneNumberByVerificationId_Call) Run(run func(verificationId gocql.UUID)) *MockRepository_FindPhoneNumberByVerificationId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocql.UUID
		if args[0] != nil {
			arg0 = args[0].(gocql.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_FindPhoneNumberByVerificationId_Call) Return(phoneNumber string, err error) *MockRepository_FindPhoneNumberByVerificationId_Call {
	_c.Call.Return(phoneNumber, err)
	return _c
}

func (_c *MockRepository_FindPhoneNumberByVerificationId_Call) RunAndReturn(run func(verificationId gocql.UUID) (string, error)) *MockRepository_FindPhoneNumberByVerificationId_Call {
	_c.Call.Return(run)
	return _c
}

// FindRefreshTokenJTIsById provides a mock function for the type MockRepository
func (_mock *MockRepository) FindRefreshTokenJTIsById(id gocql.UUID) ([]gocql.UUID, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindRefreshTokenJTIsById")
	}

	var r0 []gocql.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID) ([]gocql.UUID, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID) []gocql.UUID); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gocql.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocql.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindRefreshTokenJTIsById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRefreshTokenJTIsById'
type MockRepository_FindRefreshTokenJTIsById_Call struct {
	*mock.Call
}

// FindRefreshTokenJTIsById is a helper method to define mock.On call
//   - id gocql.UUID
func (_e *MockRepository_Expecter) FindRefreshTokenJTIsById(id any) *MockRepository_FindRefreshTokenJTIsById_Call {
	return &MockRepository_FindRefreshTokenJTIsById_Call{Call: _e.mock.On("FindRefreshTokenJTIsById", id)}
}

func (_c *MockRepository_FindRefreshTokenJTIsById_Call) Run(run func(id gocql.UUID)) *MockRepository_FindRefreshTokenJTIsById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocql.UUID
		if args[0] != nil {
			arg0 = args[0].(gocql.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_FindRefreshTokenJTIsById_Call) Return(jtis []gocql.UUID, err error) *MockRepository_FindRefreshTokenJTIsById_Call {
	_c.Call.Return(jtis, err)
	return _c
}

func (_c *MockRepository_FindRefreshTokenJTIsById_Call) RunAndReturn(run func(id gocql.UUID) ([]gocql.UUID, error)) *MockRepository_FindRefreshTokenJTIsById_Call {
	_c.Call.Return(run)
	return _c
}

// LinkAndMarkVerifiedPhoneNumber provides a mock function for the type MockRepository
func (_mock *MockRepository) LinkAndMarkVerifiedPhoneNumber(id gocql.UUID, email string, phoneNumber string, role string) error {
	ret := _mock.Called(id, email, phoneNumber, role)

	if len(ret) == 0 {
		panic("no return value specified for LinkAndMarkVerifiedPhoneNumber")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID, string, string, string) error); ok {
		r0 = returnFunc(id, email, phoneNumber, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_LinkAndMarkVerifiedPhoneNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkAndMarkVerifiedPhoneNumber'
type MockRepository_LinkAndMarkVerifiedPhoneNumber_Call struct {
	*mock.Call
}

// LinkAndMarkVerifiedPhoneNumber is a helper method to define mock.On call
//   - id gocql.UUID
//   - email string
//   - phoneNumber string
//   - role string
func (_e *MockRepository_Expecter) LinkAndMarkVerifiedPhoneNumber(id any, email any, phoneNumber any, role any) *MockRepository_LinkAndMarkVerifiedPhoneNumber_Call {
	return &MockRepository_LinkAndMarkVerifiedPhoneNumber_Call{Call: _e.mock.On("LinkAndMarkVerifiedPhoneNumber", id, email, phoneNumber, role)}
}

func (_c *MockRepository_LinkAndMarkVerifiedPhoneNumber_Call) Run(run func(id gocql.UUID, email string, phoneNumber string, role string)) *MockRepository_LinkAndMarkVerifiedPhoneNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocql.UUID
		if args[0] != nil {
			arg0 = args[0].(gocql.UUID)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_LinkAndMarkVerifiedPhoneNumber_Call) Return(err error) *MockRepository_LinkAndMarkVerifiedPhoneNumber_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_LinkAndMarkVerifiedPhoneNumber_Call) RunAndReturn(run func(id gocql.UUID, email string, phoneNumber string, role string) error) *MockRepository_LinkAndMarkVerifiedPhoneNumber_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEmailVerified provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkEmailVerified(email string) error {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for MarkEmailVerified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkEmailVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEmailVerified'
type MockRepository_MarkEmailVerified_Call struct {
	*mock.Call
}

// MarkEmailVerified is a helper method to define mock.On call
//   - email string
func (_e *MockRepository_Expecter) MarkEmailVerified(email any) *MockRepository_MarkEmailVerified_Call {
	return &MockRepository_MarkEmailVerified_Call{Call: _e.mock.On("MarkEmailVerified", email)}
}

func (_c *MockRepository_MarkEmailVerified_Call) Run(run func(email string)) *MockRepository_MarkEmailVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_MarkEmailVerified_Call) Return(err error) *MockRepository_MarkEmailVerified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkEmailVerified_Call) RunAndReturn(run func(email string) error) *MockRepository_MarkEmailVerified_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveRefreshTokenJTIById provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveRefreshTokenJTIById(id gocql.UUID, jti gocql.UUID) error {
	ret := _mock.Called(id, jti)

	if len(ret) == 0 {
		panic("no return value specified for RemoveRefreshTokenJTIById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID, gocql.UUID) error); ok {
		r0 = returnFunc(id, jti)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RemoveRefreshTokenJTIById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRefreshTokenJTIById'
type MockRepository_RemoveRefreshTokenJTIById_Call struct {
	*mock.Call
}

// RemoveRefreshTokenJTIById is a helper method to define mock.On call
//   - id gocql.UUID
//   - jti gocql.UUID
func (_e *MockRepository_Expecter) RemoveRefreshTokenJTIById(id any, jti any) *MockRepository_RemoveRefreshTokenJTIById_Call {
	return &MockRepository_RemoveRefreshTokenJTIById_Call{Call: _e.mock.On("RemoveRefreshTokenJTIById", id, jti)}
}

func (_c *MockRepository_RemoveRefreshTokenJTIById_Call) Run(run func(id gocql.UUID, jti gocql.UUID)) *MockRepository_RemoveRefreshTokenJTIById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocql.UUID
		if args[0] != nil {
			arg0 = args[0].(gocql.UUID)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_RemoveRefreshTokenJTIById_Call) Return(err error) *MockRepository_RemoveRefreshTokenJTIById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RemoveRefreshTokenJTIById_Call) RunAndReturn(run func(id gocql.UUID, jti gocql.UUID) error) *MockRepository_RemoveRefreshTokenJTIById_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceAndLinkMemberWithOldAccount provides a mock function for the type MockRepository
func (_mock *MockRepository) ReplaceAndLinkMemberWithOldAccount(newId gocql.UUID, oldAccountId gocql.UUID, email string, phoneNumber string) error {
	ret := _mock.Called(newId, oldAccountId, email, phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceAndLinkMemberWithOldAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID, gocql.UUID, string, string) error); ok {
		r0 = returnFunc(newId, oldAccountId, email, phoneNumber)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ReplaceAndLinkMemberWithOldAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceAndLinkMemberWithOldAccount'
type MockRepository_ReplaceAndLinkMemberWithOldAccount_Call struct {
	*mock.Call
}

// ReplaceAndLinkMemberWithOldAccount is a helper method to define mock.On call
//   - newId gocql.UUID
//   - oldAccountId gocql.UUID
//   - email string
//   - phoneNumber string
func (_e *MockRepository_Expecter) ReplaceAndLinkMemberWithOldAccount(newId any, oldAccountId any, email any, phoneNumber any) *MockRepository_ReplaceAndLinkMemberWithOldAccount_Call {
	return &MockRepository_ReplaceAndLinkMemberWithOldAccount_Call{Call: _e.mock.On("ReplaceAndLinkMemberWithOldAccount", newId, oldAccountId, email, phoneNumber)}
}

func (_c *MockRepository_ReplaceAndLinkMemberWithOldAccount_Call) Run(run func(newId gocql.UUID, oldAccountId gocql.UUID, email string, phoneNumber string)) *MockRepository_ReplaceAndLinkMemberWithOldAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocql.UUID
		if args[0] != nil {
			arg0 = args[0].(gocql.UUID)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_ReplaceAndLinkMemberWithOldAccount_Call) Return(err error) *MockRepository_ReplaceAndLinkMemberWithOldAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ReplaceAndLinkMemberWithOldAccount_Call) RunAndReturn(run func(newId gocql.UUID, oldAccountId gocql.UUID, email string, phoneNumber string) error) *MockRepository_ReplaceAndLinkMemberWithOldAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEmailAndOtpByVerificationId provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveEmailAndOtpByVerificationId(verificationId gocql.UUID, email string, otp string) error {
	ret := _mock.Called(verificationId, email, otp)

	if len(ret) == 0 {
		panic("no return value specified for SaveEmailAndOtpByVerificationId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID, string, string) error); ok {
		r0 = returnFunc(verificationId, email, otp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveEmailAndOtpByVerificationId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEmailAndOtpByVerificationId'
type MockRepository_SaveEmailAndOtpByVerificationId_Call struct {
	*mock.Call
}

// SaveEmailAndOtpByVerificationId is a helper method to define mock.On call
//   - verificationId gocql.UUID
//   - email string
//   - otp string
func (_e *MockRepository_Expecter) SaveEmailAndOtpByVerificationId(verificationId any, email any, otp any) *MockRepository_SaveEmailAndOtpByVerificationId_Call {
	return &MockRepository_SaveEmailAndOtpByVerificationId_Call{Call: _e.mock.On("SaveEmailAndOtpByVerificationId", verificationId, email, otp)}
}

func (_c *MockRepository_SaveEmailAndOtpByVerificationId_Call) Run(run func(verificationId gocql.UUID, email string, otp string)) *MockRepository_SaveEmailAndOtpByVerificationId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocql.UUID
		if args[0] != nil {
			arg0 = args[0].(gocql.UUID)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SaveEmailAndOtpByVerificationId_Call) Return(err error) *MockRepository_SaveEmailAndOtpByVerificationId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveEmailAndOtpByVerificationId_Call) RunAndReturn(run func(verificationId gocql.UUID, email string, otp string) error) *MockRepository_SaveEmailAndOtpByVerificationId_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEmailBySessionId provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveEmailBySessionId(sessionId gocql.UUID, email string) error {
	ret := _mock.Called(sessionId, email)

	if len(ret) == 0 {
		panic("no return value specified for SaveEmailBySessionId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID, string) error); ok {
		r0 = returnFunc(sessionId, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveEmailBySessionId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEmailBySessionId'
type MockRepository_SaveEmailBySessionId_Call struct {
	*mock.Call
}

// SaveEmailBySessionId is a helper method to define mock.On call
//   - sessionId gocql.UUID
//   - email string
func (_e *MockRepository_Expecter) SaveEmailBySessionId(sessionId any, email any) *MockRepository_SaveEmailBySessionId_Call {
	return &MockRepository_SaveEmailBySessionId_Call{Call: _e.mock.On("SaveEmailBySessionId", sessionId, email)}
}

func (_c *MockRepository_SaveEmailBySessionId_Call) Run(run func(sessionId gocql.UUID, email string)) *MockRepository_SaveEmailBySessionId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocql.UUID
		if args[0] != nil {
			arg0 = args[0].(gocql.UUID)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SaveEmailBySessionId_Call) Return(err error) *MockRepository_SaveEmailBySessionId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveEmailBySessionId_Call) RunAndReturn(run func(sessionId gocql.UUID, email string) error) *MockRepository_SaveEmailBySessionId_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEmailLoginInfo provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveEmailLoginInfo(id gocql.UUID, email string, password string) error {
	ret := _mock.Called(id, email, password)

	if len(ret) == 0 {
		panic("no return value specified for SaveEmailLoginInfo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID, string, string) error); ok {
		r0 = returnFunc(id, email, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveEmailLoginInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEmailLoginInfo'
type MockRepository_SaveEmailLoginInfo_Call struct {
	*mock.Call
}

// SaveEmailLoginInfo is a helper method to define mock.On call
//   - id gocql.UUID
//   - email string
//   - password string
func (_e *MockRepository_Expecter) SaveEmailLoginInfo(id any, email any, password any) *MockRepository_SaveEmailLoginInfo_Call {
	return &MockRepository_SaveEmailLoginInfo_Call{Call: _e.mock.On("SaveEmailLoginInfo", id, email, password)}
}

func (_c *MockRepository_SaveEmailLoginInfo_Call) Run(run func(id gocql.UUID, email string, password string)) *MockRepository_SaveEmailLoginInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocql.UUID
		if args[0] != nil {
			arg0 = args[0].(gocql.UUID)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SaveEmailLoginInfo_Call) Return(err error) *MockRepository_SaveEmailLoginInfo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveEmailLoginInfo_Call) RunAndReturn(run func(id gocql.UUID, email string, password string) error) *MockRepository_SaveEmailLoginInfo_Call {
	_c.Call.Return(run)
	return _c
}

// SaveNonce provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveNonce(nonce string) error {
	ret := _mock.Called(nonce)

	if len(ret) == 0 {
		panic("no return value specified for SaveNonce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(nonce)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveNonce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveNonce'
type MockRepository_SaveNonce_Call struct {
	*mock.Call
}

// SaveNonce is a helper method to define mock.On call
//   - nonce string
func (_e *MockRepository_Expecter) SaveNonce(nonce any) *MockRepository_SaveNonce_Call {
	return &MockRepository_SaveNonce_Call{Call: _e.mock.On("SaveNonce", nonce)}
}

func (_c *MockRepository_SaveNonce_Call) Run(run func(nonce string)) *MockRepository_SaveNonce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_SaveNonce_Call) Return(err error) *MockRepository_SaveNonce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveNonce_Call) RunAndReturn(run func(nonce string) error) *MockRepository_SaveNonce_Call {
	_c.Call.Return(run)
	return _c
}

// SavePhoneNumberByVerificationId provides a mock function for the type MockRepository
func (_mock *MockRepository) SavePhoneNumberByVerificationId(verificationId gocql.UUID, phoneNumber string) error {
	ret := _mock.Called(verificationId, phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for SavePhoneNumberByVerificationId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID, string) error); ok {
		r0 = returnFunc(verificationId, phoneNumber)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SavePhoneNumberByVerificationId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SavePhoneNumberByVerificationId'
type MockRepository_SavePhoneNumberByVerificationId_Call struct {
	*mock.Call
}

// SavePhoneNumberByVerificationId is a helper method to define mock.On call
//   - verificationId gocql.UUID
//   - phoneNumber string
func (_e *MockRepository_Expecter) SavePhoneNumberByVerificationId(verificationId any, phoneNumber any) *MockRepository_SavePhoneNumberByVerificationId_Call {
	return &MockRepository_SavePhoneNumberByVerificationId_Call{Call: _e.mock.On("SavePhoneNumberByVerificationId", verificationId, phoneNumber)}
}

func (_c *MockRepository_SavePhoneNumberByVerificationId_Call) Run(run func(verificationId gocql.UUID, phoneNumber string)) *MockRepository_SavePhoneNumberByVerificationId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocql.UUID
		if args[0] != nil {
			arg0 = args[0].(gocql.UUID)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SavePhoneNumberByVerificationId_Call) Return(err error) *MockRepository_SavePhoneNumberByVerificationId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SavePhoneNumberByVerificationId_Call) RunAndReturn(run func(verificationId gocql.UUID, phoneNumber string) error) *MockRepository_SavePhoneNumberByVerificationId_Call {
	_c.Call.Return(run)
	return _c
}

// SavePhoneNumberLoginInfo provides a mock function for the type MockRepository
func (_mock *MockRepository) SavePhoneNumberLoginInfo(phoneNumber string, id gocql.UUID) error {
	ret := _mock.Called(phoneNumber, id)

	if len(ret) == 0 {
		panic("no return value specified for SavePhoneNumberLoginInfo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, gocql.UUID) error); ok {
		r0 = returnFunc(phoneNumber, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SavePhoneNumberLoginInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SavePhoneNumberLoginInfo'
type MockRepository_SavePhoneNumberLoginInfo_Call struct {
	*mock.Call
}

// SavePhoneNumberLoginInfo is a helper method to define mock.On call
//   - phoneNumber string
//   - id gocql.UUID
func (_e *MockRepository_Expecter) SavePhoneNumberLoginInfo(phoneNumber any, id any) *MockRepository_SavePhoneNumberLoginInfo_Call {
	return &MockRepository_SavePhoneNumberLoginInfo_Call{Call: _e.mock.On("SavePhoneNumberLoginInfo", phoneNumber, id)}
}

func (_c *MockRepository_SavePhoneNumberLoginInfo_Call) Run(run func(phoneNumber string, id gocql.UUID)) *MockRepository_SavePhoneNumberLoginInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SavePhoneNumberLoginInfo_Call) Return(err error) *MockRepository_SavePhoneNumberLoginInfo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SavePhoneNumberLoginInfo_Call) RunAndReturn(run func(phoneNumber string, id gocql.UUID) error) *MockRepository_SavePhoneNumberLoginInfo_Call {
	_c.Call.Return(run)
	return _c
}

// SaveProfileId provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveProfileId(id gocql.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for SaveProfileId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveProfileId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveProfileId'
type MockRepository_SaveProfileId_Call struct {
	*mock.Call
}

// SaveProfileId is a helper method to define mock.On call
//   - id gocql.UUID
func (_e *MockRepository_Expecter) SaveProfileId(id any) *MockRepository_SaveProfileId_Call {
	return &MockRepository_SaveProfileId_Call{Call: _e.mock.On("SaveProfileId", id)}
}

func (_c *MockRepository_SaveProfileId_Call) Run(run func(id gocql.UUID)) *MockRepository_SaveProfileId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocql.UUID
		if args[0] != nil {
			arg0 = args[0].(gocql.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_SaveProfileId_Call) Return(err error) *MockRepository_SaveProfileId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveProfileId_Call) RunAndReturn(run func(id gocql.UUID) error) *MockRepository_SaveProfileId_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRefreshTokenJTIById provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveRefreshTokenJTIById(id gocql.UUID, jti gocql.UUID) error {
	ret := _mock.Called(id, jti)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshTokenJTIById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(gocql.UUID, gocql.UUID) error); ok {
		r0 = returnFunc(id, jti)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveRefreshTokenJTIById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRefreshTokenJTIById'
type MockRepository_SaveRefreshTokenJTIById_Call struct {
	*mock.Call
}

// SaveRefreshTokenJTIById is a helper method to define mock.On call
//   - id gocql.UUID
//   - jti gocql.UUID
func (_e *MockRepository_Expecter) SaveRefreshTokenJTIById(id any, jti any) *MockRepository_SaveRefreshTokenJTIById_Call {
	return &MockRepository_SaveRefreshTokenJTIById_Call{Call: _e.mock.On("SaveRefreshTokenJTIById", id, jti)}
}

func (_c *MockRepository_SaveRefreshTokenJTIById_Call) Run(run func(id gocql.UUID, jti gocql.UUID)) *MockRepository_SaveRefreshTokenJTIById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocql.UUID
		if args[0] != nil {
			arg0 = args[0].(gocql.UUID)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SaveRefreshTokenJTIById_Call) Return(err error) *MockRepository_SaveRefreshTokenJTIById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveRefreshTokenJTIById_Call) RunAndReturn(run func(id gocql.UUID, jti gocql.UUID) error) *MockRepository_SaveRefreshTokenJTIById_Call {
	_c.Call.Return(run)
	return _c
}

// SaveThirdPartySignInInfo provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveThirdPartySignInInfo(ctx context.Context, id gocql.UUID, email string, phoneNumberVerified bool, emailVerified bool) error {
	ret := _mock.Called(ctx, id, email, phoneNumberVerified, emailVerified)

	if len(ret) == 0 {
		panic("no return value specified for SaveThirdPartySignInInfo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocql.UUID, string, bool, bool) error); ok {
		r0 = returnFunc(ctx, id, email, phoneNumberVerified, emailVerified)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveThirdPartySignInInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveThirdPartySignInInfo'
type MockRepository_SaveThirdPartySignInInfo_Call struct {
	*mock.Call
}

// SaveThirdPartySignInInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - id gocql.UUID
//   - email string
//   - phoneNumberVerified bool
//   - emailVerified bool
func (_e *MockRepository_Expecter) SaveThirdPartySignInInfo(ctx any, id any, email any, phoneNumberVerified any, emailVerified any) *MockRepository_SaveThirdPartySignInInfo_Call {
	return &MockRepository_SaveThirdPartySignInInfo_Call{Call: _e.mock.On("SaveThirdPartySignInInfo", ctx, id, email, phoneNumberVerified, emailVerified)}
}

func (_c *MockRepository_SaveThirdPartySignInInfo_Call) Run(run func(ctx context.Context, id gocql.UUID, email string, phoneNumberVerified bool, emailVerified bool)) *MockRepository_SaveThirdPartySignInInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocql.UUID
		if args[1] != nil {
			arg1 = args[1].(gocql.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_SaveThirdPartySignInInfo_Call) Return(err error) *MockRepository_SaveThirdPartySignInInfo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveThirdPartySignInInfo_Call) RunAndReturn(run func(ctx context.Context, id gocql.UUID, email string, phoneNumberVerified bool, emailVerified bool) error) *MockRepository_SaveThirdPartySignInInfo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePasswordByEmail provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdatePasswordByEmail(ctx context.Context, password string, email string) error {
	ret := _mock.Called(ctx, password, email)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePasswordByEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, password, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdatePasswordByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePasswordByEmail'
type MockRepository_UpdatePasswordByEmail_Call struct {
	*mock.Call
}

// UpdatePasswordByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - password string
//   - email string
func (_e *MockRepository_Expecter) UpdatePasswordByEmail(ctx any, password any, email any) *MockRepository_UpdatePasswordByEmail_Call {
	return &MockRepository_UpdatePasswordByEmail_Call{Call: _e.mock.On("UpdatePasswordByEmail", ctx, password, email)}
}

func (_c *MockRepository_UpdatePasswordByEmail_Call) Run(run func(ctx context.Context, password string, email string)) *MockRepository_UpdatePasswordByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdatePasswordByEmail_Call) Return(err error) *MockRepository_UpdatePasswordByEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdatePasswordByEmail_Call) RunAndReturn(run func(ctx context.Context, password string, email string) error) *MockRepository_UpdatePasswordByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// VerifiedEmailExists provides a mock function for the type MockRepository
func (_mock *MockRepository) VerifiedEmailExists(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for VerifiedEmailExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_VerifiedEmailExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifiedEmailExists'
type MockRepository_VerifiedEmailExists_Call struct {
	*mock.Call
}

// VerifiedEmailExists is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRepository_Expecter) VerifiedEmailExists(ctx any, email any) *MockRepository_VerifiedEmailExists_Call {
	return &MockRepository_VerifiedEmailExists_Call{Call: _e.mock.On("VerifiedEmailExists", ctx, email)}
}

func (_c *MockRepository_VerifiedEmailExists_Call) Run(run func(ctx context.Context, email string)) *MockRepository_VerifiedEmailExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_VerifiedEmailExists_Call) Return(b bool, err error) *MockRepository_VerifiedEmailExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_VerifiedEmailExists_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *MockRepository_VerifiedEmailExists_Call {
	_c.Call.Return(run)
	return _c
}

// WasBanned provides a mock function for the type MockRepository
func (_mock *MockRepository) WasBanned(phoneNumber string) error {
	ret := _mock.Called(phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for WasBanned")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(phoneNumber)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_WasBanned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WasBanned'
type MockRepository_WasBanned_Call struct {
	*mock.Call
}

// WasBanned is a helper method to define mock.On call
//   - phoneNumber string
func (_e *MockRepository_Expecter) WasBanned(phoneNumber any) *MockRepository_WasBanned_Call {
	return &MockRepository_WasBanned_Call{Call: _e.mock.On("WasBanned", phoneNumber)}
}

func (_c *MockRepository_WasBanned_Call) Run(run func(phoneNumber string)) *MockRepository_WasBanned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_WasBanned_Call) Return(err error) *MockRepository_WasBanned_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_WasBanned_Call) RunAndReturn(run func(phoneNumber string) error) *MockRepository_WasBanned_Call {
	_c.Call.Return(run)
	return _c
}
