// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSMSClient creates a new instance of MockSMSClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSMSClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSMSClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSMSClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSMSClient is an autogenerated mock type for the SMSClient type
type MockSMSClient struct {
	mock.Mock
}

type MockSMSClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSMSClient) EXPECT() *MockSMSClient_Expecter {
	return &MockSMSClient_Expecter{mock: &_m.Mock}
}

// CheckOTP provides a mock function for the type MockSMSClient
func (_mock *MockSMSClient) CheckOTP(phone string, code string) (bool, error) {
	ret := _mock.Called(phone, code)

	if len(ret) == 0 {
		panic("no return value specified for CheckOTP")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(phone, code)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(phone, code)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(phone, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSMSClient_CheckOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckOTP'
type MockSMSClient_CheckOTP_Call struct {
	*mock.Call
}

// CheckOTP is a helper method to define mock.On call
//   - phone string
//   - code string
func (_e *MockSMSClient_Expecter) CheckOTP(phone any, code any) *MockSMSClient_CheckOTP_Call {
	return &MockSMSClient_CheckOTP_Call{Call: _e.mock.On("CheckOTP", phone, code)}
}

func (_c *MockSMSClient_CheckOTP_Call) Run(run func(phone string, code string)) *MockSMSClient_CheckOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSMSClient_CheckOTP_Call) Return(b bool, err error) *MockSMSClient_CheckOTP_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSMSClient_CheckOTP_Call) RunAndReturn(run func(phone string, code string) (bool, error)) *MockSMSClient_CheckOTP_Call {
	_c.Call.Return(run)
	return _c
}

// SendOTP provides a mock function for the type MockSMSClient
func (_mock *MockSMSClient) SendOTP(phone string) (string, error) {
	ret := _mock.Called(phone)

	if len(ret) == 0 {
		panic("no return value specified for SendOTP")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(phone)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(phone)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(phone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSMSClient_SendOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOTP'
type MockSMSClient_SendOTP_Call struct {
	*mock.Call
}

// SendOTP is a helper method to define mock.On call
//   - phone string
func (_e *MockSMSClient_Expecter) SendOTP(phone any) *MockSMSClient_SendOTP_Call {
	return &MockSMSClient_SendOTP_Call{Call: _e.mock.On("SendOTP", phone)}
}

func (_c *MockSMSClient_SendOTP_Call) Run(run func(phone string)) *MockSMSClient_SendOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSMSClient_SendOTP_Call) Return(s string, err error) *MockSMSClient_SendOTP_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSMSClient_SendOTP_Call) RunAndReturn(run func(phone string) (string, error)) *MockSMSClient_SendOTP_Call {
	_c.Call.Return(run)
	return _c
}
