spring:
  application:
    name: search
  kafka:
    bootstrap-servers: ${KAFKA_ADDRESS}
  elasticsearch:
    uris: ${OPENSEARCH_HOST}:${OPENSEARCH_PORT}
    username: ${OPENSEARCH_USERNAME}
    password: ${OPENSEARCH_PASSWORD}
