name: messagepreprocess-ci
on:
  push:
    branches:
      - main
    paths:
      - 'backend/messagepreprocess/**'
      - 'backend/common/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v6

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: build and push messagepreprocess
        env:
          REGISTRY: 565319458549.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: backend/messagepreprocess
          IMAGE_TAG: latest
        run: |
          docker buildx build --platform linux/amd64 \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./backend/messagepreprocess/Dockerfile ./backend --push